# -*- coding: utf-8 -*-
"""Complements : tolerance au bord de mer et densite de plantation.
bdm  : Front de mer / Second rideau / Deconseille en bord de mer
dens : sujets au m2 (plantation en masse)
esp  : distance de plantation entre deux sujets, en metres
"""

COMPLEMENTS = {
 "Abelia grandiflora":        ("Second rideau", 0.5, 1.4),
 "Achillea millefolium":      ("Front de mer", 5, 0.45),
 "Ajuga reptans":             ("Second rideau", 9, 0.33),
 "Anemone hupehensis":        ("Second rideau", 4, 0.5),
 "Aubrieta":                  ("Front de mer", 6, 0.4),
 "Azalea japonica":           ("Déconseillé en bord de mer", 1.5, 0.8),
 "Buddleia davidii":          ("Second rideau", 0.3, 1.8),
 "Calamagrostis acutiflora":  ("Second rideau", 3, 0.6),
 "Carex morrowii":            ("Second rideau", 6, 0.4),
 "Cornus alba":               ("Second rideau", 0.5, 1.5),
 "Corylus avellana":          ("Second rideau", 0.15, 2.5),
 "Cotoneaster":               ("Front de mer", 2, 0.7),
 "Cupressocyparis leylandii": ("Second rideau", 0.5, 1.0),
 "Deschampsia cespitosa":     ("Second rideau", 4, 0.5),
 "Euphorbia characias":       ("Front de mer", 1.5, 0.8),
 "Ficus carica":              ("Front de mer", 0.06, 4.0),
 "Gaura lindheimeri":         ("Front de mer", 3, 0.6),
 "Geranium":                  ("Second rideau", 6, 0.4),
 "Hedera":                    ("Front de mer", 4, 0.5),
 "Hibiscus syriacus":         ("Second rideau", 0.4, 1.5),
 "Hosta":                     ("Déconseillé en bord de mer", 3, 0.6),
 "Hydrangea macrophylla":     ("Front de mer", 0.7, 1.2),
 "Hydrangea paniculata":      ("Second rideau", 0.5, 1.4),
 "Lagerstroemia indica":      ("Second rideau", 0.15, 2.5),
 "Lavandula angustifolia":    ("Front de mer", 4, 0.5),
 "Lavandula intermedia":      ("Front de mer", 2, 0.7),
 "Malus domestica":           ("Déconseillé en bord de mer", 0.06, 4.0),
 "Miscanthus sinensis":       ("Second rideau", 1, 1.0),
 "Nandina domestica":         ("Second rideau", 1.5, 0.8),
 "Pennisetum alopecuroides":  ("Second rideau", 3, 0.6),
 "Perovskia atriplicifolia":  ("Front de mer", 2, 0.7),
 "Physocarpus opulifolius":   ("Second rideau", 0.5, 1.4),
 "Potentilla fruticosa":      ("Front de mer", 1.5, 0.8),
 "Prunus avium":              ("Second rideau", 0.03, 6.0),
 "Prunus domestica":          ("Second rideau", 0.06, 4.0),
 "Prunus laurocerasus":       ("Second rideau", 0.7, 1.2),
 "Prunus persica":            ("Déconseillé en bord de mer", 0.06, 4.0),
 "Pyracantha":                ("Front de mer", 0.6, 1.2),
 "Pyrus domestica":           ("Second rideau", 0.06, 4.0),
 "Rosa":                      ("Second rideau", 2, 0.7),
 "Rosmarinus officinalis":    ("Front de mer", 1.5, 0.8),
 "Salvia microphylla":        ("Front de mer", 1.5, 0.8),
 "Salvia nemorosa":           ("Second rideau", 6, 0.4),
 "Salvia officinalis":        ("Front de mer", 2.5, 0.6),
 "Spiraea japonica":          ("Second rideau", 1.5, 0.8),
 "Thymus vulgaris":           ("Front de mer", 6, 0.4),
 "Viburnum opulus":           ("Second rideau", 0.3, 1.8),
 "Viburnum tinus":            ("Front de mer", 0.6, 1.3),
 "Vinca":                     ("Second rideau", 5, 0.45),
 "Weigelia":                  ("Second rideau", 0.5, 1.4),
}
