# -*- coding: utf-8 -*-
"""Lot 2 - 50 especes supplementaires du catalogue AD.V.

ALIAS : variantes d'ecriture du catalogue rattachees a une fiche existante,
plutot que de creer des doublons vides.
"""

ALIAS = {
    "Potentilla fructicosa": "Potentilla fruticosa",
    "Euphorbia":             "Euphorbia characias",
    "Pennisetum alop.":      "Pennisetum alopecuroides",
    "Salvia":                "Salvia nemorosa",
    "Salvia grahamii":       "Salvia microphylla",
    "Cornus":                "Cornus alba",
    "Gaura":                 "Gaura lindheimeri",
    "Spiraea":               "Spiraea japonica",
    "Spiraea bumalda":       "Spiraea japonica",
    "Thymus":                "Thymus vulgaris",
    "Buddleia":              "Buddleia davidii",
    "Weigelia florida":      "Weigelia",
    "Hypericum":             "Hypericum calycinum",
    "Lavandula":             "Lavandula angustifolia",
    "Miscanthus":            "Miscanthus sinensis",
    "Perovskia":             "Perovskia atriplicifolia",
    "Hydrangea":             "Hydrangea macrophylla",
    "Pennisetum":            "Pennisetum alopecuroides",
}

FICHES2 = [
{"lat":"Acer platanoides","fr":"Érable plane","type":"Arbre","h":20.0,"l":12.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, profond, calcaire toléré","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert, jaune d'or en automne","m1":4,"m2":4,"flo":"Avril","cflo":"Jaune verdâtre",
 "plant":"Automne","popt":"Novembre à février","ent":"Faible",
 "style":"Arbre d'ombrage, alignement, grand jardin, parc",
 "asso":"Prairie, bulbes de printemps au pied, haie champêtre",
 "cons":"Très rustique et sans exigence, mais sous-estimer son volume adulte est l'erreur classique : 20 m de haut, ce n'est pas un arbre de petit jardin. Ombre dense et racines superficielles qui compliquent les plantations au pied. Les cultivars pourpres comme Crimson King restent plus modestes.",
 "bdm":"Second rideau","dens":0.02,"esp":8.0},

{"lat":"Agapanthus africanus","fr":"Agapanthe","type":"Vivace","h":0.9,"l":0.5,
 "expo":"Plein soleil","sol":"Drainé, léger, sableux","hum":"Sec à frais","rust":-10,
 "feu":"Semi-persistant","cfeu":"Vert franc","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Bleu, blanc",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin de bord de mer, massif estival, bordure, potée, jardin méditerranéen",
 "asso":"Gaura, graminées, Perovskia, Phormium, Salvia",
 "cons":"Emblématique des jardins bretons et vendéens. Fleurit mieux à l'étroit : ne pas diviser trop souvent ni planter trop large. Rusticité limitée, prévoir un paillage hivernal en secteur froid. Les variétés à feuillage caduc sont nettement plus résistantes au froid que les persistantes.",
 "bdm":"Front de mer","dens":4,"esp":0.5},

{"lat":"Alstroemeria","fr":"Lis des Incas","type":"Vivace","h":0.8,"l":0.4,
 "expo":"Soleil à mi-ombre","sol":"Drainé, humifère, profond","hum":"Frais","rust":-12,
 "feu":"Caduc","cfeu":"Vert franc","m1":6,"m2":10,"flo":"Juin à octobre","cflo":"Rose, orange, jaune, rouge, blanc",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Massif fleuri, bordure, jardin de fleurs à couper",
 "asso":"Geranium vivace, Nepeta, graminées, Salvia, rosiers",
 "cons":"Floraison très longue et excellente tenue en vase, ce qui plaît beaucoup aux clients. Racines charnues fragiles : manipuler la motte sans la casser à la plantation. Paillage hivernal les deux premières années. Ne pas couper les tiges fanées mais les tirer doucement, cela stimule la reprise de floraison.",
 "bdm":"Second rideau","dens":5,"esp":0.4},

{"lat":"Bulbine frutescens","fr":"Bulbine","type":"Vivace","h":0.5,"l":0.5,
 "expo":"Plein soleil","sol":"Drainé, sableux, pauvre","hum":"Sec","rust":-5,
 "feu":"Persistant","cfeu":"Vert clair charnu","m1":4,"m2":11,"flo":"Avril à novembre","cflo":"Jaune, orange",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Jardin sec, rocaille, potée, jardin méditerranéen, bord de mer",
 "asso":"Delosperma, Sedum, Euphorbia, graminées sèches, Yucca",
 "cons":"Floraison quasi continue et très sobre en eau. Rusticité faible : à réserver aux situations très abritées, ou à traiter comme une plante de potée à rentrer. En pleine terre en Loire-Atlantique, elle passera les hivers doux mais pas une vague de froid marquée. À proposer en connaissance de cause.",
 "bdm":"Front de mer","dens":4,"esp":0.5},

{"lat":"Carpinus betulus","fr":"Charme commun","type":"Arbre","h":15.0,"l":8.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, calcaire toléré, argileux toléré","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert, jaune ocre en automne","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Vert (chatons)",
 "plant":"Automne","popt":"Novembre à février","ent":"Moyen",
 "style":"Haie taillée, charmille, alignement, écran, arbre d'ombrage",
 "asso":"Haie champêtre avec Cornus, Viburnum, Corylus, Crataegus",
 "cons":"Le meilleur choix pour une haie taillée en climat atlantique, plus fiable que le hêtre en sol lourd. Conserve ses feuilles sèches tout l'hiver quand il est taillé, ce qui en fait un brise-vue toute l'année. Une taille par an en juillet suffit. Compter 3 plants par mètre linéaire en haie.",
 "bdm":"Second rideau","dens":0.03,"esp":0.35},

{"lat":"Caryopteris clandonensis","fr":"Barbe-bleue","type":"Arbuste","h":1.0,"l":1.0,
 "expo":"Plein soleil","sol":"Drainé, calcaire toléré, pauvre","hum":"Sec","rust":-20,
 "feu":"Caduc","cfeu":"Vert grisé ou doré","m1":8,"m2":10,"flo":"Août à octobre","cflo":"Bleu",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin sec, massif de fin d'été, bordure, jardin de gravier",
 "asso":"Perovskia, Sedum, graminées, Gaura, Rudbeckia",
 "cons":"Floraison bleue rare à cette saison, très mellifère. Rabattre à 15 cm en fin d'hiver, il fleurit sur le bois de l'année. Redoute les sols lourds et humides en hiver bien plus que le froid. Démarrage tardif au printemps, ne pas le croire mort en avril.",
 "bdm":"Second rideau","dens":1,"esp":1.0},

{"lat":"Chaenomeles superba","fr":"Cognassier du Japon","type":"Arbuste","h":1.5,"l":2.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, calcaire toléré","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert brillant","m1":2,"m2":4,"flo":"Février à avril","cflo":"Rouge, rose, orange, blanc",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie défensive, palissage sur mur, jardin de curé, massif de printemps",
 "asso":"Forsythia, Spiraea, bulbes de printemps, Hedera",
 "cons":"Floraison très précoce sur bois nu, souvent dès février : un des premiers spectacles de l'année. Rameaux épineux, à écarter des passages. Se palisse très bien contre un mur, y compris au nord. Petits coings comestibles en gelée. Taille après floraison uniquement.",
 "bdm":"Second rideau","dens":0.4,"esp":1.5},

{"lat":"Cistus pulverulentus","fr":"Ciste","type":"Arbuste","h":0.8,"l":1.0,
 "expo":"Plein soleil","sol":"Drainé, sec, pauvre, caillouteux","hum":"Sec","rust":-12,
 "feu":"Persistant","cfeu":"Vert grisé","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Rose fuchsia",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin méditerranéen, talus, rocaille, jardin sec, bord de mer",
 "asso":"Lavandula, Santolina, Rosmarinus, Phlomis, Stipa",
 "cons":"Fleurs éphémères mais renouvelées chaque matin pendant deux mois. Aucun arrosage une fois installé, aucun amendement : l'excès de richesse le tue. Ne supporte pas la taille sur vieux bois, se contenter d'un pincement léger après floraison. Durée de vie courte, 8 à 10 ans.",
 "bdm":"Front de mer","dens":1.5,"esp":0.8},

{"lat":"Cistus purpureus","fr":"Ciste pourpre","type":"Arbuste","h":1.2,"l":1.2,
 "expo":"Plein soleil","sol":"Drainé, sec, pauvre, calcaire toléré","hum":"Sec","rust":-12,
 "feu":"Persistant","cfeu":"Vert grisé","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Rose pourpré à macule rouge",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin méditerranéen, massif sec, talus, bord de mer",
 "asso":"Lavandula, Cistus, Phlomis, Euphorbia, graminées sèches",
 "cons":"Le plus spectaculaire des cistes, avec une macule sombre au cœur de chaque fleur. Mêmes exigences que les autres cistes : drainage impératif, sol pauvre, pas d'arrosage. Craint l'humidité hivernale stagnante. Planter au printemps pour un bon enracinement avant l'hiver.",
 "bdm":"Front de mer","dens":1,"esp":1.0},

{"lat":"Cotoneaster dammeri","fr":"Cotonéaster rampant","type":"Couvre-sol","h":0.3,"l":1.5,
 "expo":"Soleil à mi-ombre","sol":"Tout type, drainé, calcaire toléré","hum":"Sec à frais","rust":-25,
 "feu":"Persistant","cfeu":"Vert foncé brillant","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Blanc",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Talus, couvre-sol de masse, pied de mur, aménagement collectif, dessus de muret",
 "asso":"Juniperus rampant, Hedera, Vinca, graminées basses",
 "cons":"Couvre-sol tapissant très efficace, y compris sur talus difficile à entretenir. Baies rouges décoratives tout l'hiver. Compter 3 plants au m² pour une couverture en deux saisons. Sensible au feu bactérien : éviter la taille par temps humide.",
 "bdm":"Front de mer","dens":3,"esp":0.6},

{"lat":"Deutzia magnifica","fr":"Deutzia","type":"Arbuste","h":2.5,"l":2.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, frais, humifère","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Blanc pur",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie libre fleurie, massif de printemps, jardin de curé, jardin blanc",
 "asso":"Philadelphus, Weigelia, Spiraea, Syringa, Viburnum",
 "cons":"Floraison blanche très abondante, en grappes doubles chez ce cultivar. Tailler juste après la floraison : il fleurit sur le bois de l'année précédente. Supprimer un tiers des vieilles branches à la base tous les trois ans pour éviter qu'il s'épuise. Sans aucune difficulté par ailleurs.",
 "bdm":"Second rideau","dens":0.4,"esp":1.5},

{"lat":"Elaeagnus ebbingei","fr":"Chalef de Ebbinge","type":"Arbuste","h":3.0,"l":2.5,
 "expo":"Soleil à mi-ombre","sol":"Tout type, drainé, calcaire toléré, pauvre","hum":"Sec à frais","rust":-18,
 "feu":"Persistant","cfeu":"Vert argenté, revers écailleux","m1":10,"m2":11,"flo":"Octobre à novembre","cflo":"Blanc crème",
 "plant":"Automne à printemps","popt":"Septembre à novembre ou mars","ent":"Faible",
 "style":"Haie brise-vent, écran persistant, jardin de bord de mer, haie mixte",
 "asso":"Photinia, Viburnum tinus, Prunus lusitanica, Pittosporum, Griselinia",
 "cons":"L'arbuste de haie le plus résistant au vent et aux embruns : c'est lui qu'on plante en premier rideau pour protéger le reste. Floraison automnale discrète mais au parfum puissant, très apprécié. Deux tailles annuelles pour une haie nette. Supprimer les rameaux entièrement verts qui apparaissent sur les cultivars panachés.",
 "bdm":"Front de mer","dens":0.5,"esp":1.0},

{"lat":"Euonymus","fr":"Fusain de Fortune","type":"Couvre-sol / Arbuste","h":0.8,"l":1.2,
 "expo":"Soleil à ombre","sol":"Tout type, drainé, calcaire toléré","hum":"Frais","rust":-20,
 "feu":"Persistant","cfeu":"Vert, panaché de blanc ou de jaune","m1":6,"m2":7,"flo":"Juin à juillet","cflo":"Vert discret",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Couvre-sol lumineux, bordure, massif d'ombre, potée, aménagement collectif",
 "asso":"Hedera, Vinca, Carex, Heuchera, Nandina",
 "cons":"Cultivé pour son feuillage panaché qui éclaire les zones sombres. Extrêmement tolérant : soleil ou ombre, tout type de sol. Peut grimper s'il trouve un support. Les rameaux entièrement verts qui apparaissent doivent être supprimés, sinon ils prennent le dessus sur la panachure.",
 "bdm":"Front de mer","dens":2,"esp":0.7},

{"lat":"Festuca glauca","fr":"Fétuque bleue","type":"Graminée","h":0.3,"l":0.3,
 "expo":"Plein soleil","sol":"Drainé, sec, pauvre, caillouteux","hum":"Sec","rust":-25,
 "feu":"Persistant","cfeu":"Bleu argenté","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Beige",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Rocaille, bordure, jardin de gravier, massif contemporain, potée",
 "asso":"Sedum, Delosperma, Lavandula, Santolina, Euphorbia",
 "cons":"Cultivée pour sa couleur bleue, qui exige le plein soleil et un sol pauvre : à l'ombre ou en sol riche elle verdit. Redoute l'humidité hivernale, drainage impératif. Peigner à la main au printemps plutôt que rabattre. Se dégarnit au centre après 3 ou 4 ans, prévoir la division ou le remplacement.",
 "bdm":"Front de mer","dens":6,"esp":0.4},

{"lat":"Forsythia intermedia","fr":"Forsythia","type":"Arbuste","h":2.5,"l":2.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, calcaire toléré","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc","m1":3,"m2":4,"flo":"Mars à avril","cflo":"Jaune d'or",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie libre, jardin de curé, massif de printemps, fond de massif",
 "asso":"Chaenomeles, Spiraea, bulbes de printemps, Weigelia",
 "cons":"Explosion jaune sur bois nu en mars, puis silhouette banale le reste de l'année : à placer en fond de massif plutôt qu'en vedette. Tailler juste après la floraison, jamais en hiver. Recéper un tiers des vieilles branches chaque année, sinon il s'épuise et fleurit moins. Sans aucune exigence de sol.",
 "bdm":"Second rideau","dens":0.4,"esp":1.5},

{"lat":"Geranium macrorrhizum","fr":"Géranium à grosses racines","type":"Couvre-sol","h":0.35,"l":0.6,
 "expo":"Mi-ombre à ombre","sol":"Tout type, drainé, calcaire toléré","hum":"Sec à frais","rust":-25,
 "feu":"Semi-persistant","cfeu":"Vert clair aromatique, rouge en automne","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Rose, blanc",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Couvre-sol d'ombre sèche, pied d'arbre, talus, sous-bois",
 "asso":"Hosta, fougères, Epimedium, Vinca, Carex",
 "cons":"Le meilleur couvre-sol pour l'ombre sèche sous les arbres, là où presque rien ne tient. Feuillage aromatique que les limaces et les chevreuils dédaignent. Couvre totalement en deux saisons et étouffe les adventices. Rabattre le feuillage abîmé en fin d'hiver. Aucune exigence.",
 "bdm":"Second rideau","dens":6,"esp":0.4},

{"lat":"Hemerocallis","fr":"Hémérocalle","type":"Vivace","h":0.7,"l":0.6,
 "expo":"Soleil à mi-ombre","sol":"Tout type, profond, frais","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc","m1":6,"m2":8,"flo":"Juin à août","cflo":"Jaune, orange, rouge, rose, bicolore",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Massif fleuri, bordure, talus, bord de bassin, aménagement collectif",
 "asso":"Graminées, Rudbeckia, Echinacea, Salvia, Persicaria",
 "cons":"Chaque fleur ne dure qu'un jour, d'où son nom, mais la succession assure deux mois de floraison. Vivace increvable et sans maladie, excellente pour maintenir un talus. Supporte la sécheresse une fois installée. Diviser tous les 4 ou 5 ans quand la touffe s'épuise.",
 "bdm":"Second rideau","dens":4,"esp":0.5},

{"lat":"Heuchera","fr":"Heuchère","type":"Vivace / Couvre-sol","h":0.4,"l":0.4,
 "expo":"Mi-ombre","sol":"Drainé, humifère, frais","hum":"Frais","rust":-20,
 "feu":"Persistant","cfeu":"Pourpre, caramel, doré, argenté, vert veiné","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Blanc, rose, rouge",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Moyen",
 "style":"Bordure d'ombre, massif de feuillages, potée, jardin contemporain",
 "asso":"Hosta, Carex, fougères, Tiarella, Ajuga",
 "cons":"Cultivée pour son feuillage persistant coloré, disponible dans une gamme de teintes très large : c'est l'outil idéal pour éclairer un massif d'ombre toute l'année. Redoute le soleil brûlant et l'humidité stagnante. Tendance à se déchausser : rebutter ou replanter plus profond tous les 2 à 3 ans.",
 "bdm":"Second rideau","dens":5,"esp":0.4},

{"lat":"Hypericum calycinum","fr":"Millepertuis rampant","type":"Couvre-sol","h":0.4,"l":0.8,
 "expo":"Soleil à ombre","sol":"Tout type, drainé, pauvre toléré","hum":"Sec à frais","rust":-20,
 "feu":"Semi-persistant","cfeu":"Vert franc","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Jaune d'or",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Talus, couvre-sol de masse, pied d'arbre, aménagement collectif, sous-bois clair",
 "asso":"Cotoneaster, Hedera, Vinca, graminées, Euonymus",
 "cons":"Couvre-sol le plus économique pour habiller un talus difficile : il pousse partout, y compris en ombre sèche. Traçant, il faut lui donner de l'espace ou le contenir. Rabattre à ras tous les 2 ou 3 ans en fin d'hiver pour le régénérer. Peut être sensible à la rouille en situation confinée.",
 "bdm":"Second rideau","dens":4,"esp":0.5},

{"lat":"Juniperus chin","fr":"Genévrier de Chine","type":"Conifère","h":2.0,"l":2.5,
 "expo":"Plein soleil","sol":"Drainé, sec, calcaire toléré, pauvre","hum":"Sec","rust":-25,
 "feu":"Persistant","cfeu":"Vert bleuté ou doré","m1":0,"m2":0,"flo":"Non ornementale","cflo":"—",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Rocaille, talus, jardin sec, jardin japonais, couvre-sol de conifère",
 "asso":"Cotoneaster, Pinus mugo, graminées, Sedum, Lavandula",
 "cons":"Très rustique et sobre en eau, idéal pour un talus exposé. Ne repart pas sur le vieux bois : ne jamais tailler au-delà des pousses vertes, la zone dénudée le resterait. Les formes rampantes couvrent efficacement mais s'étalent plus que prévu, respecter les distances de plantation.",
 "bdm":"Front de mer","dens":0.5,"esp":1.5},

{"lat":"Juniperus communis","fr":"Genévrier commun","type":"Conifère","h":3.0,"l":1.0,
 "expo":"Plein soleil","sol":"Drainé, sec, calcaire, pauvre, caillouteux","hum":"Sec","rust":-30,
 "feu":"Persistant","cfeu":"Vert bleuté","m1":0,"m2":0,"flo":"Non ornementale","cflo":"—",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Jardin sec, silhouette verticale, rocaille, jardin naturaliste",
 "asso":"Lavandula, Stipa, Cistus, Santolina, graminées sèches",
 "cons":"Espèce indigène, extrêmement rustique et résistante à la sécheresse. Les formes fastigiées apportent une verticalité utile dans un massif bas. Croissance lente, ne pas espérer un effet rapide. Aucune taille nécessaire. Feuillage piquant, à écarter des passages.",
 "bdm":"Front de mer","dens":0.4,"esp":1.2},

{"lat":"Ligustrum ovalifolium","fr":"Troène de Californie","type":"Arbuste","h":3.0,"l":2.0,
 "expo":"Soleil à ombre","sol":"Tout type, calcaire toléré","hum":"Frais","rust":-20,
 "feu":"Semi-persistant","cfeu":"Vert brillant ou panaché de jaune","m1":6,"m2":7,"flo":"Juin à juillet","cflo":"Blanc crème",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Moyen",
 "style":"Haie taillée, écran, haie mixte, aménagement collectif",
 "asso":"Haie mixte avec Elaeagnus, Photinia, Viburnum tinus, Prunus laurocerasus",
 "cons":"Haie économique et rapide, qui repart bien après une taille sévère, contrairement aux conifères. Deux tailles annuelles pour une haie nette. Semi-persistant : il se dégarnit partiellement lors des hivers froids, à annoncer au client qui attend un persistant. Floraison au parfum entêtant, que certains n'apprécient pas.",
 "bdm":"Front de mer","dens":0.5,"esp":0.4},

{"lat":"Liriope muscari","fr":"Muguet du Japon","type":"Couvre-sol / Vivace","h":0.4,"l":0.4,
 "expo":"Mi-ombre à ombre","sol":"Drainé, humifère, frais","hum":"Frais","rust":-18,
 "feu":"Persistant","cfeu":"Vert foncé ou panaché","m1":8,"m2":10,"flo":"Août à octobre","cflo":"Violet, mauve, blanc",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Bordure d'ombre, sous-bois, jardin japonais, pied d'arbre, massif contemporain",
 "asso":"Ophiopogon, Carex, Hosta, fougères, Nandina, Acer palmatum",
 "cons":"Persistant précieux à l'ombre, avec une floraison en épis dressés à une saison où l'ombre est vide. Supporte la sécheresse une fois installé, y compris sous les arbres. Rabattre le feuillage abîmé en fin d'hiver. Croissance lente : planter dense pour un effet rapide.",
 "bdm":"Second rideau","dens":6,"esp":0.4},

{"lat":"Lonicera nitida","fr":"Chèvrefeuille à feuilles de buis","type":"Arbuste","h":1.5,"l":1.5,
 "expo":"Soleil à ombre","sol":"Tout type, calcaire toléré","hum":"Frais","rust":-18,
 "feu":"Persistant","cfeu":"Vert foncé ou doré","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Blanc crème discret",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Moyen",
 "style":"Haie basse taillée, bordure structurée, topiaire, remplacement du buis",
 "asso":"Haie basse seule, ou avec Lavandula, Santolina, rosiers",
 "cons":"L'alternative au buis la plus convaincante face à la pyrale : port dense, petites feuilles persistantes, se taille en volume géométrique. Croissance rapide, deux à trois tailles par an pour une bordure nette. Tolère l'ombre. Peut s'ouvrir sous le poids de la neige, une taille régulière l'évite.",
 "bdm":"Front de mer","dens":1,"esp":0.35},

{"lat":"Lythrum salicaria","fr":"Salicaire","type":"Vivace","h":1.2,"l":0.6,
 "expo":"Plein soleil","sol":"Tout type, argileux toléré, humifère","hum":"Humide","rust":-30,
 "feu":"Caduc","cfeu":"Vert franc","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Rose magenta",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Bord de bassin, noue, zone humide, jardin naturaliste, prairie humide",
 "asso":"Filipendula, Persicaria, Juncus, Molinia, Iris pseudacorus",
 "cons":"Espèce indigène des berges, l'une des rares vivaces à prospérer les pieds dans l'eau. Très mellifère. Solution idéale pour une zone détrempée où rien ne pousse, ou pour végétaliser une noue d'infiltration. Se ressème facilement en milieu humide, ce qui peut demander une régulation.",
 "bdm":"Second rideau","dens":4,"esp":0.5},

{"lat":"Magnolia soulangiana","fr":"Magnolia de Soulange","type":"Arbuste / Petit arbre","h":6.0,"l":5.0,
 "expo":"Soleil à mi-ombre","sol":"Humifère, drainé, acide à neutre, profond","hum":"Frais","rust":-20,
 "feu":"Caduc","cfeu":"Vert franc","m1":3,"m2":4,"flo":"Mars à avril","cflo":"Rose et blanc",
 "plant":"Printemps","popt":"Mars à avril","ent":"Faible",
 "style":"Sujet isolé, pièce maîtresse de jardin, massif de terre de bruyère",
 "asso":"Azalea, Rhododendron, Hosta, fougères, bulbes de printemps",
 "cons":"Floraison spectaculaire sur bois nu, mais très précoce et donc exposée aux gelées tardives : une nuit à -3 °C en mars brunit toutes les fleurs. Éviter les situations froides et les expositions est, où le soleil du matin brûle les fleurs gelées. Racines charnues fragiles : ne pas travailler le sol au pied, ne pas déplacer. Aucune taille.",
 "bdm":"Second rideau","dens":0.05,"esp":4.0},

{"lat":"Molinia arundinacea","fr":"Molinie élevée","type":"Graminée","h":2.0,"l":0.8,
 "expo":"Soleil à mi-ombre","sol":"Tout type, humifère, acide à neutre","hum":"Frais à humide","rust":-30,
 "feu":"Caduc","cfeu":"Vert, jaune d'or en automne","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Beige doré",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif naturaliste, écran léger, bord de bassin, jardin contemporain",
 "asso":"Persicaria, Sanguisorba, Deschampsia, Rudbeckia, Eupatorium",
 "cons":"Silhouette transparente en hauteur : on voit à travers, ce qui permet de l'utiliser en premier plan sans masquer. Couleur d'automne dorée remarquable, puis la touffe s'effondre d'un coup en novembre. Contrairement au Miscanthus, elle ne tient pas l'hiver : rabattre dès qu'elle se couche.",
 "bdm":"Second rideau","dens":1,"esp":1.0},

{"lat":"Nepeta faassenii","fr":"Népéta","type":"Vivace","h":0.5,"l":0.6,
 "expo":"Plein soleil","sol":"Drainé, calcaire toléré, pauvre","hum":"Sec","rust":-25,
 "feu":"Semi-persistant","cfeu":"Vert grisé aromatique","m1":5,"m2":9,"flo":"Mai à septembre","cflo":"Bleu lavande, mauve",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Bordure, pied de rosier, jardin sec, massif naturaliste, allée",
 "asso":"Rosiers, Salvia nemorosa, Gaura, Stipa, Perovskia, Achillea",
 "cons":"Le compagnon classique du rosier : il masque les pieds dénudés et fleurit en même temps. Rabattre de moitié après la première floraison pour une seconde vague jusqu'aux gelées. Très mellifère et résistant à la sécheresse. Les chats s'y roulent parfois, ce qui peut coucher la touffe.",
 "bdm":"Front de mer","dens":4,"esp":0.5},

{"lat":"Pachysandra terminalis","fr":"Pachysandre du Japon","type":"Couvre-sol","h":0.25,"l":0.4,
 "expo":"Mi-ombre à ombre","sol":"Humifère, frais, acide à neutre","hum":"Frais","rust":-25,
 "feu":"Persistant","cfeu":"Vert foncé brillant","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Blanc discret",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Sous-bois, pied d'arbre, massif d'ombre dense, façade nord",
 "asso":"Fougères, Hosta, Hedera, Carex, Epimedium",
 "cons":"Le couvre-sol de référence pour l'ombre dense, y compris sous conifères. Tapis persistant régulier, très propre, qui ne demande aucun entretien une fois installé. Installation lente : compter trois ans pour une couverture complète, et planter dense. Craint le plein soleil et le sol calcaire sec.",
 "bdm":"Déconseillé en bord de mer","dens":8,"esp":0.35},

{"lat":"Panicum virgatum","fr":"Panic érigé","type":"Graminée","h":1.5,"l":0.8,
 "expo":"Plein soleil","sol":"Tout type, drainé, pauvre toléré","hum":"Sec à frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert bleuté, ocre ou pourpre en automne","m1":7,"m2":10,"flo":"Juillet à octobre","cflo":"Beige rosé, nuage léger",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Massif contemporain, jardin naturaliste, prairie sèche, écran léger",
 "asso":"Echinacea, Rudbeckia, Perovskia, Sedum, Salvia nemorosa",
 "cons":"Inflorescence en nuage très fin, spectaculaire à contre-jour. Silhouette hivernale solide qui tient jusqu'en mars : rabattre seulement en fin d'hiver. Les cultivars bleutés comme Heavy Metal restent bien dressés, d'autres s'ouvrent en fin de saison. Extrêmement rustique et sobre en eau.",
 "bdm":"Second rideau","dens":1.5,"esp":0.8},

{"lat":"Pennisetum orientale","fr":"Herbe aux écouvillons d'Orient","type":"Graminée","h":0.6,"l":0.7,
 "expo":"Plein soleil","sol":"Drainé, sec, calcaire toléré, pauvre","hum":"Sec","rust":-15,
 "feu":"Caduc","cfeu":"Vert grisé","m1":6,"m2":10,"flo":"Juin à octobre","cflo":"Rose argenté",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Bordure souple, jardin sec, massif contemporain, potée, jardin de gravier",
 "asso":"Gaura, Perovskia, Sedum, Salvia, Verbena bonariensis",
 "cons":"Fleurit plus tôt et plus longtemps que le Pennisetum alopecuroides, avec des épis plus fins et plus rosés. Plus exigeant en drainage et moins rustique : l'humidité hivernale en sol lourd lui est fatale. Plantation de printemps impérative. Rabattre en mars, jamais à l'automne.",
 "bdm":"Front de mer","dens":3,"esp":0.6},

{"lat":"Persicaria bistorta","fr":"Renouée bistorte","type":"Vivace","h":0.8,"l":0.6,
 "expo":"Soleil à mi-ombre","sol":"Tout type, humifère, argileux toléré","hum":"Frais à humide","rust":-30,
 "feu":"Caduc","cfeu":"Vert franc","m1":5,"m2":8,"flo":"Mai à août","cflo":"Rose tendre",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Bord de bassin, massif frais, jardin naturaliste, prairie humide",
 "asso":"Molinia, Deschampsia, Filipendula, Sanguisorba, Astrantia",
 "cons":"Espèce indigène des prairies humides, épis roses dressés très graphiques. Excellente pour un sol lourd et frais où beaucoup de vivaces échouent. Rabattre après la première floraison pour une remontée. À ne pas confondre avec la renouée du Japon, qui est une plante invasive sans rapport.",
 "bdm":"Second rideau","dens":4,"esp":0.5},

{"lat":"Philadelphus coronarius","fr":"Seringat","type":"Arbuste","h":3.0,"l":2.5,
 "expo":"Soleil à mi-ombre","sol":"Tout type, calcaire toléré","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc ou doré","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Blanc pur",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie libre, jardin de curé, jardin blanc, près d'une terrasse pour le parfum",
 "asso":"Deutzia, Weigelia, Syringa, Spiraea, Viburnum",
 "cons":"Parfum de fleur d'oranger très puissant, l'argument de vente principal : le placer près d'un passage ou d'une terrasse. Tailler juste après la floraison, il fleurit sur le bois de l'année précédente. Recéper un tiers des vieilles branches à la base tous les 2 ou 3 ans, sinon il se dégarnit du bas.",
 "bdm":"Second rideau","dens":0.3,"esp":1.8},

{"lat":"Phillyrea angustifolia","fr":"Filaire à feuilles étroites","type":"Arbuste","h":2.5,"l":2.0,
 "expo":"Plein soleil","sol":"Drainé, sec, calcaire, pauvre, caillouteux","hum":"Sec","rust":-15,
 "feu":"Persistant","cfeu":"Vert foncé","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Blanc crème discret",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin méditerranéen, haie sèche, topiaire, bord de mer, remplacement du buis",
 "asso":"Cistus, Lavandula, Rosmarinus, Phlomis, Olea",
 "cons":"Excellente alternative méditerranéenne au buis et à l'if : se taille en boule ou en haie, supporte la sécheresse totale et résiste aux embruns. Croissance lente, prévoir un sujet déjà formé si le client est pressé. Aucun arrosage une fois installé. Très peu connu, à faire découvrir.",
 "bdm":"Front de mer","dens":0.5,"esp":1.2},

{"lat":"Phlomis fruticosa","fr":"Sauge de Jérusalem","type":"Arbuste","h":1.0,"l":1.2,
 "expo":"Plein soleil","sol":"Drainé, sec, calcaire, pauvre","hum":"Sec","rust":-12,
 "feu":"Persistant","cfeu":"Vert argenté duveteux","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Jaune",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin méditerranéen, massif sec, talus, jardin de gravier, bord de mer",
 "asso":"Cistus, Lavandula, Santolina, Euphorbia, Stipa",
 "cons":"Feuillage argenté et duveteux qui structure un massif toute l'année, fleurs en couronnes étagées très graphiques. Conserver les tiges défleuries, décoratives en hiver. Redoute l'humidité hivernale en sol lourd. Tailler légèrement après floraison, jamais sur le vieux bois.",
 "bdm":"Front de mer","dens":1,"esp":1.0},

{"lat":"Phlomis russeliana","fr":"Phlomis de Russell","type":"Vivace","h":0.9,"l":0.8,
 "expo":"Soleil à mi-ombre","sol":"Drainé, tout type, pauvre toléré","hum":"Sec à frais","rust":-25,
 "feu":"Persistant","cfeu":"Vert sauge duveteux","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Jaune pâle",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif naturaliste, couvre-sol structurant, jardin sec, bordure",
 "asso":"Graminées, Salvia nemorosa, Achillea, Sedum, Perovskia",
 "cons":"Plus rustique et plus couvrant que le Phlomis fruticosa, avec de grandes feuilles basales persistantes qui étouffent les adventices. Les tiges florales séchées tiennent tout l'hiver et sont un des grands effets du jardin naturaliste : ne pas les couper avant mars. S'étale doucement par rhizomes.",
 "bdm":"Second rideau","dens":2,"esp":0.7},

{"lat":"Photinia fraseri","fr":"Photinia","type":"Arbuste","h":3.0,"l":2.5,
 "expo":"Soleil à mi-ombre","sol":"Drainé, humifère, acide à neutre","hum":"Frais","rust":-15,
 "feu":"Persistant","cfeu":"Rouge vif au débourrement, puis vert foncé","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Blanc crème",
 "plant":"Automne à printemps","popt":"Octobre ou mars","ent":"Moyen",
 "style":"Haie persistante colorée, écran, sujet isolé, haie mixte",
 "asso":"Elaeagnus, Viburnum tinus, Prunus lusitanica, Pittosporum",
 "cons":"Les jeunes pousses rouges sont l'attrait principal : une taille au printemps et une en fin d'été relancent la coloration. Craint le calcaire actif, qui provoque une chlorose jaune du feuillage. Sensible à l'entomosporiose en situation confinée et humide : espacer les sujets et éviter les tailles par temps humide.",
 "bdm":"Second rideau","dens":0.5,"esp":1.0},

{"lat":"Pinus mugo","fr":"Pin nain de montagne","type":"Conifère","h":1.5,"l":2.0,
 "expo":"Plein soleil","sol":"Drainé, pauvre, caillouteux, calcaire toléré","hum":"Sec","rust":-30,
 "feu":"Persistant","cfeu":"Vert foncé","m1":0,"m2":0,"flo":"Non ornementale","cflo":"—",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Rocaille, jardin japonais, jardin de gravier, potée, massif contemporain",
 "asso":"Festuca glauca, Sedum, Juniperus, bruyères, graminées basses",
 "cons":"Conifère nain d'une rusticité à toute épreuve, qui reste compact sans intervention. Croissance très lente, à prendre en compte dans le prix comme dans l'effet attendu. On peut réduire les chandelles de printemps de moitié à la main pour densifier la silhouette. Aucune exigence de sol.",
 "bdm":"Front de mer","dens":0.4,"esp":1.5},

{"lat":"Pittosporum tenuifolium","fr":"Pittospore de Nouvelle-Zélande","type":"Arbuste","h":3.0,"l":2.0,
 "expo":"Soleil à mi-ombre","sol":"Drainé, humifère, frais","hum":"Frais","rust":-10,
 "feu":"Persistant","cfeu":"Vert clair ondulé, pourpre ou panaché selon cultivar","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Pourpre foncé discret",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Haie persistante légère, jardin contemporain, bord de mer, potée, topiaire",
 "asso":"Phormium, Griselinia, Elaeagnus, graminées, Agapanthus",
 "cons":"Feuillage fin et ondulé sur rameaux noirs, beaucoup plus léger qu'un laurier : il éclaire une haie au lieu de l'alourdir. Excellente tenue au bord de mer. Rusticité limitée, c'est sa vraie contrainte : un hiver à -12 °C peut le tuer, à réserver aux secteurs abrités du littoral. Fleurs discrètes mais très parfumées le soir.",
 "bdm":"Front de mer","dens":0.6,"esp":0.8},

{"lat":"Prunus armeniaca","fr":"Abricotier","type":"Fruitier","h":4.0,"l":4.0,
 "expo":"Plein soleil","sol":"Drainé, calcaire toléré, profond","hum":"Sec à frais","rust":-20,
 "feu":"Caduc","cfeu":"Vert franc","m1":2,"m2":3,"flo":"Février à mars","cflo":"Blanc rosé",
 "plant":"Automne","popt":"Novembre à février","ent":"Soutenu",
 "style":"Verger, palissage sur mur chaud, jardin nourricier",
 "asso":"Prairie fleurie, aromatiques au pied",
 "cons":"Floraison la plus précoce des fruitiers, souvent dès février : en Loire-Atlantique une gelée de mars détruit la récolte une année sur deux. À réserver aux situations très abritées, idéalement palissé contre un mur au sud. Craint l'excès d'humidité au collet. Taille en vert uniquement, jamais en hiver, pour éviter la gomme.",
 "bdm":"Déconseillé en bord de mer","dens":0.06,"esp":4.0},

{"lat":"Prunus cerasifera","fr":"Prunier myrobolan","type":"Arbre","h":6.0,"l":4.0,
 "expo":"Plein soleil","sol":"Tout type, calcaire toléré","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Pourpre foncé (cultivars Pissardii, Nigra)","m1":3,"m2":4,"flo":"Mars à avril","cflo":"Rose pâle",
 "plant":"Automne","popt":"Novembre à février","ent":"Faible",
 "style":"Sujet isolé, alignement urbain, haie libre, contraste de feuillage",
 "asso":"Graminées, vivaces claires, arbustes à feuillage vert ou doré",
 "cons":"Cultivé pour son feuillage pourpre, tenu toute la saison, qui fait contraste dans un massif vert. Floraison rose très précoce sur bois nu. Sans exigence particulière, il pousse partout. Attention à l'usage : le pourpre est une couleur forte, un seul sujet suffit généralement dans un jardin de particulier.",
 "bdm":"Second rideau","dens":0.06,"esp":4.0},

{"lat":"Prunus lusitanica","fr":"Laurier du Portugal","type":"Arbuste","h":4.0,"l":3.0,
 "expo":"Soleil à mi-ombre","sol":"Drainé, calcaire toléré, tout type","hum":"Frais","rust":-15,
 "feu":"Persistant","cfeu":"Vert foncé brillant, pétiole rouge","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Blanc crème parfumé",
 "plant":"Automne à printemps","popt":"Septembre à novembre ou mars","ent":"Faible",
 "style":"Haie persistante, écran, topiaire, sujet isolé, haie mixte",
 "asso":"Elaeagnus, Photinia, Viburnum tinus, Pittosporum",
 "cons":"Bien préférable au laurier-cerise : feuillage plus fin, croissance plus mesurée, port plus élégant, et il n'a pas son caractère envahissant. Supporte le calcaire, contrairement au Photinia. Une seule taille annuelle suffit. Floraison en grappes blanches parfumées, suivie de baies noires appréciées des oiseaux. À proposer systématiquement en alternative.",
 "bdm":"Front de mer","dens":0.5,"esp":1.0},

{"lat":"Prunus serrulata","fr":"Cerisier du Japon","type":"Arbre","h":6.0,"l":5.0,
 "expo":"Plein soleil","sol":"Drainé, humifère, profond, neutre","hum":"Frais","rust":-20,
 "feu":"Caduc","cfeu":"Vert, orangé en automne","m1":4,"m2":4,"flo":"Avril","cflo":"Rose, blanc",
 "plant":"Automne","popt":"Novembre à février","ent":"Faible",
 "style":"Sujet isolé, jardin japonais, alignement, petit jardin",
 "asso":"Azalea, Acer palmatum, Ophiopogon, bulbes de printemps, graminées",
 "cons":"Floraison spectaculaire de deux à trois semaines, c'est un arbre qu'on plante pour un moment précis de l'année. Le cultivar Kanzan est le plus courant, en port évasé ; Amanogawa reste colonnaire et convient aux très petits jardins. Racines superficielles : ne pas travailler le sol au pied. Éviter toute taille, chaque plaie est une porte d'entrée aux maladies.",
 "bdm":"Second rideau","dens":0.05,"esp":5.0},

{"lat":"Rubus idaeus","fr":"Framboisier","type":"Fruitier","h":1.8,"l":0.6,
 "expo":"Soleil à mi-ombre","sol":"Humifère, drainé, acide à neutre, frais","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Blanc discret",
 "plant":"Automne","popt":"Novembre à mars","ent":"Moyen",
 "style":"Jardin nourricier, potager, haie fruitière, palissage",
 "asso":"Ribes, Vaccinium, plantes mellifères",
 "cons":"Distinguer les remontants, qui fructifient en été puis en automne et se rabattent entièrement en hiver, des non-remontants, qui fructifient une fois et dont on ne coupe que les cannes ayant produit. Se confondre entre les deux, c'est perdre la récolte. Drageonne beaucoup : prévoir une barrière ou un désherbage régulier. Palissage sur fils indispensable.",
 "bdm":"Second rideau","dens":2.5,"esp":0.5},

{"lat":"Salvia uliginosa","fr":"Sauge des marais","type":"Vivace","h":1.8,"l":0.8,
 "expo":"Plein soleil","sol":"Humifère, frais, profond","hum":"Frais à humide","rust":-12,
 "feu":"Caduc","cfeu":"Vert clair","m1":7,"m2":10,"flo":"Juillet à octobre","cflo":"Bleu ciel",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Massif de fin d'été, bord de bassin, jardin naturaliste, arrière-plan léger",
 "asso":"Graminées, Verbena bonariensis, Rudbeckia, Eupatorium, Persicaria",
 "cons":"Bleu ciel très pur, rare en fin de saison, sur des tiges hautes et transparentes qu'on place en arrière-plan sans masquer. Contrairement aux autres sauges, elle veut de la fraîcheur au sol : elle s'effondre en sécheresse. Traçante, elle colonise doucement. Rabattre au printemps, pailler en hiver dans les secteurs froids.",
 "bdm":"Second rideau","dens":3,"esp":0.6},

{"lat":"Sambucus nigra","fr":"Sureau noir","type":"Arbuste","h":5.0,"l":4.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, humifère, riche, argileux toléré","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert, ou pourpre et doré selon cultivar","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Blanc crème",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie champêtre, jardin de biodiversité, jardin nourricier, fond de massif",
 "asso":"Corylus, Viburnum opulus, Cornus sanguinea, Crataegus",
 "cons":"Espèce indigène de première importance pour la biodiversité : fleurs très mellifères, baies consommées par des dizaines d'espèces d'oiseaux. Fleurs et baies utilisables en cuisine, un argument qui plaît. Croissance très rapide en sol riche. Les cultivars pourpres à feuillage découpé, comme Black Lace, en font une plante d'ornement à part entière. Recéper tous les 3 ans.",
 "bdm":"Second rideau","dens":0.15,"esp":2.5},

{"lat":"Syringa vulgaris","fr":"Lilas commun","type":"Arbuste","h":4.0,"l":3.0,
 "expo":"Plein soleil","sol":"Drainé, calcaire toléré, profond","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert franc","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Mauve, violet, blanc, rose",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Jardin de curé, haie libre, près d'une terrasse pour le parfum, sujet isolé",
 "asso":"Philadelphus, Deutzia, Weigelia, rosiers, vivaces de printemps",
 "cons":"Parfum inégalé, mais floraison courte, deux à trois semaines : à associer à des arbustes qui prennent le relais. Supprimer les fleurs fanées juste après la floraison stimule celle de l'année suivante. Ne jamais tailler en hiver, on supprimerait les boutons. Drageonne selon le porte-greffe. Exige le plein soleil pour bien fleurir.",
 "bdm":"Second rideau","dens":0.2,"esp":2.0},

{"lat":"Verbena bonariensis","fr":"Verveine de Buenos Aires","type":"Vivace","h":1.5,"l":0.4,
 "expo":"Plein soleil","sol":"Drainé, tout type, pauvre toléré","hum":"Sec à frais","rust":-12,
 "feu":"Caduc","cfeu":"Vert foncé","m1":6,"m2":11,"flo":"Juin à novembre","cflo":"Violet mauve",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Massif naturaliste, jardin sec, premier plan transparent, prairie fleurie",
 "asso":"Graminées, Gaura, Perovskia, Echinacea, Salvia, Rudbeckia",
 "cons":"Tiges très fines et hautes qui portent les fleurs en apesanteur : à planter en premier plan malgré sa hauteur, on voit à travers. Floraison de six mois, extrêmement attractive pour les papillons. Se ressème spontanément et se déplace dans le massif, ce qui fait son charme naturaliste. Durée de vie courte, mais le semis assure le renouvellement. Rabattre au printemps seulement.",
 "bdm":"Front de mer","dens":5,"esp":0.4},

{"lat":"Yucca filamentosa","fr":"Yucca filamenteux","type":"Vivace / Arbuste","h":1.5,"l":1.0,
 "expo":"Plein soleil","sol":"Drainé, sec, sableux, pauvre","hum":"Sec","rust":-20,
 "feu":"Persistant","cfeu":"Vert bleuté ou panaché de jaune","m1":6,"m2":8,"flo":"Juin à août","cflo":"Blanc crème",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin sec, massif graphique, jardin contemporain, bord de mer, jardin de gravier",
 "asso":"Graminées, Sedum, Delosperma, Phormium, Euphorbia",
 "cons":"Silhouette en rosette très architecturale, présente toute l'année, puis une hampe florale d'un mètre cinquante en été. Rusticité bien meilleure que sa silhouette exotique ne le laisse croire. Drainage impératif, il pourrit en sol lourd et humide. Feuilles à extrémité pointue, à écarter des passages et des aires de jeux.",
 "bdm":"Front de mer","dens":1,"esp":1.0},

{"lat":"Lonicera pileata","fr":"Chèvrefeuille arbustif","type":"Couvre-sol / Arbuste","h":0.6,"l":1.2,
 "expo":"Soleil à ombre","sol":"Tout type, drainé, calcaire toléré","hum":"Sec à frais","rust":-20,
 "feu":"Persistant","cfeu":"Vert brillant","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Blanc crème discret",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Couvre-sol de masse, talus, bordure basse, aménagement collectif, pied de haie",
 "asso":"Cotoneaster, Hedera, Vinca, Euonymus, graminées basses",
 "cons":"Couvre-sol persistant au port étalé et régulier, très utilisé en collectif parce qu'il ne demande rien : ni taille, ni arrosage, et il tolère l'ombre comme le plein soleil. Baies violettes translucides en automne. Compter 3 plants au m². Une taille de rabattage tous les 3 ou 4 ans suffit à le régénérer.",
 "bdm":"Front de mer","dens":3,"esp":0.6},
]
