# -*- coding: utf-8 -*-
"""Lot 5 - 50 especes supplementaires du catalogue AD.V."""

ALIAS5 = {
    "Agapanthe graphite":    "Agapanthus africanus",
    "Teucrium":              "Teucrium fruticans",
    "Thymus albiflorus":     "Thymus serpyllum",
    "Thymus citriodorus":    "Thymus vulgaris",
    "Acer":                  "Acer campestris",
    "Verbena":               "Verbena bonariensis",
    "Magnolia leonard":      "Magnolia stellata",
    "Weigelia brigela":      "Weigelia",
    "Weigelia kosteriana":   "Weigelia",
    "Yucca":                 "Yucca filamentosa",
    "Loropetalum chinensis": "Loropetalum",
    "Mahonia media":         "Mahonia",
    "Matteuccia orientalis": "Matteuccia struthiopteris",
    "Lavandula willowale":   "Lavandula intermedia",
    "Leucanthemeum max":     "Leucanthemum maximum",
    "Leycesteria":           "Leycesteria formosa",
    "Helleborus orientalis": "Helleborus niger",
    "Helleborus foetidus":   "Helleborus niger",
    "Lippia nodiflora":      "Lippia citriodora",
    "Liriope spicata":       "Liriope muscari",
    "Lonicera acuminata":    "Lonicera japonica",
    "Cyrtomium fortunei":    "Cyrtomium falcatum",
    "Echinacea purpurea":    "Echinacea",
    "Elaeagnus pungens":     "Elaeagnus ebbingei",
    "Hedera sagittifolia":   "Hedera",
    "Heuchera americana":    "Heuchera",
    "Heuchera micrantha":    "Heuchera",
    "Iris hollandica":       "Iris germanica",
    "Iris reticulata":       "Iris germanica",
    "Eupatorium maculatum":  "Eupatorium cannabinum",
    "Festuca mairei":        "Festuca gautieri",
    "Kniphofia citrina":     "Kniphofia uvaria",
    "Anemone sylvestris":    "Anemone hupehensis",
    "Anemone tomentosa":     "Anemone hupehensis",
    "Anemone x":             "Anemone hupehensis",
    "Sesleria automnalis":   "Sesleria caerulea",
    "Sedum spurium":         "Sedum acre",
    "Scabiosa japonica":     "Scabiosa columbaria",
    "Scabiosa ochroleuca":   "Scabiosa columbaria",
    "Vitis":                 "Vitis vinifera",
    "Crocosmia":             "Crocosmia crocosmiiflora",
    "Gaillardia":            "Gaillardia grandiflora",
    "Aquilegia":             "Aquilegia vulgaris",
    "Luzula sylvatica":      "Luzula nivea",
    "Melica ciliata":        "Koeleria glauca",
    "Cotoneaster horizontalis": "Cotoneaster",
}

FICHES5 = [
{"lat":"Acanthus mollis","fr":"Acanthe","type":"Vivace","h":1.2,"l":1.0,
 "expo":"Soleil à mi-ombre","sol":"Profond, drainé, calcaire toléré","hum":"Sec à frais","rust":-15,
 "feu":"Semi-persistant","cfeu":"Vert foncé brillant, très découpé","m1":6,"m2":8,"flo":"Juin à août","cflo":"Blanc et pourpre",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Massif structuré, jardin méditerranéen, pied de mur, sujet architectural",
 "asso":"Euphorbia, Phlomis, graminées, Hedera, Iris",
 "cons":"Feuillage monumental qui a inspiré le chapiteau corinthien, et hampes florales dressées d'un mètre cinquante. Racines charnues très profondes : une fois installée, elle est quasi impossible à déplacer et le moindre fragment repart. Bien choisir son emplacement d'emblée. Supporte la sécheresse estivale, le feuillage disparaît alors et revient à l'automne.",
 "bdm":"Second rideau","dens":1,"esp":1.0},

{"lat":"Acer campestris","fr":"Érable champêtre","type":"Arbre","h":12.0,"l":8.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, calcaire toléré, argileux toléré","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert, jaune d'or en automne","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Vert jaune discret",
 "plant":"Automne","popt":"Novembre à février","ent":"Faible",
 "style":"Haie champêtre, haie taillée, alignement, arbre d'ombrage de taille modeste",
 "asso":"Carpinus, Cornus sanguinea, Crataegus, Corylus, Viburnum opulus",
 "cons":"Espèce indigène du bocage, la plus adaptable des érables : elle accepte le calcaire, l'argile, la sécheresse et le vent. Se conduit aussi bien en arbre libre qu'en haie taillée, où elle remplace avantageusement le charme en sol lourd et sec. Taille modeste qui convient aux jardins de particuliers. Aucune maladie notable.",
 "bdm":"Second rideau","dens":0.03,"esp":0.4},

{"lat":"Acer negundo","fr":"Érable negundo","type":"Arbre","h":12.0,"l":8.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, frais, argileux toléré","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert, panaché de blanc ou doré selon cultivar","m1":3,"m2":4,"flo":"Mars à avril","cflo":"Vert jaune discret",
 "plant":"Automne","popt":"Novembre à février","ent":"Faible",
 "style":"Sujet isolé, contraste de feuillage clair, jardin urbain, terrain frais",
 "asso":"Arbustes à feuillage sombre, graminées, vivaces d'ombre au pied",
 "cons":"Les cultivars panachés comme Flamingo apportent une note très claire, presque blanche, qui éclaire un fond de jardin. Croissance rapide mais bois cassant et durée de vie modeste. Se ressème abondamment, au point d'être classé envahissant dans certaines régions : préférer les cultivars horticoles, moins prolifiques.",
 "bdm":"Second rideau","dens":0.03,"esp":6.0},

{"lat":"Achillea filipendulina","fr":"Achillée jaune","type":"Vivace","h":1.2,"l":0.6,
 "expo":"Plein soleil","sol":"Drainé, pauvre toléré, calcaire toléré","hum":"Sec","rust":-30,
 "feu":"Caduc","cfeu":"Vert grisé, découpé, aromatique","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Jaune d'or, en larges plateaux",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif estival, jardin sec, prairie fleurie, fond de bordure, fleurs séchées",
 "asso":"Echinacea, graminées, Perovskia, Salvia nemorosa, Eryngium",
 "cons":"Larges plateaux jaunes portés très haut, qui restent décoratifs longtemps après la floraison et se conservent parfaitement en bouquet sec. Tiges solides qui ne demandent pas de tuteurage, contrairement à beaucoup de vivaces de cette hauteur. Sobre en eau. Ne rien apporter, la richesse la fait verser.",
 "bdm":"Front de mer","dens":3,"esp":0.6},

{"lat":"Alchemilla mollis","fr":"Alchémille","type":"Couvre-sol / Vivace","h":0.5,"l":0.6,
 "expo":"Soleil à mi-ombre","sol":"Tout type, humifère, frais","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert tendre, feuilles plissées","m1":5,"m2":8,"flo":"Mai à août","cflo":"Vert chartreuse, en nuage",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Bordure d'allée, pied de rosier, jardin romantique, massif frais, sous-bois clair",
 "asso":"Rosiers, Geranium vivace, Astrantia, Campanula, Hosta, Nepeta",
 "cons":"Les feuilles plissées retiennent les gouttes de rosée en perles, un détail que les clients adorent. Floraison en nuage vert acide qui adoucit toutes les couleurs voisines, d'où son emploi systématique en bordure d'allée et au pied des rosiers. Rabattre à ras après la floraison : elle refait un feuillage neuf en trois semaines. Se ressème beaucoup.",
 "bdm":"Second rideau","dens":4,"esp":0.5},

{"lat":"Allium schoenoprasum","fr":"Ciboulette","type":"Vivace / Aromatique","h":0.3,"l":0.25,
 "expo":"Plein soleil","sol":"Drainé, humifère, frais","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert bleuté, en touffe fine","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Rose mauve, en pompons",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Potager, bordure comestible, jardin d'aromatiques, pied de rosier, potée",
 "asso":"Rosiers, fraisiers, Thymus, Origanum, Salvia officinalis",
 "cons":"Double usage, culinaire et ornemental : les pompons roses sont très décoratifs et mellifères. Traditionnellement plantée au pied des rosiers, où elle est réputée limiter les pucerons. Couper régulièrement pour relancer un feuillage tendre. Diviser tous les trois ans, la touffe s'épuise. Se ressème si on laisse les fleurs.",
 "bdm":"Second rideau","dens":9,"esp":0.25},

{"lat":"Anaphalis triplinervis","fr":"Immortelle d'Amérique","type":"Vivace","h":0.5,"l":0.5,
 "expo":"Plein soleil","sol":"Drainé, tout type, pauvre toléré","hum":"Sec à frais","rust":-30,
 "feu":"Caduc","cfeu":"Argenté, feutré","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Blanc nacré",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif argenté, bordure, jardin sec, fleurs séchées, jardin naturaliste",
 "asso":"Perovskia, Stachys, Artemisia, Sedum, graminées, Aster",
 "cons":"Feuillage argenté toute la saison puis fleurs blanches nacrées qui se conservent indéfiniment en bouquet sec, d'où son nom d'immortelle. Contrairement à la plupart des plantes argentées, elle tolère un sol qui reste un peu frais, ce qui élargit son emploi. Rabattre en fin d'hiver seulement.",
 "bdm":"Front de mer","dens":4,"esp":0.5},

{"lat":"Anthemis tinctoria","fr":"Camomille des teinturiers","type":"Vivace","h":0.7,"l":0.6,
 "expo":"Plein soleil","sol":"Drainé, sec, pauvre, calcaire toléré","hum":"Sec","rust":-25,
 "feu":"Semi-persistant","cfeu":"Vert grisé, finement découpé","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Jaune d'or, jaune pâle",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Prairie fleurie, massif naturaliste, jardin sec, bordure champêtre",
 "asso":"Salvia nemorosa, graminées, Achillea, Scabiosa, Centranthus",
 "cons":"Floraison en marguerites jaunes très abondante et très longue si on rabat après la première vague. Utilisée autrefois comme plante tinctoriale. Durée de vie courte, trois ans environ, mais elle se ressème facilement. Redoute l'humidité hivernale en sol lourd, comme la plupart des vivaces de terrain sec.",
 "bdm":"Front de mer","dens":4,"esp":0.5},

{"lat":"Aquilegia vulgaris","fr":"Ancolie","type":"Vivace","h":0.7,"l":0.4,
 "expo":"Soleil à mi-ombre","sol":"Humifère, drainé, frais","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert bleuté, découpé","m1":4,"m2":6,"flo":"Avril à juin","cflo":"Bleu violacé, rose, blanc, pourpre",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Jardin de curé, sous-bois clair, massif romantique, jardin champêtre",
 "asso":"Alchemilla, Geranium vivace, Hosta, fougères, Digitalis",
 "cons":"Fleurs éperonnées d'une grande finesse, à une saison creuse entre les bulbes de printemps et les vivaces d'été. Se ressème très librement et hybride spontanément : les semis donnent des couleurs différentes du pied d'origine, ce qui fait son charme mais surprend les clients. Durée de vie courte, compensée par le semis.",
 "bdm":"Second rideau","dens":6,"esp":0.4},

{"lat":"Cotoneaster horizontalis","fr":"Cotonéaster horizontal","type":"Couvre-sol / Arbuste","h":0.6,"l":1.5,
 "expo":"Soleil à mi-ombre","sol":"Tout type, drainé, calcaire toléré, pauvre","hum":"Sec","rust":-25,
 "feu":"Caduc","cfeu":"Vert foncé, rouge écarlate en automne","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Rose pâle",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Talus, pied de mur, palissage à plat, rocaille, dessus de muret",
 "asso":"Juniperus rampant, Hedera, graminées basses, Sedum",
 "cons":"Rameaux disposés en arêtes de poisson très régulières, qui épousent un mur ou un talus à plat : un effet graphique qu'aucun autre couvre-sol ne donne. Baies rouges tout l'hiver, très visitées par les oiseaux. Sensible au feu bactérien, ne pas tailler par temps humide. Fleurs extrêmement mellifères.",
 "bdm":"Front de mer","dens":1,"esp":1.0},

{"lat":"Crocosmia crocosmiiflora","fr":"Montbrétia","type":"Vivace","h":0.8,"l":0.3,
 "expo":"Plein soleil","sol":"Drainé, humifère, frais","hum":"Frais","rust":-15,
 "feu":"Caduc","cfeu":"Vert clair, en glaives","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Orange, rouge, jaune",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif estival, bordure, jardin de bord de mer, jardin exotique",
 "asso":"Graminées, Hemerocallis, Rudbeckia, Agapanthus, Kniphofia",
 "cons":"Couleurs chaudes en épis arqués, très présentes dans les jardins du littoral atlantique où elle se naturalise. Se multiplie rapidement par cormus et forme des colonies denses : diviser tous les trois ou quatre ans, sinon elle fleurit moins. Le cultivar Lucifer, rouge vif, est le plus vigoureux et le plus rustique.",
 "bdm":"Front de mer","dens":9,"esp":0.25},

{"lat":"Cydonia oblanga","fr":"Cognassier","type":"Fruitier","h":4.0,"l":4.0,
 "expo":"Plein soleil","sol":"Profond, frais, drainé","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert grisé duveteux, jaune en automne","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Rose pâle, grandes fleurs",
 "plant":"Automne","popt":"Novembre à février","ent":"Faible",
 "style":"Verger, jardin nourricier, sujet isolé, jardin de curé",
 "asso":"Prairie fleurie, vivaces mellifères au pied, haie champêtre",
 "cons":"Un fruitier ornemental à part entière : grandes fleurs roses au printemps, gros coings jaunes et parfumés à l'automne, port tortueux en hiver. Autofertile, un seul sujet suffit. Fruits immangeables crus mais parfaits en gelée et en pâte. Craint le calcaire actif, qui provoque une chlorose. Taille très légère.",
 "bdm":"Second rideau","dens":0.06,"esp":4.0},

{"lat":"Cyrtomium falcatum","fr":"Fougère houx","type":"Fougère","h":0.6,"l":0.6,
 "expo":"Mi-ombre à ombre","sol":"Humifère, drainé, calcaire toléré","hum":"Frais","rust":-15,
 "feu":"Persistant","cfeu":"Vert foncé brillant, vernissé","m1":0,"m2":0,"flo":"Non fleurie","cflo":"—",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif d'ombre, potée, patio ombragé, bord de mer, jardin japonais",
 "asso":"Hosta, Carex, Ophiopogon, Heuchera, Aspidistra",
 "cons":"Frondes épaisses et brillantes qui ressemblent à des feuilles de houx, très différentes des fougères classiques. Persistante et coriace, elle supporte bien mieux la sécheresse de l'air que les autres fougères, ce qui la rend utilisable en potée et près d'un mur. Bonne tolérance aux embruns. Éviter les situations gelantes prolongées.",
 "bdm":"Front de mer","dens":3,"esp":0.6},

{"lat":"Diospyros","fr":"Plaqueminier","type":"Fruitier / Arbre","h":6.0,"l":5.0,
 "expo":"Plein soleil","sol":"Profond, drainé, frais","hum":"Frais","rust":-18,
 "feu":"Caduc","cfeu":"Vert foncé brillant, orange écarlate en automne","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Jaune crème discret",
 "plant":"Printemps","popt":"Mars à avril","ent":"Faible",
 "style":"Verger, sujet isolé, jardin nourricier, arbre d'automne",
 "asso":"Prairie, graminées, vivaces d'automne au pied",
 "cons":"Sans doute le plus bel arbre fruitier d'automne : le feuillage vire à l'orange écarlate puis tombe, laissant les kakis suspendus comme des lanternes sur les branches nues jusqu'en décembre. Autofertile pour les variétés courantes. Fructification tardive, à partir de la quatrième ou cinquième année. Aucune maladie notable.",
 "bdm":"Second rideau","dens":0.05,"esp":5.0},

{"lat":"Doronicum orientale","fr":"Doronic","type":"Vivace","h":0.5,"l":0.4,
 "expo":"Soleil à mi-ombre","sol":"Humifère, frais, drainé","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert clair","m1":3,"m2":5,"flo":"Mars à mai","cflo":"Jaune d'or",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Massif de printemps, sous-bois clair, bordure, jardin de curé",
 "asso":"Bulbes de printemps, Pulmonaria, Brunnera, Hosta, Alchemilla",
 "cons":"L'une des toutes premières vivaces à fleurir, dès mars, en grandes marguerites jaunes qui accompagnent parfaitement les bulbes de printemps. Entre en repos et disparaît complètement en été : prévoir une voisine qui prend le relais, sinon le massif est vide. Apprécie un sol frais et une ombre légère l'été.",
 "bdm":"Second rideau","dens":6,"esp":0.4},

{"lat":"Echinops ritro","fr":"Boule azurée","type":"Vivace","h":1.2,"l":0.6,
 "expo":"Plein soleil","sol":"Drainé, sec, pauvre, calcaire toléré","hum":"Sec","rust":-30,
 "feu":"Caduc","cfeu":"Vert grisé, revers argenté, épineux","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Bleu métallique, en sphères",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif naturaliste, jardin sec, fond de bordure, fleurs séchées",
 "asso":"Eryngium, graminées, Achillea, Perovskia, Sedum spectabile",
 "cons":"Sphères bleu métallique parfaitement rondes, uniques dans un massif, et l'une des plantes les plus visitées par les bourdons et les papillons en plein été. Excellente en bouquet sec si on la coupe avant l'ouverture complète. Racine pivotante profonde : très résistante à la sécheresse mais difficile à déplacer. Feuillage épineux.",
 "bdm":"Front de mer","dens":2,"esp":0.7},

{"lat":"Epimedium versicolor","fr":"Fleur des elfes","type":"Couvre-sol","h":0.35,"l":0.4,
 "expo":"Mi-ombre à ombre","sol":"Humifère, drainé, tout type","hum":"Sec à frais","rust":-25,
 "feu":"Semi-persistant","cfeu":"Vert bronzé au débourrement, rougissant en automne","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Jaune pâle, rose, blanc",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Sous-bois, ombre sèche, pied d'arbre, bordure ombragée, jardin japonais",
 "asso":"Hosta, fougères, Geranium macrorrhizum, Luzula, Carex",
 "cons":"L'un des tout meilleurs couvre-sols pour l'ombre sèche sous les arbres, avec le géranium à grosses racines : une fois installé, il tient sans arrosage. Jeunes feuilles teintées de bronze au printemps. Rabattre le feuillage en février, juste avant la floraison, pour bien voir les fleurs. Croissance lente, planter dense.",
 "bdm":"Second rideau","dens":6,"esp":0.4},

{"lat":"Eragrostis spectabilis","fr":"Éragrostide","type":"Graminée","h":0.6,"l":0.6,
 "expo":"Plein soleil","sol":"Drainé, sableux, pauvre","hum":"Sec","rust":-20,
 "feu":"Caduc","cfeu":"Vert bleuté, rouge cuivré en automne","m1":8,"m2":10,"flo":"Août à octobre","cflo":"Rose pourpré, en nuage",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Massif contemporain, jardin sec, premier plan à contre-jour, jardin de gravier",
 "asso":"Sedum spectabile, Perovskia, Echinacea, Gaura, Verbena bonariensis",
 "cons":"Nuage rose pourpré très fin en fin d'été, spectaculaire à contre-jour du soleil couchant : à placer en fonction de la lumière du soir. Feuillage cuivré à l'automne. Exige un sol pauvre et drainant, elle s'affaisse en terre riche. Plantation de printemps impérative, rabattre en mars.",
 "bdm":"Front de mer","dens":3,"esp":0.6},

{"lat":"Erigeron karvinskianus","fr":"Vergerette de Karvinski","type":"Couvre-sol","h":0.3,"l":0.6,
 "expo":"Plein soleil","sol":"Drainé, pauvre, caillouteux, fissures","hum":"Sec","rust":-12,
 "feu":"Semi-persistant","cfeu":"Vert clair","m1":4,"m2":11,"flo":"Avril à novembre","cflo":"Blanc virant rose puis pourpre",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Muret, escalier, joints de dallage, pied de mur, jardin méditerranéen, potée",
 "asso":"Centranthus, Campanula, Sedum, Thymus, Armeria",
 "cons":"Floraison ininterrompue d'avril aux gelées, avec des fleurs qui passent du blanc au rose puis au pourpre, toutes présentes en même temps. Colonise seule les fissures de murs et les joints d'escalier, où elle s'installe par semis : c'est exactement l'usage à en faire. Aucun entretien. Se ressème généreusement.",
 "bdm":"Front de mer","dens":4,"esp":0.5},

{"lat":"Eryngium planum","fr":"Panicaut bleu","type":"Vivace","h":0.8,"l":0.4,
 "expo":"Plein soleil","sol":"Drainé, sec, pauvre, sableux, calcaire toléré","hum":"Sec","rust":-30,
 "feu":"Caduc","cfeu":"Vert bleuté, épineux","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Bleu acier métallique",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin sec, massif naturaliste, bord de mer, jardin de gravier, fleurs séchées",
 "asso":"Echinops, graminées, Achillea, Perovskia, Sedum, Verbena bonariensis",
 "cons":"Bleu acier métallique qui colore la tige entière, pas seulement la fleur : un effet unique dans un massif. Se conserve parfaitement en bouquet sec. Racine pivotante très profonde, d'où sa résistance à la sécheresse totale, mais elle rend tout déplacement impossible. Ne rien apporter, il déteste la richesse.",
 "bdm":"Front de mer","dens":5,"esp":0.4},

{"lat":"Eupatorium cannabinum","fr":"Eupatoire chanvrine","type":"Vivace","h":1.6,"l":0.8,
 "expo":"Soleil à mi-ombre","sol":"Tout type, humifère, argileux toléré","hum":"Frais à humide","rust":-30,
 "feu":"Caduc","cfeu":"Vert foncé","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Rose mauve, en larges corymbes",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Bord de bassin, noue, zone humide, jardin naturaliste, fond de massif",
 "asso":"Lythrum, Molinia, Persicaria, Filipendula, Sanguisorba",
 "cons":"Espèce indigène des berges, l'une des plantes les plus attractives pour les papillons en fin d'été : un pied en fleurs peut en porter une dizaine simultanément. Grande et vigoureuse, à placer en fond de massif frais. Conserver les tiges sèches en hiver, elles abritent des insectes. Se ressème en milieu humide.",
 "bdm":"Second rideau","dens":1.5,"esp":0.8},

{"lat":"Euphorbia myrsinites","fr":"Euphorbe de Corse","type":"Couvre-sol","h":0.15,"l":0.4,
 "expo":"Plein soleil","sol":"Drainé, sec, très pauvre, caillouteux","hum":"Sec","rust":-15,
 "feu":"Persistant","cfeu":"Bleu glauque, en spirales charnues","m1":3,"m2":5,"flo":"Mars à mai","cflo":"Vert chartreuse",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Rocaille, muret, dessus de mur, jardin de gravier, jardin méditerranéen",
 "asso":"Sedum, Delosperma, Festuca glauca, Armeria, Thymus",
 "cons":"Tiges retombantes couvertes de feuilles bleues disposées en spirale, très graphique sur un dessus de muret. Floraison chartreuse très précoce. Latex irritant : gants obligatoires, à signaler s'il y a des enfants. Drainage absolument impératif, elle pourrit en terre ordinaire. Se ressème en rocaille.",
 "bdm":"Front de mer","dens":6,"esp":0.4},

{"lat":"Exochorda racemosa","fr":"Buisson de perles","type":"Arbuste","h":2.5,"l":2.5,
 "expo":"Soleil à mi-ombre","sol":"Drainé, humifère, acide à neutre","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert clair","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Blanc pur",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Massif de printemps, haie libre fleurie, sujet isolé, jardin blanc",
 "asso":"Deutzia, Spiraea nipponica, Philadelphus, Weigelia, bulbes de printemps",
 "cons":"Les boutons ronds et nacrés alignés sur les rameaux ressemblent à des perles avant de s'ouvrir en grandes fleurs blanches : c'est de là que vient son nom, et c'est le moment le plus joli. Redoute le calcaire actif. Tailler après la floraison uniquement. Croissance modérée, port arrondi naturel qui ne demande rien.",
 "bdm":"Second rideau","dens":0.2,"esp":2.0},

{"lat":"Fagus sylvatica","fr":"Hêtre commun","type":"Arbre","h":25.0,"l":15.0,
 "expo":"Soleil à mi-ombre","sol":"Drainé, profond, frais, acide à neutre","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert tendre puis foncé, ou pourpre, cuivré en automne","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Vert discret",
 "plant":"Automne","popt":"Novembre à février","ent":"Moyen",
 "style":"Haie taillée, grand jardin, sujet isolé, alignement, parc",
 "asso":"En haie monospécifique, ou haie mixte avec Carpinus, Ilex, Taxus",
 "cons":"En haie taillée, il conserve ses feuilles cuivrées tout l'hiver, ce qui en fait un brise-vue élégant à la belle et à la mauvaise saison. Mais il exige un sol drainé, profond et frais : en terre lourde ou calcaire, il végète et le charme lui est nettement préférable. Une taille par an en août. Compter 3 plants par mètre linéaire.",
 "bdm":"Déconseillé en bord de mer","dens":0.01,"esp":0.35},

{"lat":"Fargesia murielae","fr":"Bambou non traçant","type":"Graminée / Bambou","h":3.0,"l":1.5,
 "expo":"Mi-ombre","sol":"Humifère, drainé, frais, profond","hum":"Frais","rust":-25,
 "feu":"Persistant","cfeu":"Vert clair, chaumes jaunes","m1":0,"m2":0,"flo":"Exceptionnelle","cflo":"—",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Écran persistant, brise-vue, jardin japonais, potée, massif d'ombre",
 "asso":"Acer palmatum, Hakonechloa, Ophiopogon, fougères, Hosta",
 "cons":"Le point capital : ce bambou est cespiteux, il ne trace pas, contrairement aux Phyllostachys qui envahissent tout et exigent une barrière anti-rhizome. C'est la réponse au client échaudé par un bambou envahissant. Port souple et retombant. Exige de la fraîcheur au sol, il souffre en plein soleil sec. Paillage indispensable.",
 "bdm":"Second rideau","dens":0.5,"esp":1.2},

{"lat":"Festuca gautieri","fr":"Fétuque de Gautier","type":"Graminée","h":0.25,"l":0.3,
 "expo":"Plein soleil","sol":"Drainé, sec, pauvre, caillouteux","hum":"Sec","rust":-25,
 "feu":"Persistant","cfeu":"Vert vif, en coussin dense","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Beige discret",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Rocaille, bordure, jardin de gravier, massif contemporain, entre-dalles",
 "asso":"Festuca glauca, Sedum, Armeria, Thymus, Delosperma",
 "cons":"Coussin vert vif très dense et parfaitement régulier, qui garde sa forme sans aucune intervention, contrairement à la fétuque bleue qui se dégarnit. Feuillage piquant au toucher, d'où son surnom de fétuque hérisson. Persistante et propre toute l'année. Peigner au printemps. Drainage impératif.",
 "bdm":"Front de mer","dens":8,"esp":0.3},

{"lat":"Filipendula ulmaria","fr":"Reine des prés","type":"Vivace","h":1.2,"l":0.6,
 "expo":"Soleil à mi-ombre","sol":"Humifère, argileux toléré, riche","hum":"Humide","rust":-30,
 "feu":"Caduc","cfeu":"Vert foncé, revers argenté","m1":6,"m2":8,"flo":"Juin à août","cflo":"Blanc crème, en plumeaux parfumés",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Bord de bassin, noue, prairie humide, jardin naturaliste, zone détrempée",
 "asso":"Lythrum, Eupatorium, Molinia, Persicaria, Carex pendula",
 "cons":"Espèce indigène des fossés et prairies humides, à la floraison en plumeaux crème au parfum de miel et d'amande. Prospère là où le sol reste détrempé, y compris en hiver, ce qui règle les zones où presque rien ne tient. Plante médicinale historique, à l'origine de l'aspirine. Se ressème en milieu humide.",
 "bdm":"Second rideau","dens":3,"esp":0.6},

{"lat":"Fuchsia magellanica","fr":"Fuchsia de Magellan","type":"Arbuste","h":1.5,"l":1.2,
 "expo":"Mi-ombre","sol":"Humifère, drainé, frais","hum":"Frais","rust":-15,
 "feu":"Caduc","cfeu":"Vert foncé ou panaché","m1":6,"m2":11,"flo":"Juin à novembre","cflo":"Rouge et violet, pendantes",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Haie fleurie de mi-ombre, massif frais, jardin de bord de mer, façade nord",
 "asso":"Hydrangea, Hosta, fougères, Carex, Anemone du Japon",
 "cons":"Le seul fuchsia vraiment rustique, utilisé en haie fleurie sur toute la façade atlantique où il forme des massifs impressionnants. Floraison de six mois à mi-ombre, ce qui est rare. Peut geler jusqu'au sol en hiver froid et repartir de souche au printemps : pailler le pied et ne rabattre qu'en avril, une fois le redémarrage visible.",
 "bdm":"Front de mer","dens":0.8,"esp":1.2},

{"lat":"Gaillardia grandiflora","fr":"Gaillarde","type":"Vivace","h":0.6,"l":0.5,
 "expo":"Plein soleil","sol":"Drainé, sableux, pauvre","hum":"Sec","rust":-20,
 "feu":"Caduc","cfeu":"Vert grisé","m1":6,"m2":10,"flo":"Juin à octobre","cflo":"Rouge et jaune, bicolore",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif estival, jardin sec, bordure, prairie fleurie, bord de mer",
 "asso":"Coreopsis, Echinacea, graminées, Achillea, Perovskia",
 "cons":"Couleurs chaudes en bicolore, floraison de cinq mois si on supprime régulièrement les fleurs fanées. Très résistante à la sécheresse et au vent salé. Durée de vie courte, deux à trois ans, surtout en sol lourd : le drainage est le seul facteur qui la prolonge vraiment. Ne pas rabattre avant le printemps.",
 "bdm":"Front de mer","dens":5,"esp":0.45},

{"lat":"Galium odoratum","fr":"Aspérule odorante","type":"Couvre-sol","h":0.2,"l":0.5,
 "expo":"Mi-ombre à ombre","sol":"Humifère, frais, calcaire toléré","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert vif, en verticilles étoilés","m1":4,"m2":6,"flo":"Avril à juin","cflo":"Blanc pur, étoilé",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Sous-bois, pied d'arbre, tapis d'ombre, jardin naturaliste",
 "asso":"Fougères, Hosta, Epimedium, Luzula, Anemone des bois",
 "cons":"Tapis léger d'étoiles vertes surmonté de fleurs blanches, l'image même du sous-bois. Dégage un parfum de foin coupé en séchant, utilisé pour aromatiser le vin de mai. S'étale par rhizomes et couvre efficacement sous les arbres. Exige la fraîcheur : elle disparaît en été sec, mais revient l'année suivante.",
 "bdm":"Second rideau","dens":9,"esp":0.3},

{"lat":"Geranium endressii","fr":"Géranium d'Endress","type":"Couvre-sol","h":0.5,"l":0.6,
 "expo":"Soleil à mi-ombre","sol":"Tout type, humifère, drainé","hum":"Frais","rust":-25,
 "feu":"Semi-persistant","cfeu":"Vert clair découpé","m1":5,"m2":9,"flo":"Mai à septembre","cflo":"Rose saumoné",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Couvre-sol fleuri, bordure, pied de rosier, talus, aménagement collectif",
 "asso":"Rosiers, Alchemilla, Nepeta, graminées, Astrantia",
 "cons":"Rose saumoné lumineux sur cinq mois, l'un des géraniums vivaces les plus florifères. Forme un tapis dense qui étouffe les adventices. Rabattre à ras après la première vague : il refait un feuillage neuf et refleurit jusqu'aux gelées. Le cultivar Wargrave Pink est le plus répandu et le plus fiable.",
 "bdm":"Second rideau","dens":4,"esp":0.5},

{"lat":"Helleborus niger","fr":"Rose de Noël","type":"Vivace","h":0.4,"l":0.4,
 "expo":"Mi-ombre à ombre","sol":"Humifère, drainé, calcaire toléré, profond","hum":"Frais","rust":-25,
 "feu":"Persistant","cfeu":"Vert foncé coriace","m1":12,"m2":3,"flo":"Décembre à mars","cflo":"Blanc, rose, pourpre, vert",
 "plant":"Automne","popt":"Septembre à novembre","ent":"Faible",
 "style":"Sous-bois, massif d'hiver, façade nord, pied d'arbre, potée",
 "asso":"Fougères, Carex, Epimedium, Cyclamen, bulbes précoces, Bergenia",
 "cons":"Fleurit en plein hiver, de décembre à mars, ce qu'aucune autre vivace du catalogue ne fait : c'est l'argument massue pour un massif d'ombre qui semble mort en janvier. Couper les vieilles feuilles en décembre pour dégager les fleurs. Lente à s'installer, patienter deux ans, et surtout ne jamais la déplacer ensuite.",
 "bdm":"Second rideau","dens":5,"esp":0.4},

{"lat":"Houttuynia cordata","fr":"Houttuynia","type":"Couvre-sol","h":0.3,"l":0.6,
 "expo":"Soleil à mi-ombre","sol":"Humifère, argileux toléré","hum":"Humide","rust":-20,
 "feu":"Caduc","cfeu":"Panaché de vert, crème, rose et rouge","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Blanc",
 "plant":"Printemps","popt":"Mars à mai","ent":"Moyen",
 "style":"Bord de bassin, zone humide, bac, couvre-sol de terrain détrempé",
 "asso":"Juncus, Carex, Lythrum, Iris des marais",
 "cons":"Feuillage multicolore spectaculaire, mais un avertissement s'impose : elle est extrêmement traçante en sol humide et devient impossible à éradiquer une fois installée, le moindre fragment de rhizome repartant. À réserver aux bacs, aux paniers de bassin ou aux zones bien délimitées. Odeur forte au froissement.",
 "bdm":"Second rideau","dens":6,"esp":0.4},

{"lat":"Hydrangea arborescens","fr":"Hortensia arborescent","type":"Arbuste","h":1.5,"l":1.5,
 "expo":"Mi-ombre","sol":"Humifère, frais, drainé, calcaire toléré","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert clair","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Blanc, en grosses boules",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Massif d'ombre, haie libre, jardin blanc, façade nord",
 "asso":"Hosta, fougères, Anemone du Japon, Carex, Astrantia",
 "cons":"Le cultivar Annabelle porte d'énormes boules blanches de 25 cm. Comme le paniculata, il fleurit sur le bois de l'année : taille franche en fin d'hiver, sans risque de perdre la floraison. Tolère le calcaire, contrairement au macrophylla. Les tiges peuvent ployer sous le poids des fleurs après la pluie : une taille moins sévère donne des fleurs plus petites mais mieux tenues.",
 "bdm":"Second rideau","dens":0.5,"esp":1.4},

{"lat":"Hydrangea aspera","fr":"Hortensia velouté","type":"Arbuste","h":2.5,"l":2.5,
 "expo":"Mi-ombre","sol":"Humifère, drainé, frais, acide à neutre","hum":"Frais","rust":-18,
 "feu":"Caduc","cfeu":"Vert foncé, grandes feuilles veloutées","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Mauve et blanc, en plateaux",
 "plant":"Automne à printemps","popt":"Octobre ou mars","ent":"Faible",
 "style":"Sous-bois clair, massif d'ombre, sujet isolé, jardin de collection",
 "asso":"Acer palmatum, fougères, Hosta, Carex, Anemone du Japon",
 "cons":"Grandes feuilles veloutées au toucher et inflorescences plates à fleurs stériles mauves en couronne : le plus élégant des hortensias, et le moins connu. Redoute le soleil direct et le vent, qui abîment le feuillage. Fleurit sur le bois de l'année précédente, donc taille légère uniquement. Emplacement abrité indispensable.",
 "bdm":"Déconseillé en bord de mer","dens":0.3,"esp":2.0},

{"lat":"Hyssopus officinalis","fr":"Hysope","type":"Vivace / Aromatique","h":0.5,"l":0.4,
 "expo":"Plein soleil","sol":"Drainé, sec, calcaire, pauvre","hum":"Sec","rust":-25,
 "feu":"Semi-persistant","cfeu":"Vert foncé étroit, aromatique","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Bleu violacé, rose, blanc",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin d'aromatiques, bordure basse, jardin médiéval, rocaille, jardin sec",
 "asso":"Lavandula, Thymus, Santolina, Satureja, Origanum",
 "cons":"Épis bleus très mellifères en fin d'été, sur une petite plante aromatique qui se taille en bordure basse. Traditionnelle des jardins de curé et des jardins médiévaux. Rabattre au printemps pour garder un port compact, jamais sur le vieux bois. Exige un drainage franc, elle pourrit en terre lourde.",
 "bdm":"Front de mer","dens":5,"esp":0.4},

{"lat":"Iberis sempervirens","fr":"Corbeille d'argent vivace","type":"Couvre-sol","h":0.3,"l":0.5,
 "expo":"Plein soleil","sol":"Drainé, calcaire, pauvre, caillouteux","hum":"Sec","rust":-25,
 "feu":"Persistant","cfeu":"Vert foncé","m1":3,"m2":5,"flo":"Mars à mai","cflo":"Blanc pur",
 "plant":"Automne à printemps","popt":"Septembre à octobre ou mars","ent":"Faible",
 "style":"Rocaille, muret, bordure, dessus de mur, jardin de gravier",
 "asso":"Aubrieta, Arabis, Armeria, Sedum, Cerastium",
 "cons":"Coussin persistant qui disparaît sous une nappe blanche au printemps, et qui reste propre le reste de l'année, contrairement à l'aubriète qui se dégarnit. Rabattre d'un tiers après la floraison pour maintenir la forme. Très mellifère et précoce. Aucune exigence hormis le drainage.",
 "bdm":"Front de mer","dens":5,"esp":0.45},

{"lat":"Iris germanica","fr":"Iris des jardins","type":"Vivace","h":0.8,"l":0.4,
 "expo":"Plein soleil","sol":"Drainé, calcaire toléré, pauvre toléré","hum":"Sec","rust":-25,
 "feu":"Semi-persistant","cfeu":"Vert bleuté, en glaives","m1":4,"m2":6,"flo":"Avril à juin","cflo":"Bleu, violet, jaune, blanc, bicolore",
 "plant":"Automne","popt":"Juillet à septembre","ent":"Faible",
 "style":"Massif sec, bordure, jardin de curé, rocaille, jardin méditerranéen",
 "asso":"Lavandula, Nepeta, Salvia nemorosa, Perovskia, graminées",
 "cons":"Point technique décisif : le rhizome doit affleurer à la surface du sol, à moitié découvert et exposé au soleil. Planté trop profond ou paillé, il ne fleurit pas — c'est la cause d'échec numéro un. Planter de préférence en été après la floraison. Diviser tous les trois ou quatre ans. Feuillage en glaives décoratif toute la saison.",
 "bdm":"Front de mer","dens":6,"esp":0.4},

{"lat":"Iris pseudacorus","fr":"Iris des marais","type":"Vivace","h":1.2,"l":0.6,
 "expo":"Plein soleil","sol":"Tout type, humifère, argileux toléré","hum":"Humide","rust":-30,
 "feu":"Caduc","cfeu":"Vert franc, en glaives","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Jaune d'or",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Bord de bassin, noue, lagunage, berge, phytoépuration",
 "asso":"Juncus, Carex pendula, Lythrum, Filipendula, Eupatorium",
 "cons":"Espèce indigène qui vit les pieds dans l'eau, jusqu'à 30 cm de profondeur : la plante de base d'une ceinture de bassin ou d'une noue. Utilisée en phytoépuration pour sa capacité à filtrer. Très vigoureuse et colonisatrice en milieu favorable : la contenir en panier si le bassin est petit.",
 "bdm":"Second rideau","dens":4,"esp":0.5},

{"lat":"Isopogon formosus","fr":"Isopogon","type":"Arbuste","h":1.5,"l":1.2,
 "expo":"Plein soleil","sol":"Drainé, sableux, acide, très pauvre","hum":"Sec","rust":-8,
 "feu":"Persistant","cfeu":"Vert fin et découpé","m1":3,"m2":6,"flo":"Mars à juin","cflo":"Rose fuchsia, en cônes",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Jardin sec, jardin exotique, bord de mer abrité, massif de collection",
 "asso":"Grevillea, Callistemon, Leptospermum, Phormium, graminées sèches",
 "cons":"Fleurs en cônes roses très originales, sur un arbuste australien encore rare. Comme les grévilléas, il redoute absolument le calcaire et le phosphore : ne jamais fertiliser, cela le tue. Rusticité très faible, à réserver aux secteurs littoraux les plus doux et bien abrités. À proposer en connaissance de cause.",
 "bdm":"Front de mer","dens":0.6,"esp":1.3},

{"lat":"Juncus inflexus","fr":"Jonc glauque","type":"Graminée","h":0.8,"l":0.5,
 "expo":"Plein soleil","sol":"Tout type, argileux toléré","hum":"Humide","rust":-30,
 "feu":"Persistant","cfeu":"Bleu glauque, tiges cylindriques dressées","m1":6,"m2":8,"flo":"Juin à août","cflo":"Brun discret",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Bord de bassin, noue, lagunage, zone détrempée, massif contemporain",
 "asso":"Iris pseudacorus, Carex, Lythrum, Filipendula, Molinia",
 "cons":"Espèce indigène des sols détrempés, aux tiges cylindriques bleutées parfaitement verticales : un graphisme très net qui fonctionne bien en aménagement contemporain autour d'un bassin. Persistant, il structure la berge en hiver. Utilisé en phytoépuration. Supporte l'eau stagnante et les sols compactés.",
 "bdm":"Second rideau","dens":4,"esp":0.5},

{"lat":"Knautia arvensis","fr":"Knautie des champs","type":"Vivace","h":0.9,"l":0.5,
 "expo":"Plein soleil","sol":"Drainé, calcaire toléré, pauvre","hum":"Sec","rust":-30,
 "feu":"Caduc","cfeu":"Vert grisé","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Mauve, pourpre",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Prairie fleurie, massif naturaliste, jardin champêtre, bordure haute",
 "asso":"Scabiosa, Briza, Salvia nemorosa, Achillea, Malva, graminées",
 "cons":"Espèce indigène des prairies, indispensable dans un mélange de prairie fleurie : floraison de quatre mois et l'une des meilleures plantes pour les papillons et les abeilles sauvages. Port souple et aéré qui se mêle naturellement aux graminées. Se ressème et se déplace, ce qui est l'effet recherché.",
 "bdm":"Front de mer","dens":4,"esp":0.5},

{"lat":"Kniphofia uvaria","fr":"Tritome","type":"Vivace","h":1.2,"l":0.6,
 "expo":"Plein soleil","sol":"Drainé, profond, humifère","hum":"Frais","rust":-15,
 "feu":"Semi-persistant","cfeu":"Vert bleuté, en glaives arqués","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Orange et jaune, en épis dressés",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif estival, jardin exotique, bord de mer, sujet architectural, jardin sec",
 "asso":"Agapanthus, Crocosmia, graminées, Hemerocallis, Phormium",
 "cons":"Épis dressés en flamme orange et jaune, très verticaux, qui donnent immédiatement un caractère exotique. Bonne tenue au vent salé. Le point sensible est l'humidité hivernale au cœur de la touffe : lier le feuillage en fauteuil au-dessus du collet pour l'hiver en secteur froid et humide. Ne pas rabattre à l'automne.",
 "bdm":"Front de mer","dens":3,"esp":0.6},

{"lat":"Koeleria glauca","fr":"Koélérie glauque","type":"Graminée","h":0.3,"l":0.3,
 "expo":"Plein soleil","sol":"Drainé, sec, sableux, pauvre, calcaire toléré","hum":"Sec","rust":-25,
 "feu":"Persistant","cfeu":"Bleu argenté","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Beige argenté, en épis compacts",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Rocaille, bordure, jardin de gravier, massif contemporain, toiture végétalisée",
 "asso":"Festuca glauca, Sedum, Armeria, Thymus, Delosperma",
 "cons":"Proche de la fétuque bleue mais à floraison nettement plus décorative, en épis compacts argentés dressés au-dessus de la touffe. Persistante et très résistante à la sécheresse. Peigner au printemps. Comme toutes les graminées bleutées, elle exige le plein soleil et un sol pauvre pour garder sa couleur.",
 "bdm":"Front de mer","dens":6,"esp":0.4},

{"lat":"Kolkwitzia amabilis","fr":"Buisson de beauté","type":"Arbuste","h":3.0,"l":2.5,
 "expo":"Soleil à mi-ombre","sol":"Drainé, tout type, calcaire toléré","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc, ocre en automne","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Rose tendre à gorge jaune",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie libre fleurie, massif de printemps, sujet isolé, jardin de curé",
 "asso":"Deutzia, Weigelia, Philadelphus, Spiraea nipponica, Syringa",
 "cons":"Rameaux arqués entièrement couverts de clochettes roses, un des plus beaux arbustes de printemps et pourtant peu prescrit. Écorce exfoliante décorative en hiver. Aucune exigence de sol. Tailler après la floraison, en supprimant un tiers des vieilles branches à la base tous les trois ans.",
 "bdm":"Second rideau","dens":0.3,"esp":1.8},

{"lat":"Laburnum anagyroides","fr":"Cytise","type":"Arbre","h":6.0,"l":4.0,
 "expo":"Plein soleil","sol":"Drainé, calcaire toléré, pauvre toléré","hum":"Sec à frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert bleuté, trifolié","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Jaune d'or, en longues grappes",
 "plant":"Automne","popt":"Novembre à mars","ent":"Faible",
 "style":"Sujet isolé, petit jardin, tonnelle en arceau, jardin de curé",
 "asso":"Wisteria, Ceanothus, vivaces bleues, graminées",
 "cons":"Longues grappes jaunes pendantes en mai, spectaculaires, surtout conduit sur une arche. Attention, mention obligatoire au client : toutes les parties de la plante sont très toxiques, en particulier les graines contenues dans les gousses, qui attirent les enfants. À proscrire dans un jardin avec de jeunes enfants ou des animaux.",
 "bdm":"Second rideau","dens":0.06,"esp":4.0},

{"lat":"Lavatera cachemiriana","fr":"Lavatère arbustive","type":"Arbuste / Vivace","h":2.0,"l":1.5,
 "expo":"Plein soleil","sol":"Drainé, pauvre toléré, calcaire toléré","hum":"Sec","rust":-15,
 "feu":"Semi-persistant","cfeu":"Vert grisé duveteux","m1":6,"m2":10,"flo":"Juin à octobre","cflo":"Rose tendre, blanc",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif estival, haie libre fleurie, bord de mer, jardin sec, écran rapide",
 "asso":"Perovskia, graminées, Gaura, Caryopteris, Verbena bonariensis",
 "cons":"Croissance très rapide et floraison de cinq mois : la solution quand un client veut un effet immédiat en une saison. Bonne tenue au vent salé. Durée de vie courte, quatre à cinq ans, et bois cassant : rabattre de moitié chaque printemps pour la densifier et limiter la casse. À annoncer comme une plante de transition.",
 "bdm":"Front de mer","dens":0.5,"esp":1.4},

{"lat":"Leucanthemum maximum","fr":"Marguerite d'été","type":"Vivace","h":0.8,"l":0.5,
 "expo":"Plein soleil","sol":"Drainé, profond, tout type","hum":"Frais","rust":-30,
 "feu":"Semi-persistant","cfeu":"Vert foncé","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Blanc à cœur jaune",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif estival, jardin champêtre, bordure, jardin blanc, fleurs à couper",
 "asso":"Salvia nemorosa, graminées, Achillea, Echinacea, Nepeta",
 "cons":"La marguerite classique en version vivace et robuste, valeur sûre du massif d'été. Supprimer régulièrement les fleurs fanées prolonge nettement la floraison. Diviser tous les trois ans, le centre de la touffe s'épuise. Les cultivars à grandes fleurs peuvent nécessiter un tuteurage discret en situation venteuse.",
 "bdm":"Second rideau","dens":4,"esp":0.5},

{"lat":"Leycesteria formosa","fr":"Arbre aux faisans","type":"Arbuste","h":2.0,"l":1.5,
 "expo":"Soleil à mi-ombre","sol":"Humifère, drainé, frais","hum":"Frais","rust":-15,
 "feu":"Caduc","cfeu":"Vert clair, tiges vertes creuses","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Blanc à bractées pourpres",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Massif d'ombre claire, haie libre, jardin de biodiversité, sous-bois",
 "asso":"Hydrangea, Kerria, fougères, graminées, Cornus",
 "cons":"Grappes pendantes blanches enchâssées dans des bractées pourpre foncé, puis baies noires très appréciées des oiseaux, d'où son nom. Tiges vertes creuses décoratives en hiver. Fleurit sur le bois de l'année : rabattre à 30 cm en fin d'hiver, il repart vigoureusement. Se ressème facilement.",
 "bdm":"Second rideau","dens":0.6,"esp":1.2},

{"lat":"Liatris spicata","fr":"Plume du Kansas","type":"Vivace","h":0.8,"l":0.3,
 "expo":"Plein soleil","sol":"Drainé, sableux, pauvre toléré","hum":"Sec à frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert franc, en touffe fine","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Violet mauve, blanc",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif naturaliste, prairie fleurie, bordure, jardin sec, fleurs à couper",
 "asso":"Echinacea, Rudbeckia, graminées, Sedum spectabile, Achillea",
 "cons":"Épis dressés qui fleurissent du haut vers le bas, à l'inverse de presque toutes les autres plantes : un détail qui amuse toujours les clients. Très mellifère et excellente en bouquet. Redoute l'humidité hivernale, qui fait pourrir le cormus : drainage impératif, et ne jamais rabattre avant le printemps.",
 "bdm":"Second rideau","dens":6,"esp":0.4},

{"lat":"Limonium latifolium","fr":"Lavande de mer","type":"Vivace","h":0.6,"l":0.5,
 "expo":"Plein soleil","sol":"Drainé, sableux, pauvre, salin toléré","hum":"Sec","rust":-20,
 "feu":"Semi-persistant","cfeu":"Vert foncé, en rosette basale","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Bleu lavande, en nuage",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin de bord de mer, jardin sec, rocaille, fleurs séchées, jardin de gravier",
 "asso":"Armeria, Eryngium, graminées, Gaura, Sedum",
 "cons":"Nuage de minuscules fleurs bleues au-dessus d'une rosette basale plate, un effet très aérien. Résiste au sel et au vent, c'est une plante des littoraux. Se conserve indéfiniment en bouquet sec, c'est le statice des fleuristes. Racine pivotante profonde : très résistante à la sécheresse mais impossible à déplacer.",
 "bdm":"Front de mer","dens":4,"esp":0.5},

{"lat":"Lippia citriodora","fr":"Verveine citronnelle","type":"Arbuste / Aromatique","h":2.0,"l":1.5,
 "expo":"Plein soleil","sol":"Drainé, léger, riche","hum":"Sec à frais","rust":-8,
 "feu":"Caduc","cfeu":"Vert clair, parfum citronné puissant","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Blanc lilas discret",
 "plant":"Printemps","popt":"Avril à mai","ent":"Moyen",
 "style":"Jardin d'aromatiques, terrasse, potée, près d'un passage pour le parfum",
 "asso":"Salvia, Lavandula, Melissa, Origanum, agrumes en bac",
 "cons":"Le parfum citronné le plus puissant du catalogue, libéré au moindre frôlement : à planter impérativement le long d'un passage ou près d'une terrasse. Usage en infusion. Rusticité faible, c'est sa vraie limite : elle gèle en dessous de -8 °C et il est plus sûr de la cultiver en bac à rentrer, ou de pailler très généreusement. Feuillaison très tardive, en mai.",
 "bdm":"Front de mer","dens":0.5,"esp":1.4},

{"lat":"Lobelia cardinalis","fr":"Lobélie cardinale","type":"Vivace","h":1.0,"l":0.4,
 "expo":"Soleil à mi-ombre","sol":"Humifère, riche, profond","hum":"Frais à humide","rust":-20,
 "feu":"Semi-persistant","cfeu":"Vert pourpré à bronze","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Rouge écarlate",
 "plant":"Printemps","popt":"Avril à mai","ent":"Moyen",
 "style":"Bord de bassin, zone humide, massif frais, jardin exotique",
 "asso":"Lythrum, Eupatorium, Carex, Hosta, Persicaria, Molinia",
 "cons":"Le rouge le plus intense du catalogue, sur des épis dressés, avec un feuillage pourpré qui l'accompagne. Exige un sol constamment frais à humide et riche : elle dépérit rapidement en terrain ordinaire. Durée de vie limitée, à diviser tous les deux ou trois ans pour la maintenir. Pailler le pied en hiver.",
 "bdm":"Second rideau","dens":6,"esp":0.4},

{"lat":"Lonicera japonica","fr":"Chèvrefeuille du Japon","type":"Grimpante","h":6.0,"l":3.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, drainé, calcaire toléré","hum":"Frais","rust":-20,
 "feu":"Semi-persistant","cfeu":"Vert franc","m1":5,"m2":9,"flo":"Mai à septembre","cflo":"Blanc virant jaune, très parfumé",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Moyen",
 "style":"Clôture, pergola, treillage, habillage rapide, couvre-sol de talus",
 "asso":"Clematis, Rosa grimpant, Jasminum, Vitis",
 "cons":"Croissance très rapide et floraison parfumée de cinq mois : la solution pour masquer un grillage en une saison. Parfum le plus puissant le soir, à placer près d'une terrasse. Vigueur à surveiller, il étouffe ses voisins et est classé envahissant dans certaines régions : taille annuelle sévère indispensable pour le contenir.",
 "bdm":"Front de mer","dens":0.5,"esp":2.0},

{"lat":"Mahonia","fr":"Mahonia","type":"Arbuste","h":2.5,"l":2.0,
 "expo":"Mi-ombre à ombre","sol":"Tout type, humifère, calcaire toléré","hum":"Frais","rust":-20,
 "feu":"Persistant","cfeu":"Vert foncé brillant, épineux, pourpré en hiver","m1":11,"m2":2,"flo":"Novembre à février","cflo":"Jaune d'or, en épis parfumés",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Massif d'ombre, façade nord, haie défensive, jardin d'hiver, sous-bois",
 "asso":"Sarcococca, Helleborus, fougères, Hedera, Bergenia",
 "cons":"Fleurit en plein hiver, de novembre à février, avec un parfum de muguet, à l'ombre, là où rien d'autre ne se passe : c'est une des plantes les plus utiles du catalogue. Baies bleutées ensuite, appréciées des oiseaux. Feuillage très épineux, à écarter des passages mais parfait en haie défensive. Supprimer les tiges les plus âgées à la base pour renouveler.",
 "bdm":"Second rideau","dens":0.6,"esp":1.2},

{"lat":"Matteuccia struthiopteris","fr":"Fougère plume d'autruche","type":"Fougère","h":1.2,"l":0.8,
 "expo":"Mi-ombre à ombre","sol":"Humifère, riche, profond, acide à neutre","hum":"Frais à humide","rust":-30,
 "feu":"Caduc","cfeu":"Vert tendre, en vase régulier","m1":0,"m2":0,"flo":"Non fleurie","cflo":"—",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Sous-bois humide, bord de bassin, massif d'ombre, jardin naturaliste",
 "asso":"Hosta, Carex pendula, Astrantia, Persicaria, Osmunda",
 "cons":"Frondes disposées en vase parfaitement régulier, d'une élégance remarquable au printemps. Exige un sol riche et constamment frais : elle brunit dès juillet en terrain sec, ce qui est le reproche le plus fréquent. Traçante par stolons, elle forme des colonies : à lui donner de l'espace ou à contenir.",
 "bdm":"Second rideau","dens":1.5,"esp":0.8},

{"lat":"Morus kagayamae","fr":"Mûrier platane","type":"Arbre","h":6.0,"l":6.0,
 "expo":"Plein soleil","sol":"Tout type, drainé, calcaire toléré","hum":"Sec à frais","rust":-20,
 "feu":"Caduc","cfeu":"Vert franc, grandes feuilles","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Non ornementale",
 "plant":"Automne à printemps","popt":"Novembre à mars","ent":"Moyen",
 "style":"Arbre d'ombrage de terrasse, cour, alignement urbain, arbre têtard",
 "asso":"Terrasse, cour minérale, plantations basses au pied",
 "cons":"Variété stérile qui ne fructifie pas : c'est tout son intérêt en terrasse, là où le mûrier fruitier tache les dallages et les vêtements. Se conduit en tête de chat, taillé chaque hiver au même point, formant un parasol dense et bas : c'est l'arbre d'ombrage de terrasse par excellence. Grandes feuilles, ombre très fraîche.",
 "bdm":"Front de mer","dens":0.05,"esp":5.0},

{"lat":"Muhlenbergia capillaris","fr":"Muhlenbergia","type":"Graminée","h":0.9,"l":0.8,
 "expo":"Plein soleil","sol":"Drainé, sableux, pauvre","hum":"Sec","rust":-18,
 "feu":"Semi-persistant","cfeu":"Vert fin","m1":9,"m2":11,"flo":"Septembre à novembre","cflo":"Rose pourpré, en nuage vaporeux",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Massif contemporain, jardin sec, plantation de masse, contre-jour d'automne",
 "asso":"Sedum spectabile, Perovskia, Aster, Panicum, Echinacea",
 "cons":"Nuage rose vaporeux en octobre, spectaculaire à contre-jour et plus encore en plantation de masse : c'est là qu'elle prend toute sa dimension, un pied isolé déçoit. Floraison très tardive, elle prend le relais quand tout s'éteint. Drainage impératif, rabattre en mars seulement.",
 "bdm":"Front de mer","dens":2,"esp":0.7},

{"lat":"Phlox subulata","fr":"Phlox mousse","type":"Couvre-sol","h":0.15,"l":0.4,
 "expo":"Plein soleil","sol":"Drainé, sec, pauvre, caillouteux","hum":"Sec","rust":-25,
 "feu":"Persistant","cfeu":"Vert vif, en coussin aciculaire","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Rose, mauve, blanc, bleu",
 "plant":"Automne à printemps","popt":"Septembre à octobre ou mars","ent":"Faible",
 "style":"Rocaille, muret, talus sec, dallage, dessus de mur, bordure basse",
 "asso":"Aubrieta, Iberis, Arabis, Armeria, Sedum, Festuca glauca",
 "cons":"Tapis persistant qui disparaît totalement sous les fleurs en avril, l'un des effets les plus spectaculaires du printemps en rocaille. Rabattre d'un tiers après la floraison pour éviter qu'il se dégarnisse au centre. Exige un drainage franc et un sol pauvre. Retombe très bien d'un muret.",
 "bdm":"Front de mer","dens":6,"esp":0.4},

{"lat":"Platanus acerifolia","fr":"Platane commun","type":"Arbre","h":30.0,"l":20.0,
 "expo":"Plein soleil","sol":"Tout type, profond, frais","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc, ocre en automne","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Non ornementale",
 "plant":"Automne","popt":"Novembre à mars","ent":"Moyen",
 "style":"Alignement, place de village, grande propriété, arbre têtard, cour ombragée",
 "asso":"Alignement monospécifique, cour minérale",
 "cons":"Arbre de très grand développement, à réserver aux alignements et aux grandes propriétés, ou à conduire en têtard taillé chaque hiver pour un ombrage de cour maîtrisé. Écorce en plaques très décorative. Deux points à signaler : le chancre coloré, maladie grave et réglementée dans le Sud, et les poils des fruits, irritants pour les voies respiratoires.",
 "bdm":"Second rideau","dens":0.01,"esp":10.0},

{"lat":"Polypodium vulgare","fr":"Polypode commun","type":"Fougère","h":0.3,"l":0.4,
 "expo":"Mi-ombre à ombre","sol":"Drainé, humifère, pauvre, fissures","hum":"Sec à frais","rust":-25,
 "feu":"Persistant","cfeu":"Vert franc, frondes simples","m1":0,"m2":0,"flo":"Non fleurie","cflo":"—",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Vieux mur, muret de pierre, souche, talus ombragé, sous-bois sec",
 "asso":"Asplenium, mousses, Hedera, Luzula, Epimedium",
 "cons":"Fougère indigène qui pousse en épiphyte sur les vieux murs, les souches et les troncs moussus, sans terre : la seule fougère vraiment adaptée à l'ombre sèche. Persistante toute l'année. Croissance lente, effet progressif. Excellente pour végétaliser naturellement un enrochement ou un muret ancien.",
 "bdm":"Second rideau","dens":4,"esp":0.5},

{"lat":"Teucrium fruticans","fr":"Germandrée arbustive","type":"Arbuste","h":1.5,"l":1.5,
 "expo":"Plein soleil","sol":"Drainé, sec, calcaire, pauvre","hum":"Sec","rust":-10,
 "feu":"Persistant","cfeu":"Argenté, revers blanc feutré","m1":4,"m2":9,"flo":"Avril à septembre","cflo":"Bleu lavande",
 "plant":"Printemps","popt":"Mars à mai","ent":"Moyen",
 "style":"Haie basse taillée, topiaire argentée, jardin méditerranéen, bord de mer",
 "asso":"Lavandula, Santolina, Cistus, Phlomis, Rosmarinus",
 "cons":"Feuillage argenté persistant qui se taille en haie basse ou en boule, une alternative méditerranéenne au buis avec en prime une floraison bleue étalée sur cinq mois. Excellente tenue aux embruns. Rusticité limitée : à réserver aux secteurs doux et abrités, il souffre en dessous de -10 °C. Taille légère après la floraison principale.",
 "bdm":"Front de mer","dens":0.8,"esp":0.6},

{"lat":"Tilia platyphyllos","fr":"Tilleul à grandes feuilles","type":"Arbre","h":25.0,"l":15.0,
 "expo":"Soleil à mi-ombre","sol":"Profond, frais, calcaire toléré","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert franc, jaune d'or en automne","m1":6,"m2":6,"flo":"Juin","cflo":"Jaune crème, très parfumé",
 "plant":"Automne","popt":"Novembre à mars","ent":"Moyen",
 "style":"Alignement, place de village, arbre d'ombrage, arbre têtard, tilleul taillé en rideau",
 "asso":"Alignement monospécifique, prairie, cour",
 "cons":"L'arbre d'ombrage traditionnel des cours et des places, dont la floraison de juin embaume et attire les abeilles par milliers. Fleurs récoltées en tisane. Se conduit très bien en rideau taillé ou en têtard, ce qui permet de le maîtriser dans un espace contraint. Attention au miellat des pucerons, qui poisse les voitures garées dessous.",
 "bdm":"Second rideau","dens":0.01,"esp":8.0},

{"lat":"Tulbaghia violacea","fr":"Ail d'Afrique du Sud","type":"Vivace","h":0.5,"l":0.3,
 "expo":"Plein soleil","sol":"Drainé, sableux, pauvre","hum":"Sec","rust":-10,
 "feu":"Persistant","cfeu":"Vert bleuté, en touffe fine","m1":6,"m2":10,"flo":"Juin à octobre","cflo":"Mauve lilas",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Bordure, jardin sec, bord de mer, potée, jardin méditerranéen",
 "asso":"Agapanthus, Gaura, graminées, Perovskia, Delosperma",
 "cons":"Floraison de cinq mois sur une touffe fine et persistante, très employée en bordure sur le littoral. Feuillage à odeur d'ail au froissement, réputé éloigner certains ravageurs. Rusticité limitée : paillage hivernal nécessaire, ou culture en potée en secteur froid. Drainage impératif, elle pourrit en sol lourd.",
 "bdm":"Front de mer","dens":6,"esp":0.4},

{"lat":"Valeriana officinalis","fr":"Valériane officinale","type":"Vivace","h":1.5,"l":0.6,
 "expo":"Soleil à mi-ombre","sol":"Humifère, profond, argileux toléré","hum":"Frais à humide","rust":-30,
 "feu":"Caduc","cfeu":"Vert franc, découpé","m1":6,"m2":8,"flo":"Juin à août","cflo":"Blanc rosé, en ombelles",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin naturaliste, bord de bassin, prairie humide, jardin de simples",
 "asso":"Eupatorium, Filipendula, Lythrum, Molinia, Sanguisorba",
 "cons":"Espèce indigène des lieux frais, à ne pas confondre avec la valériane rouge des murs secs, qui est un Centranthus et n'a rien à voir. Ombelles blanches parfumées, très mellifères. Plante médicinale historique, la racine est sédative. Se ressème abondamment en milieu frais.",
 "bdm":"Second rideau","dens":2,"esp":0.7},

{"lat":"Viburnum lantana","fr":"Viorne lantane","type":"Arbuste","h":4.0,"l":3.0,
 "expo":"Soleil à mi-ombre","sol":"Drainé, calcaire, pauvre toléré, sec","hum":"Sec à frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert grisé duveteux, rouge pourpre en automne","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Blanc crème",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie champêtre, talus sec, jardin de biodiversité, terrain calcaire",
 "asso":"Cornus sanguinea, Crataegus, Prunus spinosa, Ligustrum vulgare",
 "cons":"Espèce indigène des coteaux calcaires secs, complémentaire de la viorne obier qui, elle, veut la fraîcheur : c'est le bon choix pour une haie champêtre en terrain sec et calcaire. Baies passant du rouge au noir, souvent les deux couleurs sur la même grappe. Feuillage duveteux, coloration automnale pourpre. Aucun entretien.",
 "bdm":"Second rideau","dens":0.3,"esp":1.8},

{"lat":"Viola labradorica","fr":"Violette du Labrador","type":"Couvre-sol","h":0.15,"l":0.3,
 "expo":"Mi-ombre à ombre","sol":"Humifère, drainé, frais","hum":"Frais","rust":-30,
 "feu":"Semi-persistant","cfeu":"Vert pourpré à bronze","m1":3,"m2":5,"flo":"Mars à mai","cflo":"Mauve violacé",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Sous-bois, pied d'arbre, bordure d'ombre, entre-dalles ombragé, jardin naturaliste",
 "asso":"Fougères, Epimedium, Galium, Luzula, Hosta, Helleborus",
 "cons":"Petit tapis au feuillage pourpré permanent, qui met en valeur les fleurs mauves du printemps. Se ressème librement et s'installe dans les moindres interstices, entre les dalles et au pied des murs : c'est le charme d'une plante qui se place elle-même, mais il faut l'accepter. Aucun entretien.",
 "bdm":"Second rideau","dens":9,"esp":0.3},

{"lat":"Vitis vinifera","fr":"Vigne","type":"Grimpante / Fruitier","h":8.0,"l":3.0,
 "expo":"Plein soleil","sol":"Drainé, caillouteux, pauvre, calcaire toléré","hum":"Sec","rust":-20,
 "feu":"Caduc","cfeu":"Vert, ou pourpre, écarlate en automne","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Vert discret, parfumé",
 "plant":"Automne à printemps","popt":"Novembre à mars","ent":"Moyen",
 "style":"Pergola, tonnelle, treille de terrasse, palissage sur mur, jardin nourricier",
 "asso":"Rosa grimpant, Jasminum, Wisteria, aromatiques au pied",
 "cons":"L'ombrage de terrasse idéal : dense en été quand on en a besoin, et disparu en hiver quand on cherche le soleil. Couleur d'automne souvent spectaculaire. Exige une structure solide et une taille annuelle en hiver, sans laquelle elle s'emballe. Surveiller mildiou et oïdium en climat humide ; les variétés résistantes évitent tout traitement.",
 "bdm":"Front de mer","dens":0.3,"esp":3.0},

{"lat":"Yucca rostrata","fr":"Yucca bec","type":"Arbuste / Sujet architectural","h":3.0,"l":1.5,
 "expo":"Plein soleil","sol":"Drainé, sableux, caillouteux, très pauvre","hum":"Sec","rust":-18,
 "feu":"Persistant","cfeu":"Bleu argenté, en sphère de lames fines","m1":6,"m2":7,"flo":"Juin à juillet","cflo":"Blanc crème, en hampe dressée",
 "plant":"Printemps","popt":"Avril à juin","ent":"Faible",
 "style":"Jardin sec, jardin contemporain, sujet isolé, jardin de gravier, entrée",
 "asso":"Graminées bleutées, Sedum, Delosperma, Agave, Phormium",
 "cons":"Sphère parfaite de lames bleu argenté portée sur un tronc, l'un des plus beaux sujets architecturaux du catalogue et une pièce maîtresse qui justifie son prix. Bien plus rustique qu'il n'y paraît, à condition d'un drainage parfait : c'est l'humidité hivernale au collet qui le tue, jamais le froid. Croissance très lente. Feuilles à pointe acérée.",
 "bdm":"Front de mer","dens":0.4,"esp":1.5},
]
