# -*- coding: utf-8 -*-
"""Lot 3 - 50 especes supplementaires du catalogue AD.V."""

ALIAS3 = {
    "Photinia":                 "Photinia fraseri",
    "Abelia":                   "Abelia grandiflora",
    "Anemone":                  "Anemone hupehensis",
    "Elaeagnus":                "Elaeagnus ebbingei",
    "Rubus":                    "Rubus idaeus",
    "Deutzia":                  "Deutzia magnifica",
    "Deutzia gracilis":         "Deutzia magnifica",
    "Deutzia crenata":          "Deutzia magnifica",
    "Gaura lindheimerie":       "Gaura lindheimeri",
    "Carex":                    "Carex morrowii",
    "Carex testacea":           "Carex buchananii",
    "Nepeta":                   "Nepeta faassenii",
    "Weigelia candida":         "Weigelia",
    "Pittosporum":              "Pittosporum tenuifolium",
    "Phormium":                 "Phormium tenax",
    "Hosta sieboldiana":        "Hosta",
    "Hosta fortunei":           "Hosta",
    "Potentilla abbotswood":    "Potentilla fruticosa",
    "Chaenomeles speciosa":     "Chaenomeles superba",
    "Thymus praecox":           "Thymus serpyllum",
    "Cistus salvifolius":       "Cistus corbariensis",
    "Cistus skanbergii":        "Cistus corbariensis",
    "Cistus florentinus":       "Cistus corbariensis",
    "Euphorbia martinii":       "Euphorbia characias",
    "Geranium cantabridgense":  "Geranium macrorrhizum",
    "Juniperus squamata":       "Juniperus chin",
    "Hedera algeriensis":       "Hedera",
    "Salvia pratensis":         "Salvia nemorosa",
    "Corylus maxima":           "Corylus avellana",
    "Buddleja davidii":         "Buddleia davidii",
    "Stipa tenuissima":         "Stipa tenuifolia",
    "Viburnum":                 "Viburnum tinus",
    "Cornus stolonifera":       "Cornus alba",
    "Pennisetum villosum":      "Pennisetum orientale",
    "Symphoricarpos chenaultii":"Symphoricarpos doorenbosii",
    "Thuya occidentalis":       "Thuya plicata",
    "Spiraea thunbergii":       "Spiraea nipponica",
    "Tamarix eté":              "Tamarix africana",
    "Ribes nigrum":             "Ribes rubrum",
}

FICHES3 = [
{"lat":"Arabis caucasica","fr":"Corbeille d'argent","type":"Couvre-sol","h":0.2,"l":0.4,
 "expo":"Plein soleil","sol":"Drainé, calcaire, pauvre, caillouteux","hum":"Sec","rust":-20,
 "feu":"Persistant","cfeu":"Vert grisé","m1":3,"m2":5,"flo":"Mars à mai","cflo":"Blanc",
 "plant":"Automne à printemps","popt":"Septembre à octobre ou mars","ent":"Faible",
 "style":"Rocaille, muret, talus sec, dallage, bordure basse",
 "asso":"Aubrieta, Iberis, Cerastium, Armeria, Sedum",
 "cons":"Retombe joliment d'un muret ou d'un dessus de mur, en nappe blanche au printemps. Rabattre de moitié après floraison pour garder un port compact, sinon elle s'étale et se dégarnit au centre. Redoute l'humidité stagnante bien plus que le froid.",
 "bdm":"Front de mer","dens":6,"esp":0.4},

{"lat":"Aronia prunifolia","fr":"Aronie","type":"Arbuste","h":2.0,"l":1.5,
 "expo":"Soleil à mi-ombre","sol":"Tout type, acide à neutre, argileux toléré","hum":"Frais à humide","rust":-30,
 "feu":"Caduc","cfeu":"Vert, rouge écarlate en automne","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Blanc",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie libre, jardin de biodiversité, jardin nourricier, massif d'automne",
 "asso":"Viburnum opulus, Cornus, Sambucus, graminées",
 "cons":"Trois saisons d'intérêt : floraison blanche au printemps, baies noires en été, feuillage rouge feu en automne. Baies très riches en antioxydants, consommées en jus ou en gelée, un argument qui séduit. Tolère les sols lourds et humides. Aucune taille nécessaire, aucune maladie connue.",
 "bdm":"Second rideau","dens":0.4,"esp":1.5},

{"lat":"Betula verrucosa","fr":"Bouleau verruqueux","type":"Arbre","h":20.0,"l":8.0,
 "expo":"Plein soleil","sol":"Drainé, léger, acide à neutre, pauvre toléré","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert clair, jaune d'or en automne","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Vert (chatons)",
 "plant":"Automne","popt":"Novembre à février","ent":"Faible",
 "style":"Sujet isolé, bosquet, jardin contemporain, écorce décorative en hiver",
 "asso":"Graminées, fougères, bulbes de printemps, Hydrangea, Hedera",
 "cons":"Écorce blanche remarquable, surtout planté en bosquet de trois sujets. Croissance rapide mais durée de vie courte, 50 à 60 ans. Racines traçantes et superficielles à éloigner des constructions et des canalisations. Souffre des étés secs en sol léger. Pollen fortement allergisant : à signaler au client.",
 "bdm":"Second rideau","dens":0.02,"esp":6.0},

{"lat":"Campanula lactiflora","fr":"Campanule à fleurs de lait","type":"Vivace","h":1.2,"l":0.6,
 "expo":"Soleil à mi-ombre","sol":"Profond, frais, humifère","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc","m1":6,"m2":8,"flo":"Juin à août","cflo":"Bleu lavande, blanc, rose",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Massif de vivaces, jardin de curé, jardin romantique, arrière-plan",
 "asso":"Rosiers, Geranium vivace, Alchemilla, Astrantia, Nepeta",
 "cons":"Grandes panicules bleutées qui apportent de la hauteur sans lourdeur. Peut nécessiter un tuteurage discret en situation venteuse. Rabattre après la première floraison pour une remontée. Se ressème doucement. Apprécie un sol qui ne sèche pas en été.",
 "bdm":"Second rideau","dens":3,"esp":0.6},

{"lat":"Carex buchananii","fr":"Laîche de Buchanan","type":"Graminée","h":0.6,"l":0.4,
 "expo":"Plein soleil","sol":"Drainé, tout type","hum":"Sec à frais","rust":-15,
 "feu":"Persistant","cfeu":"Bronze cuivré","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Brun discret",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif contemporain, potée, jardin de gravier, contraste de couleur",
 "asso":"Festuca glauca, Sedum, Heuchera pourpre, Euphorbia, Phormium",
 "cons":"Couleur bronze permanente, unique parmi les graminées, qui fait contraste avec les feuillages verts ou argentés. Les clients la croient souvent morte : préciser que cette teinte est naturelle et présente toute l'année. Peigner à la main au printemps plutôt que rabattre. Drainage impératif en hiver.",
 "bdm":"Front de mer","dens":5,"esp":0.4},

{"lat":"Carex pendula","fr":"Laîche pendante","type":"Graminée","h":1.4,"l":1.0,
 "expo":"Mi-ombre à ombre","sol":"Tout type, humifère, argileux toléré","hum":"Frais à humide","rust":-25,
 "feu":"Persistant","cfeu":"Vert franc","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Brun vert, épis pendants",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Sous-bois, bord de bassin, zone humide ombragée, jardin naturaliste",
 "asso":"Fougères, Hosta, Persicaria, Lythrum, Astrantia",
 "cons":"Espèce indigène, l'une des rares graminées à prospérer à l'ombre humide, là où beaucoup échouent. Longs épis retombants très graphiques. Se ressème abondamment en milieu favorable : à surveiller, ou à réserver aux endroits où cette spontanéité est bienvenue.",
 "bdm":"Second rideau","dens":2,"esp":0.7},

{"lat":"Castanea sativa","fr":"Châtaignier","type":"Arbre / Fruitier","h":20.0,"l":15.0,
 "expo":"Plein soleil","sol":"Drainé, acide, profond, léger","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc, jaune ocre en automne","m1":6,"m2":7,"flo":"Juin à juillet","cflo":"Jaune crème (chatons)",
 "plant":"Automne","popt":"Novembre à février","ent":"Faible",
 "style":"Verger, grand jardin, arbre d'ombrage, jardin nourricier",
 "asso":"Prairie, haie champêtre, sous-bois de fougères",
 "cons":"Arbre de grand développement, à réserver aux terrains vastes : 20 m de haut et autant d'envergure. Redoute absolument le calcaire, il faut un sol acide, ce qui limite fortement son emploi en Loire-Atlantique selon les secteurs. Prévoir deux variétés pour la fructification. Surveiller le chancre et l'encre.",
 "bdm":"Déconseillé en bord de mer","dens":0.01,"esp":10.0},

{"lat":"Centranthus ruber","fr":"Valériane rouge","type":"Vivace","h":0.8,"l":0.6,
 "expo":"Plein soleil","sol":"Drainé, calcaire, pauvre, caillouteux","hum":"Sec","rust":-20,
 "feu":"Semi-persistant","cfeu":"Vert bleuté","m1":5,"m2":9,"flo":"Mai à septembre","cflo":"Rouge carminé, rose, blanc",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Muret, rocaille, talus sec, jardin méditerranéen, jardin de gravier",
 "asso":"Lavandula, Stipa, Euphorbia, Erigeron, Santolina",
 "cons":"Pousse dans les fissures de murs sans une once de terre : la plante idéale pour habiller un vieux mur ou un enrochement. Floraison très longue si on rabat après la première vague. Se ressème abondamment, ce qui fait son charme dans un jardin naturel mais demande une régulation ailleurs. Aucun arrosage.",
 "bdm":"Front de mer","dens":3,"esp":0.6},

{"lat":"Cistus corbariensis","fr":"Ciste de Corbières","type":"Arbuste","h":0.8,"l":1.2,
 "expo":"Plein soleil","sol":"Drainé, sec, pauvre, calcaire toléré","hum":"Sec","rust":-15,
 "feu":"Persistant","cfeu":"Vert franc, pourpré en hiver","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Blanc à cœur jaune",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Talus sec, jardin méditerranéen, couvre-sol arbustif, bord de mer",
 "asso":"Lavandula, Rosmarinus, Phlomis, Santolina, graminées sèches",
 "cons":"Le plus rustique des cistes et le plus tolérant au calcaire, ce qui en fait le meilleur choix pour un talus sec en Loire-Atlantique. Port étalé qui couvre bien le sol. Feuillage prenant des teintes pourprées en hiver. Ne jamais tailler sur le vieux bois, il ne repart pas.",
 "bdm":"Front de mer","dens":1,"esp":1.0},

{"lat":"Cornus sanguinea","fr":"Cornouiller sanguin","type":"Arbuste","h":3.0,"l":2.5,
 "expo":"Soleil à mi-ombre","sol":"Tout type, calcaire toléré, argileux toléré","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert, rouge pourpre en automne","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Blanc crème",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie champêtre, jardin de biodiversité, talus, bosquet, massif d'hiver",
 "asso":"Viburnum opulus, Corylus, Crataegus, Sambucus, Prunus spinosa",
 "cons":"Espèce indigène incontournable de la haie champêtre : fleurs mellifères, baies noires pour les oiseaux, feuillage d'automne pourpre et bois rouge en hiver. Pousse absolument partout, y compris en sol lourd et calcaire. Drageonne et s'étale : lui donner de l'espace ou recéper régulièrement.",
 "bdm":"Second rideau","dens":0.3,"esp":1.8},

{"lat":"Cotinus coggygria","fr":"Arbre à perruque","type":"Arbuste","h":4.0,"l":3.5,
 "expo":"Plein soleil","sol":"Drainé, calcaire toléré, pauvre","hum":"Sec à frais","rust":-20,
 "feu":"Caduc","cfeu":"Pourpre foncé ou vert, écarlate en automne","m1":6,"m2":7,"flo":"Juin à juillet","cflo":"Rose fumé vaporeux",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Sujet isolé, massif de contraste, jardin sec, fond de massif",
 "asso":"Graminées, Perovskia, Sedum, Verbena bonariensis, vivaces claires",
 "cons":"Les inflorescences vaporeuses donnent l'effet de fumée rose qui vaut son nom, et le feuillage pourpre s'embrase en automne. Sol pauvre et sec impératif : en terre riche il fait du bois et perd sa couleur. Deux conduites possibles : laissé libre il fleurit, recépé chaque année il donne un feuillage plus grand mais aucune fleur.",
 "bdm":"Second rideau","dens":0.2,"esp":2.5},

{"lat":"Echinacea","fr":"Échinacée","type":"Vivace","h":0.9,"l":0.5,
 "expo":"Plein soleil","sol":"Drainé, profond, fertile","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert foncé","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Rose pourpré, blanc, orange, jaune",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif naturaliste, prairie fleurie, jardin de vivaces, massif d'été",
 "asso":"Rudbeckia, graminées, Perovskia, Sedum, Salvia nemorosa, Achillea",
 "cons":"Pilier du jardin naturaliste, très mellifère et attractive pour les papillons. Conserver les cônes fanés en hiver : ils sont décoratifs et nourrissent les oiseaux. Redoute l'humidité hivernale en sol lourd, qui est la cause d'échec la plus fréquente. Les cultivars orange et jaune sont souvent moins pérennes que les roses.",
 "bdm":"Second rideau","dens":4,"esp":0.5},

{"lat":"Euonymus japonicus","fr":"Fusain du Japon","type":"Arbuste","h":2.5,"l":1.5,
 "expo":"Soleil à mi-ombre","sol":"Tout type, drainé, calcaire toléré","hum":"Frais","rust":-15,
 "feu":"Persistant","cfeu":"Vert foncé brillant ou panaché de jaune","m1":6,"m2":7,"flo":"Juin à juillet","cflo":"Vert crème discret",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Moyen",
 "style":"Haie taillée, topiaire, bord de mer, potée, massif structuré",
 "asso":"Pittosporum, Elaeagnus, Griselinia, Viburnum tinus, Phormium",
 "cons":"Excellente tenue aux embruns et à la pollution, ce qui explique sa présence dans les aménagements côtiers et urbains. Se taille en haie nette ou en boule. Les formes panachées éclairent bien mais sont plus sensibles au froid. Surveiller l'oïdium en situation confinée.",
 "bdm":"Front de mer","dens":0.7,"esp":0.6},

{"lat":"Euphorbia amygdaloides","fr":"Euphorbe des bois","type":"Vivace / Couvre-sol","h":0.5,"l":0.5,
 "expo":"Mi-ombre à ombre","sol":"Tout type, humifère, drainé","hum":"Frais","rust":-20,
 "feu":"Persistant","cfeu":"Vert foncé ou pourpre (var. Purpurea)","m1":4,"m2":6,"flo":"Avril à juin","cflo":"Vert chartreuse",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Sous-bois, massif d'ombre, pied de haie, jardin naturaliste",
 "asso":"Fougères, Hosta, Geranium macrorrhizum, Epimedium, Carex",
 "cons":"L'une des rares euphorbes vraiment adaptées à l'ombre, contrairement à characias qui veut le soleil. Les bractées vert acide éclairent un massif sombre au printemps. La variété Purpurea offre un feuillage pourpre remarquable. Latex irritant : gants obligatoires à la taille, à signaler s'il y a des enfants.",
 "bdm":"Second rideau","dens":4,"esp":0.5},

{"lat":"Foeniculum vulgare","fr":"Fenouil bronze","type":"Vivace / Aromatique","h":1.8,"l":0.6,
 "expo":"Plein soleil","sol":"Drainé, calcaire toléré, pauvre","hum":"Sec","rust":-20,
 "feu":"Caduc","cfeu":"Bronze pourpré, très finement découpé","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Jaune, en ombelles",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif naturaliste, jardin d'aromatiques, effet vaporeux, prairie fleurie",
 "asso":"Verbena bonariensis, graminées, Echinacea, Salvia, Gaura",
 "cons":"Feuillage en nuage bronze d'une finesse remarquable, qui allège un massif comme aucune autre plante. Très mellifère et plante hôte du machaon, dont on trouve les chenilles rayées sur les tiges. Se ressème beaucoup : couper les ombelles avant maturité si on veut le contenir. Feuillage et graines comestibles.",
 "bdm":"Front de mer","dens":2,"esp":0.7},

{"lat":"Hibiscus moscheutos","fr":"Hibiscus des marais","type":"Vivace","h":1.5,"l":1.0,
 "expo":"Plein soleil","sol":"Profond, humifère, riche","hum":"Frais à humide","rust":-20,
 "feu":"Caduc","cfeu":"Vert franc","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Rouge, rose, blanc",
 "plant":"Printemps","popt":"Avril à mai","ent":"Moyen",
 "style":"Bord de bassin, massif estival, zone fraîche, jardin exotique",
 "asso":"Miscanthus, Persicaria, Lythrum, Canna, graminées",
 "cons":"Fleurs immenses, jusqu'à 25 cm de diamètre, qui produisent un effet spectaculaire. Contrairement à l'Hibiscus syriacus, c'est une vivace herbacée qui disparaît totalement en hiver et redémarre très tard, souvent en mai : ne pas la croire morte et marquer son emplacement. Exige de la fraîcheur au sol tout l'été.",
 "bdm":"Second rideau","dens":1,"esp":1.0},

{"lat":"Hydrangea quercifolia","fr":"Hortensia à feuilles de chêne","type":"Arbuste","h":2.0,"l":2.0,
 "expo":"Mi-ombre","sol":"Humifère, drainé, acide à neutre","hum":"Frais","rust":-20,
 "feu":"Caduc","cfeu":"Vert, pourpre écarlate en automne","m1":6,"m2":8,"flo":"Juin à août","cflo":"Blanc virant rose",
 "plant":"Automne à printemps","popt":"Octobre ou mars","ent":"Faible",
 "style":"Massif d'ombre, sous-bois clair, jardin de terre de bruyère, massif d'automne",
 "asso":"Azalea, Acer palmatum, Hosta, fougères, Carex",
 "cons":"Le plus intéressant des hortensias sur l'année entière : grandes feuilles lobées originales, panicules blanches en été, feuillage écarlate en automne et écorce exfoliante en hiver. Fleurit sur le bois de l'année précédente, donc taille légère uniquement. Supporte mieux la sécheresse que le macrophylla.",
 "bdm":"Second rideau","dens":0.4,"esp":1.5},

{"lat":"Imperata cylindrica","fr":"Herbe sanglante du Japon","type":"Graminée","h":0.5,"l":0.4,
 "expo":"Soleil à mi-ombre","sol":"Humifère, drainé, frais","hum":"Frais","rust":-15,
 "feu":"Caduc","cfeu":"Vert à pointe rouge sang, s'intensifiant en été","m1":0,"m2":0,"flo":"Rarement fleurie","cflo":"—",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Massif contemporain, potée, premier plan à contre-jour, jardin japonais",
 "asso":"Ophiopogon noir, Heuchera pourpre, Sedum, Carex, Hakonechloa",
 "cons":"Le rouge translucide du feuillage prend toute sa valeur à contre-jour : à placer en fonction du soleil couchant, sinon l'effet est perdu. Croissance lente et touffe modeste, planter en groupe de cinq ou plus. Exige de la fraîcheur au sol en été. Supprimer toute pousse revenant au vert pur.",
 "bdm":"Second rideau","dens":6,"esp":0.4},

{"lat":"Kerria japonica","fr":"Corète du Japon","type":"Arbuste","h":2.0,"l":2.0,
 "expo":"Mi-ombre à ombre","sol":"Tout type, humifère, frais","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert clair, tiges vertes en hiver","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Jaune d'or",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Massif d'ombre, sous-bois, jardin de curé, façade nord, haie libre",
 "asso":"Hosta, fougères, Hydrangea, Vinca, Carex",
 "cons":"L'un des rares arbustes à fleurir généreusement à l'ombre, ce qui en fait une solution précieuse pour une façade nord. Les tiges restent vertes en hiver, apportant de la couleur à la mauvaise saison. Drageonne franchement : lui donner de l'espace. Tailler après la floraison en supprimant les vieilles tiges à la base.",
 "bdm":"Second rideau","dens":0.4,"esp":1.5},

{"lat":"Ligustrum japonicum","fr":"Troène du Japon","type":"Arbuste","h":3.0,"l":2.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, drainé, calcaire toléré","hum":"Frais","rust":-15,
 "feu":"Persistant","cfeu":"Vert foncé brillant, coriace","m1":6,"m2":7,"flo":"Juin à juillet","cflo":"Blanc crème",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie persistante, écran, topiaire, sujet isolé, jardin méditerranéen",
 "asso":"Elaeagnus, Photinia, Viburnum tinus, Pittosporum, Phillyrea",
 "cons":"Vrai persistant, contrairement au troène de Californie qui se dégarnit l'hiver : c'est le bon choix quand le client veut un écran fiable toute l'année. Feuillage épais et brillant, plus élégant. Croissance plus lente, donc moins de tailles. Bonne tolérance au calcaire et à la sécheresse une fois installé.",
 "bdm":"Front de mer","dens":0.6,"esp":0.8},

{"lat":"Luzula nivea","fr":"Luzule blanche","type":"Graminée","h":0.5,"l":0.4,
 "expo":"Mi-ombre à ombre","sol":"Humifère, drainé, acide à neutre","hum":"Frais","rust":-25,
 "feu":"Persistant","cfeu":"Vert franc, marges velues","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Blanc crème",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Sous-bois, couvre-sol d'ombre, bordure ombragée, jardin naturaliste",
 "asso":"Fougères, Hosta, Epimedium, Geranium macrorrhizum, Carex",
 "cons":"Une des rares graminées à floraison réellement visible à l'ombre, en petites houppes blanches. Persistante, elle structure un sous-bois toute l'année. Forme progressivement un tapis dense qui limite les adventices. Supporte la sécheresse d'été sous les arbres une fois installée.",
 "bdm":"Second rideau","dens":6,"esp":0.4},

{"lat":"Malus coccinela","fr":"Pommier d'ornement","type":"Arbre","h":4.0,"l":3.5,
 "expo":"Plein soleil","sol":"Tout type, profond, calcaire toléré","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert pourpré, orangé en automne","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Rose vif à rouge",
 "plant":"Automne","popt":"Novembre à février","ent":"Faible",
 "style":"Sujet isolé, petit jardin, alignement, jardin de biodiversité",
 "asso":"Bulbes de printemps, prairie fleurie, graminées, vivaces basses",
 "cons":"Le bon arbre pour un petit jardin : floraison abondante au printemps, puis petites pommes décoratives qui tiennent jusqu'en hiver et nourrissent les oiseaux. Excellent pollinisateur pour un verger voisin. Aucune taille nécessaire. Surveiller la tavelure sur les cultivars anciens ; les récents y sont résistants.",
 "bdm":"Second rideau","dens":0.06,"esp":4.0},

{"lat":"Malva moschata","fr":"Mauve musquée","type":"Vivace","h":0.8,"l":0.5,
 "expo":"Plein soleil","sol":"Drainé, tout type, pauvre toléré","hum":"Sec à frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert finement découpé","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Rose tendre, blanc",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Prairie fleurie, jardin champêtre, massif naturaliste, bordure",
 "asso":"Achillea, Centranthus, graminées, Salvia nemorosa, Knautia",
 "cons":"Espèce indigène de nos bords de chemins, parfaite pour un aménagement champêtre ou une prairie fleurie. Floraison longue et très mellifère. Se ressème spontanément et se déplace, ce qui donne un aspect naturel mais demande de l'accepter. Durée de vie courte, compensée par le semis.",
 "bdm":"Front de mer","dens":4,"esp":0.5},

{"lat":"Mentha spicata","fr":"Menthe verte","type":"Vivace / Aromatique","h":0.6,"l":0.8,
 "expo":"Soleil à mi-ombre","sol":"Tout type, humifère, riche","hum":"Frais à humide","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc aromatique","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Mauve pâle",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin d'aromatiques, potager, bord de bassin, potée",
 "asso":"Melissa, Origanum, Foeniculum, Salvia officinalis",
 "cons":"Extrêmement traçante par rhizomes : plantée en pleine terre elle envahit tout le massif en deux saisons. La planter systématiquement en pot enterré ou en bac, c'est la seule méthode fiable. Apprécie un sol frais et une mi-ombre. Rabattre en été pour relancer un feuillage tendre.",
 "bdm":"Second rideau","dens":5,"esp":0.45},

{"lat":"Origanum vulgare","fr":"Origan","type":"Vivace / Aromatique","h":0.5,"l":0.5,
 "expo":"Plein soleil","sol":"Drainé, calcaire, pauvre, caillouteux","hum":"Sec","rust":-25,
 "feu":"Semi-persistant","cfeu":"Vert franc ou doré, aromatique","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Rose mauve",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin d'aromatiques, rocaille, bordure, jardin sec, prairie fleurie",
 "asso":"Thymus, Salvia officinalis, Lavandula, Achillea, Santolina",
 "cons":"L'une des plantes les plus mellifères du catalogue : en floraison, la touffe est couverte d'abeilles et de papillons. Double usage, culinaire et ornemental. Le cultivar doré éclaire une bordure mais brûle au soleil brûlant. Rabattre en fin d'hiver. Exige un sol vraiment drainant.",
 "bdm":"Front de mer","dens":5,"esp":0.45},

{"lat":"Osmanthus burkwoodii","fr":"Osmanthe de Burkwood","type":"Arbuste","h":2.5,"l":2.0,
 "expo":"Soleil à mi-ombre","sol":"Drainé, humifère, calcaire toléré","hum":"Frais","rust":-18,
 "feu":"Persistant","cfeu":"Vert foncé brillant","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Blanc, très parfumé",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie persistante, topiaire, près d'un passage pour le parfum, massif structuré",
 "asso":"Viburnum tinus, Elaeagnus, Photinia, Prunus lusitanica, Choisya",
 "cons":"Parfum de fleur d'oranger d'une puissance remarquable, perceptible à plusieurs mètres : c'est l'argument, il faut le placer près d'une entrée ou d'une terrasse. Port dense et croissance lente, très facile à maintenir en volume. Se taille bien en boule. Une des meilleures alternatives au buis pour un sujet structurant.",
 "bdm":"Second rideau","dens":0.6,"esp":0.8},

{"lat":"Phormium tenax","fr":"Lin de Nouvelle-Zélande","type":"Vivace / Arbuste","h":2.0,"l":1.5,
 "expo":"Plein soleil","sol":"Drainé, profond, tout type","hum":"Frais","rust":-10,
 "feu":"Persistant","cfeu":"Vert, pourpre, bronze ou panaché de rose et crème","m1":6,"m2":7,"flo":"Juin à juillet","cflo":"Rouge brique",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Jardin contemporain, bord de mer, sujet architectural, potée, jardin exotique",
 "asso":"Agapanthus, graminées, Pittosporum, Griselinia, Yucca",
 "cons":"Silhouette en gerbe très architecturale, présente toute l'année, qui structure un massif comme peu de plantes. Excellente tenue aux embruns, d'où sa présence sur tout le littoral atlantique. Rusticité limitée : les cultivars pourpres et panachés sont plus fragiles que le type vert. Prévoir sa taille adulte, souvent sous-estimée.",
 "bdm":"Front de mer","dens":0.6,"esp":1.3},

{"lat":"Ribes rubrum","fr":"Groseillier à grappes","type":"Fruitier","h":1.5,"l":1.2,
 "expo":"Soleil à mi-ombre","sol":"Humifère, frais, profond","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Vert jaune discret",
 "plant":"Automne","popt":"Novembre à mars","ent":"Moyen",
 "style":"Jardin nourricier, potager, haie fruitière, massif mi-ombragé",
 "asso":"Rubus, Vaccinium, plantes mellifères, aromatiques",
 "cons":"L'un des rares fruitiers productifs à mi-ombre, ce qui permet de valoriser une exposition difficile. Fructifie sur le bois de deux et trois ans : supprimer chaque hiver les branches de plus de quatre ans pour renouveler. Autofertile, un seul pied suffit. Paillage indispensable, il craint la sécheresse.",
 "bdm":"Second rideau","dens":0.8,"esp":1.2},

{"lat":"Salix purpurea","fr":"Saule pourpre","type":"Arbuste","h":3.0,"l":2.5,
 "expo":"Plein soleil","sol":"Tout type, argileux toléré","hum":"Frais à humide","rust":-30,
 "feu":"Caduc","cfeu":"Vert bleuté, rameaux pourprés","m1":3,"m2":4,"flo":"Mars à avril","cflo":"Gris argenté (chatons)",
 "plant":"Automne à printemps","popt":"Novembre à mars","ent":"Moyen",
 "style":"Berge, noue, zone humide, haie champêtre, fascine et génie végétal",
 "asso":"Cornus alba, Viburnum opulus, Lythrum, Molinia, Juncus",
 "cons":"Espèce indigène de berge, capable de vivre les pieds dans l'eau. Utilisée en génie végétal pour stabiliser un talus ou une berge : les boutures reprennent presque systématiquement, plantées à même le sol en hiver. Chatons très précoces, ressource majeure pour les abeilles en sortie d'hiver. Recéper tous les 2 à 3 ans.",
 "bdm":"Second rideau","dens":0.3,"esp":1.8},

{"lat":"Santolina chamaecyparissus","fr":"Santoline","type":"Arbuste","h":0.5,"l":0.7,
 "expo":"Plein soleil","sol":"Drainé, sec, calcaire, pauvre, caillouteux","hum":"Sec","rust":-15,
 "feu":"Persistant","cfeu":"Argenté, très découpé","m1":6,"m2":8,"flo":"Juin à août","cflo":"Jaune bouton",
 "plant":"Printemps","popt":"Mars à mai","ent":"Moyen",
 "style":"Bordure taillée, jardin de curé, jardin sec, rocaille, parterre géométrique",
 "asso":"Lavandula, Rosmarinus, Cistus, Thymus, Phlomis",
 "cons":"Feuillage argenté persistant qui se taille en boule ou en bordure basse, une alternative méditerranéenne au buis. Taille annuelle obligatoire juste après la floraison, sur le bois vert uniquement : taillée trop court elle ne repart pas. Certains suppriment les fleurs jaunes, qui jurent avec l'argenté. Se dégarnit après 5 ou 6 ans.",
 "bdm":"Front de mer","dens":2.5,"esp":0.6},

{"lat":"Scabiosa columbaria","fr":"Scabieuse colombaire","type":"Vivace","h":0.6,"l":0.4,
 "expo":"Plein soleil","sol":"Drainé, calcaire, pauvre","hum":"Sec","rust":-25,
 "feu":"Semi-persistant","cfeu":"Vert grisé","m1":5,"m2":10,"flo":"Mai à octobre","cflo":"Bleu lavande, rose",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Prairie fleurie, massif naturaliste, bordure, jardin sec",
 "asso":"Achillea, Salvia nemorosa, graminées, Gaura, Knautia, Nepeta",
 "cons":"Floraison exceptionnellement longue, de mai jusqu'aux gelées si on supprime régulièrement les fleurs fanées. Espèce indigène des pelouses calcaires, très attractive pour les papillons. Redoute l'humidité hivernale en sol lourd. Rabattre en fin d'hiver seulement.",
 "bdm":"Front de mer","dens":5,"esp":0.4},

{"lat":"Sedum acre","fr":"Orpin âcre","type":"Couvre-sol","h":0.1,"l":0.3,
 "expo":"Plein soleil","sol":"Drainé, sec, très pauvre, caillouteux","hum":"Sec","rust":-30,
 "feu":"Persistant","cfeu":"Vert clair charnu","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Jaune vif",
 "plant":"Printemps","popt":"Mars à juin","ent":"Faible",
 "style":"Toiture végétalisée, dallage, muret, rocaille, gravier, entre-pavés",
 "asso":"Delosperma, Thymus serpyllum, Sempervivum, Festuca glauca",
 "cons":"Pousse littéralement sur rien : quelques centimètres de substrat pauvre lui suffisent, d'où son usage systématique en toiture végétalisée. Supporte le piétinement léger et la sécheresse totale. Colonise rapidement par fragmentation, un simple morceau posé au sol s'enracine. Ne jamais amender ni arroser.",
 "bdm":"Front de mer","dens":9,"esp":0.3},

{"lat":"Spiraea nipponica","fr":"Spirée du Japon blanche","type":"Arbuste","h":2.0,"l":2.0,
 "expo":"Plein soleil","sol":"Tout type, drainé, calcaire toléré","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert bleuté","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Blanc pur",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie libre fleurie, massif de printemps, jardin blanc, aménagement collectif",
 "asso":"Deutzia, Philadelphus, Weigelia, Syringa, graminées",
 "cons":"Rameaux arqués entièrement couverts de fleurs blanches au printemps, un effet de cascade très différent des spirées d'été à fleurs roses. Attention : celle-ci fleurit sur le bois de l'année précédente, la taille se fait donc après la floraison, à l'inverse de Spiraea japonica. Confondre les deux, c'est perdre la floraison.",
 "bdm":"Second rideau","dens":0.4,"esp":1.5},

{"lat":"Stachys byzanthina","fr":"Oreille d'ours","type":"Couvre-sol","h":0.4,"l":0.6,
 "expo":"Plein soleil","sol":"Drainé, sec, pauvre, caillouteux","hum":"Sec","rust":-25,
 "feu":"Persistant","cfeu":"Argenté, feutré et duveteux","m1":6,"m2":8,"flo":"Juin à août","cflo":"Rose mauve",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Bordure, rocaille, jardin sec, jardin tactile, contraste de feuillage",
 "asso":"Lavandula, Nepeta, Salvia nemorosa, Sedum, graminées",
 "cons":"Feuillage argenté et velouté irrésistible au toucher, très apprécié des enfants : un bon choix en bordure d'allée. Redoute l'humidité, qui fait pourrir les feuilles feutrées : jamais d'arrosage sur le feuillage, et retirer les feuilles abîmées après l'hiver. Certains suppriment les hampes florales pour ne garder que le tapis argenté.",
 "bdm":"Front de mer","dens":5,"esp":0.45},

{"lat":"Stipa tenuifolia","fr":"Cheveux d'ange","type":"Graminée","h":0.6,"l":0.4,
 "expo":"Plein soleil","sol":"Drainé, sec, pauvre, caillouteux","hum":"Sec","rust":-15,
 "feu":"Semi-persistant","cfeu":"Vert clair, blond doré en été","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Beige argenté",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin sec, massif contemporain, bordure souple, jardin de gravier, potée",
 "asso":"Lavandula, Perovskia, Gaura, Sedum, Salvia, Verbena bonariensis",
 "cons":"Le mouvement au moindre souffle de vent est tout son intérêt : à placer là où on la voit bouger, en bordure d'allée ou contre le ciel. Blondit en été, ce qui fait sa beauté. Peigner à la main au printemps plutôt que rabattre. Se ressème abondamment, parfois trop. Drainage impératif, elle pourrit en sol lourd.",
 "bdm":"Front de mer","dens":6,"esp":0.4},

{"lat":"Symphoricarpos doorenbosii","fr":"Symphorine","type":"Arbuste","h":1.5,"l":1.5,
 "expo":"Soleil à ombre","sol":"Tout type, calcaire toléré, pauvre toléré","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert bleuté","m1":6,"m2":8,"flo":"Juin à août","cflo":"Rose discret",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie libre, talus, massif d'ombre, aménagement collectif, jardin de biodiversité",
 "asso":"Cornus sanguinea, Viburnum, Cotoneaster, graminées",
 "cons":"Cultivée pour ses grosses baies blanches ou rosées qui tiennent de septembre à Noël, bien après la chute des feuilles. Pousse absolument partout, y compris en ombre sèche et en sol ingrat, d'où son emploi massif en collectif. Drageonne et forme des colonies : lui donner de l'espace ou la contenir.",
 "bdm":"Second rideau","dens":0.5,"esp":1.4},

{"lat":"Tamarix africana","fr":"Tamaris de printemps","type":"Arbuste","h":4.0,"l":3.0,
 "expo":"Plein soleil","sol":"Drainé, sableux, pauvre, salin toléré","hum":"Sec","rust":-18,
 "feu":"Caduc","cfeu":"Vert bleuté, très fin","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Rose pâle",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Moyen",
 "style":"Bord de mer, haie brise-vent, jardin de sable, sujet isolé",
 "asso":"Elaeagnus, Phormium, Agapanthus, graminées, Cistus",
 "cons":"La plante emblématique du front de mer : elle supporte le sel, le sable et le vent comme aucune autre, et sert de premier rideau pour protéger le reste du jardin. Silhouette en nuage rose au printemps. Attention à la période de taille : celui-ci fleurit sur le bois de l'année précédente, on taille donc après floraison, contrairement aux tamaris d'été.",
 "bdm":"Front de mer","dens":0.3,"esp":1.8},

{"lat":"Taxus baccata","fr":"If commun","type":"Conifère","h":10.0,"l":5.0,
 "expo":"Soleil à ombre","sol":"Drainé, calcaire toléré, profond","hum":"Frais","rust":-25,
 "feu":"Persistant","cfeu":"Vert très foncé","m1":3,"m2":4,"flo":"Mars à avril","cflo":"Non ornementale",
 "plant":"Automne à printemps","popt":"Septembre à novembre ou mars","ent":"Moyen",
 "style":"Haie taillée, topiaire, jardin structuré, écran, fond de massif",
 "asso":"Fond sombre pour rosiers, graminées, vivaces claires, Hydrangea",
 "cons":"Le meilleur conifère de haie, et le seul qui reparte sur le vieux bois : une haie dégarnie peut être rabattue sévèrement et se refaire, ce qu'aucun cyprès ne permet. Tolère l'ombre. Croissance lente, à intégrer au budget. Toutes les parties sauf la pulpe rouge sont toxiques, y compris pour les chevaux : à signaler.",
 "bdm":"Second rideau","dens":0.5,"esp":0.6},

{"lat":"Thuya plicata","fr":"Thuya géant","type":"Conifère","h":12.0,"l":4.0,
 "expo":"Soleil à mi-ombre","sol":"Profond, frais, drainé","hum":"Frais","rust":-25,
 "feu":"Persistant","cfeu":"Vert foncé brillant","m1":0,"m2":0,"flo":"Non ornementale","cflo":"—",
 "plant":"Automne à printemps","popt":"Septembre à novembre ou mars","ent":"Moyen",
 "style":"Haie brise-vue, écran, fond de propriété",
 "asso":"À intégrer dans une haie mixte plutôt qu'en monospécifique",
 "cons":"Plus résistant au dessèchement et aux maladies que le thuya occidental, et au feuillage plus brillant. Ne repart pas sur le vieux bois : ne jamais tailler trop court. Deux tailles annuelles. Comme tous les conifères de haie, il appauvrit le sol à son pied et n'offre rien à la biodiversité : proposer systématiquement une haie mixte en alternative.",
 "bdm":"Second rideau","dens":0.5,"esp":0.8},

{"lat":"Thymus serpyllum","fr":"Serpolet","type":"Couvre-sol / Aromatique","h":0.1,"l":0.4,
 "expo":"Plein soleil","sol":"Drainé, sec, pauvre, caillouteux, calcaire","hum":"Sec","rust":-25,
 "feu":"Persistant","cfeu":"Vert grisé ou doré","m1":5,"m2":8,"flo":"Mai à août","cflo":"Rose mauve, blanc",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Entre-pavés, dallage, toiture végétalisée, rocaille, tapis fleuri praticable",
 "asso":"Sedum, Sagina, Delosperma, Festuca glauca, Armeria",
 "cons":"Contrairement au thym commun qui forme un sous-arbrisseau, le serpolet fait un tapis ras de quelques centimètres, praticable : c'est la solution pour les joints de dallage et les allées peu circulées. Supporte un piétinement modéré et libère son parfum quand on marche dessus. Très mellifère. Drainage impératif.",
 "bdm":"Front de mer","dens":9,"esp":0.3},

{"lat":"Veronica spicata","fr":"Véronique en épis","type":"Vivace","h":0.5,"l":0.4,
 "expo":"Plein soleil","sol":"Drainé, calcaire toléré, pauvre","hum":"Sec à frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc","m1":6,"m2":8,"flo":"Juin à août","cflo":"Bleu violacé, rose, blanc",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Bordure, rocaille, massif naturaliste, jardin sec, prairie fleurie",
 "asso":"Salvia nemorosa, Achillea, Sedum, graminées, Nepeta",
 "cons":"Épis dressés très verticaux qui rythment un massif bas, dans le même registre que la sauge des bois mais plus compacte. Rabattre après la première floraison pour une remontée. Très mellifère. Redoute l'humidité hivernale en sol lourd, comme la plupart des vivaces de rocaille.",
 "bdm":"Front de mer","dens":6,"esp":0.4},

{"lat":"Viburnum bodnantense","fr":"Viorne de Bodnant","type":"Arbuste","h":3.0,"l":2.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, humifère, calcaire toléré","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert bronzé, rouge en automne","m1":11,"m2":3,"flo":"Novembre à mars","cflo":"Rose tendre, très parfumé",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Massif d'hiver, près d'un passage pour le parfum, haie libre, jardin de curé",
 "asso":"Cornus alba, Hamamelis, Sarcococca, graminées, bulbes de printemps",
 "cons":"Fleurit en plein hiver sur bois nu, de novembre à mars, avec un parfum puissant : c'est la plante qui répond au client qui trouve son jardin triste en janvier. Les fleurs résistent au gel et se renouvellent après chaque coup de froid. Silhouette banale le reste de l'année, à placer en second plan.",
 "bdm":"Second rideau","dens":0.4,"esp":1.5},

{"lat":"Bergenia cordifolia","fr":"Bergénia","type":"Couvre-sol / Vivace","h":0.4,"l":0.5,
 "expo":"Soleil à ombre","sol":"Tout type, humifère","hum":"Frais","rust":-30,
 "feu":"Persistant","cfeu":"Vert foncé coriace, pourpre en hiver","m1":3,"m2":5,"flo":"Mars à mai","cflo":"Rose vif, blanc",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Bordure d'ombre, pied d'arbre, massif structuré, façade nord, jardin contemporain",
 "asso":"Hosta, fougères, Carex, Heuchera, Geranium macrorrhizum",
 "cons":"Grandes feuilles épaisses et persistantes qui structurent un massif toute l'année et rougissent en hiver. Floraison précoce, dès mars, quand rien d'autre ne fleurit. Tolère à peu près tout : soleil ou ombre, sec ou frais, sol ingrat. Une des vivaces les plus fiables du catalogue. Retirer les feuilles abîmées au printemps.",
 "bdm":"Front de mer","dens":4,"esp":0.5},

{"lat":"Astrantia major","fr":"Grande astrance","type":"Vivace","h":0.7,"l":0.5,
 "expo":"Mi-ombre","sol":"Profond, humifère, frais","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc découpé","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Blanc rosé, rouge pourpre",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Massif d'ombre, jardin romantique, sous-bois clair, jardin de fleurs à couper",
 "asso":"Hosta, fougères, Geranium vivace, Anemone du Japon, Deschampsia",
 "cons":"Fleurs en collerettes d'une finesse remarquable, presque des étoiles de papier, excellentes en bouquet frais ou séché. Exige un sol qui reste frais tout l'été : c'est sa seule vraie condition, elle dépérit en terrain sec. Rabattre après la première floraison pour une remontée. Se ressème doucement.",
 "bdm":"Second rideau","dens":5,"esp":0.4},

{"lat":"Delosperma cooperi","fr":"Pourpier vivace","type":"Couvre-sol","h":0.1,"l":0.4,
 "expo":"Plein soleil","sol":"Drainé, sec, sableux, très pauvre","hum":"Sec","rust":-15,
 "feu":"Persistant","cfeu":"Vert charnu","m1":6,"m2":10,"flo":"Juin à octobre","cflo":"Magenta, jaune, orange",
 "plant":"Printemps","popt":"Avril à juin","ent":"Faible",
 "style":"Rocaille, toiture végétalisée, muret, gravier, talus sec, bord de mer",
 "asso":"Sedum, Thymus serpyllum, Festuca glauca, Sempervivum",
 "cons":"Floraison fluorescente presque continue de juin aux gelées, avec des fleurs qui ne s'ouvrent qu'au soleil. Aucun arrosage, aucun amendement. Le drainage est vital : c'est l'humidité hivernale qui la tue, jamais le froid. À proscrire en sol lourd, à réserver aux rocailles, murets et toitures.",
 "bdm":"Front de mer","dens":9,"esp":0.3},

{"lat":"Escallonia","fr":"Escallonia","type":"Arbuste","h":2.5,"l":2.0,
 "expo":"Plein soleil","sol":"Drainé, tout type, calcaire toléré","hum":"Frais","rust":-12,
 "feu":"Persistant","cfeu":"Vert foncé brillant, vernissé","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Rose, rouge, blanc",
 "plant":"Automne à printemps","popt":"Octobre ou mars","ent":"Moyen",
 "style":"Haie fleurie persistante, bord de mer, écran, massif structuré",
 "asso":"Elaeagnus, Pittosporum, Griselinia, Phormium, Agapanthus",
 "cons":"Rare et précieux : une haie à la fois persistante et longuement fleurie, ce que peu d'arbustes offrent. Excellente tenue aux embruns, on le trouve partout sur le littoral atlantique. Rusticité limitée, à éviter en secteur froid et exposé. Tailler après la floraison principale. Feuillage aromatique au froissement.",
 "bdm":"Front de mer","dens":0.6,"esp":0.9},

{"lat":"Dryopteris erythrosora","fr":"Fougère automnale","type":"Fougère","h":0.6,"l":0.6,
 "expo":"Mi-ombre à ombre","sol":"Humifère, drainé, acide à neutre","hum":"Frais","rust":-20,
 "feu":"Semi-persistant","cfeu":"Cuivré rosé au débourrement, puis vert foncé","m1":0,"m2":0,"flo":"Non fleurie","cflo":"—",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Sous-bois, massif d'ombre, jardin japonais, bord de bassin ombragé",
 "asso":"Hosta, Carex, Heuchera, Epimedium, Hakonechloa, Astrantia",
 "cons":"Les jeunes frondes sortent cuivrées puis rosées avant de verdir, ce qui est très rare chez une fougère : elle apporte de la couleur à l'ombre. Semi-persistante en climat doux, elle garde une présence hivernale. Exige un sol qui ne dessèche pas et un paillage. Ne pas couper les vieilles frondes avant le printemps.",
 "bdm":"Second rideau","dens":3,"esp":0.6},

{"lat":"Cordyline australis","fr":"Cordyline","type":"Arbuste / Petit arbre","h":5.0,"l":2.0,
 "expo":"Plein soleil","sol":"Drainé, léger, sableux","hum":"Sec à frais","rust":-8,
 "feu":"Persistant","cfeu":"Vert, pourpre ou panaché selon cultivar","m1":6,"m2":7,"flo":"Juin à juillet","cflo":"Blanc crème parfumé",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Jardin exotique, bord de mer, sujet architectural, potée, entrée",
 "asso":"Phormium, Agapanthus, Yucca, graminées, Pittosporum",
 "cons":"Silhouette en palmier qui donne immédiatement un air exotique, très employée sur le littoral. Rusticité faible, c'est sa limite : les cultivars pourpres et panachés souffrent dès -6 °C, le type vert tient un peu mieux. Drainage impératif, l'humidité au collet en hiver la fait pourrir. À réserver aux situations abritées.",
 "bdm":"Front de mer","dens":0.3,"esp":1.8},

{"lat":"Sesleria caerulea","fr":"Seslérie bleue","type":"Graminée","h":0.3,"l":0.3,
 "expo":"Soleil à mi-ombre","sol":"Drainé, calcaire, pauvre","hum":"Sec à frais","rust":-25,
 "feu":"Persistant","cfeu":"Bleu vert, revers argenté","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Gris argenté",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Couvre-sol graminéen, prairie sèche, bordure, massif contemporain, entre-dalles",
 "asso":"Sedum, Festuca glauca, Salvia nemorosa, Achillea, Thymus",
 "cons":"Petite graminée persistante à floraison très précoce, employée en nappe pour remplacer un gazon en zone sèche et peu circulée. Supporte le calcaire et la mi-ombre, ce qui est rare. Compter 8 plants au m² pour un tapis continu. Peigner au printemps. Reste basse et régulière sans aucune intervention.",
 "bdm":"Front de mer","dens":8,"esp":0.35},

{"lat":"Grevillea juniperina","fr":"Grévilléa","type":"Arbuste","h":1.5,"l":2.0,
 "expo":"Plein soleil","sol":"Drainé, sableux, acide, très pauvre","hum":"Sec","rust":-10,
 "feu":"Persistant","cfeu":"Vert fin et piquant","m1":11,"m2":6,"flo":"Novembre à juin","cflo":"Jaune, orange, rouge",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Jardin sec, bord de mer, massif exotique, talus, jardin de gravier",
 "asso":"Cistus, Phormium, graminées sèches, Callistemon, Yucca",
 "cons":"Floraison hivernale et printanière très longue, en fleurs araignées originales, à une saison où presque rien ne fleurit. Redoute absolument le calcaire et les sols riches en phosphore : ne jamais fertiliser, cela la tue. Rusticité limitée, à réserver aux secteurs doux et abrités. Feuillage piquant, à écarter des passages.",
 "bdm":"Front de mer","dens":0.5,"esp":1.4},

{"lat":"Loropetalum","fr":"Loropétale de Chine","type":"Arbuste","h":2.0,"l":2.0,
 "expo":"Soleil à mi-ombre","sol":"Humifère, drainé, acide","hum":"Frais","rust":-12,
 "feu":"Persistant","cfeu":"Pourpre foncé ou vert selon cultivar","m1":3,"m2":5,"flo":"Mars à mai","cflo":"Rose fuchsia, blanc",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif contemporain, jardin de terre de bruyère, potée, contraste de feuillage",
 "asso":"Azalea, Nandina, Ophiopogon, Acer palmatum, Carex",
 "cons":"Feuillage pourpre persistant toute l'année et floraison en franges roses au printemps : peu d'arbustes offrent les deux. Exige un sol acide comme les azalées, le calcaire provoque une chlorose. Rusticité moyenne, à abriter des vents froids. Se taille bien pour maintenir un volume compact.",
 "bdm":"Second rideau","dens":0.5,"esp":1.4},
]
