# -*- coding: utf-8 -*-
"""Fiches horticoles - 50 especes les plus representees du catalogue AD.V.
Champs : type, dimensions adultes, exposition, sol, rusticite, feuillage,
floraison, plantation, entretien, style, associations.
"""

FICHES = [
{"lat":"Abelia grandiflora","fr":"Abélia","type":"Arbuste","h":2.0,"l":2.0,
 "expo":"Soleil à mi-ombre","sol":"Drainé, calcaire toléré","hum":"Frais à sec","rust":-12,
 "feu":"Semi-persistant","cfeu":"Vert brillant","m1":6,"m2":10,"flo":"Juin à octobre","cflo":"Blanc rosé",
 "plant":"Automne à printemps","popt":"Mars à avril ou octobre","ent":"Faible",
 "style":"Contemporain, massif structurant, haie libre",
 "asso":"Stipa, Pennisetum, Perovskia, Nepeta, rosiers paysagers",
 "cons":"Taille de rajeunissement tous les 2-3 ans en fin d'hiver. Craint les vents froids en situation exposée."},

{"lat":"Achillea millefolium","fr":"Achillée millefeuille","type":"Vivace","h":0.7,"l":0.5,
 "expo":"Plein soleil","sol":"Drainé, pauvre toléré","hum":"Sec","rust":-25,
 "feu":"Caduc","cfeu":"Vert grisé","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Blanc, rose, jaune, rouge",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Prairie fleurie, jardin sec, massif naturaliste",
 "asso":"Salvia nemorosa, Echinacea, Stipa, Gaura, Perovskia",
 "cons":"Rabattre après floraison pour une remontée. Se ressème et se divise facilement. Ne pas fertiliser."},

{"lat":"Ajuga reptans","fr":"Bugle rampante","type":"Couvre-sol","h":0.15,"l":0.5,
 "expo":"Mi-ombre à ombre","sol":"Tout type, humifère","hum":"Frais","rust":-20,
 "feu":"Persistant","cfeu":"Vert, pourpre ou panaché","m1":4,"m2":6,"flo":"Avril à juin","cflo":"Bleu violacé",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Sous-bois, pied d'arbre, bordure ombragée",
 "asso":"Hosta, Heuchera, fougères, Carex, Epimedium",
 "cons":"Couvre-sol traçant efficace. Limiter l'extension si nécessaire. Craint la sécheresse prolongée."},

{"lat":"Anemone hupehensis","fr":"Anémone du Japon","type":"Vivace","h":1.0,"l":0.6,
 "expo":"Mi-ombre","sol":"Frais, humifère, profond","hum":"Frais","rust":-20,
 "feu":"Caduc","cfeu":"Vert foncé","m1":8,"m2":10,"flo":"Août à octobre","cflo":"Blanc, rose",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif d'ombre, jardin romantique, sous-bois clair",
 "asso":"Hosta, fougères, Hydrangea, Carex, Astrantia",
 "cons":"Lente à s'installer, patienter 2 ans. Ne pas déplacer une fois établie. Précieuse pour la floraison tardive."},

{"lat":"Aubrieta","fr":"Aubriète","type":"Couvre-sol","h":0.15,"l":0.5,
 "expo":"Plein soleil","sol":"Drainé, calcaire, pauvre","hum":"Sec","rust":-20,
 "feu":"Persistant","cfeu":"Vert grisé","m1":3,"m2":5,"flo":"Mars à mai","cflo":"Violet, mauve, rose",
 "plant":"Automne à printemps","popt":"Septembre à octobre ou mars","ent":"Faible",
 "style":"Rocaille, muret, talus, dallage",
 "asso":"Iberis, Cerastium, Sedum, Armeria, Thymus",
 "cons":"Rabattre de moitié après floraison pour garder un port compact. Redoute l'humidité stagnante."},

{"lat":"Azalea japonica","fr":"Azalée japonaise","type":"Arbuste","h":1.0,"l":1.2,
 "expo":"Mi-ombre","sol":"Acide, humifère, drainé","hum":"Frais","rust":-18,
 "feu":"Persistant","cfeu":"Vert foncé","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Rose, rouge, blanc, violet",
 "plant":"Automne à printemps","popt":"Octobre ou mars","ent":"Moyen",
 "style":"Jardin japonais, massif de terre de bruyère, sous-bois",
 "asso":"Rhododendron, Pieris, Acer palmatum, fougères, Hydrangea",
 "cons":"Sol calcaire à proscrire absolument. Paillage indispensable, arrosage à l'eau non calcaire. Racines superficielles à protéger."},

{"lat":"Buddleia davidii","fr":"Arbre aux papillons","type":"Arbuste","h":3.0,"l":2.5,
 "expo":"Plein soleil","sol":"Tout type, drainé, calcaire toléré","hum":"Sec à frais","rust":-20,
 "feu":"Caduc","cfeu":"Vert grisé","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Violet, mauve, blanc, rose",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Moyen",
 "style":"Jardin de curé, massif estival, jardin de biodiversité",
 "asso":"Perovskia, Caryopteris, graminées, Verbena bonariensis",
 "cons":"Taille sévère obligatoire chaque fin d'hiver (30 cm du sol) sinon dégarnissement rapide. Espèce classée envahissante dans certaines régions : privilégier les cultivars stériles."},

{"lat":"Calamagrostis acutiflora","fr":"Calamagrostide","type":"Graminée","h":1.6,"l":0.6,
 "expo":"Plein soleil","sol":"Tout type, y compris argileux","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert, doré en automne","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Beige doré",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif contemporain, graminée verticale de structure",
 "asso":"Perovskia, Echinacea, Rudbeckia, Sedum, Salvia nemorosa",
 "cons":"Port strictement vertical, ne s'affaisse pas. Rabattre en fin d'hiver. Silhouette hivernale décorative à conserver."},

{"lat":"Carex morrowii","fr":"Laîche du Japon","type":"Graminée","h":0.4,"l":0.4,
 "expo":"Mi-ombre à ombre","sol":"Frais, humifère","hum":"Frais","rust":-18,
 "feu":"Persistant","cfeu":"Vert panaché de blanc ou crème","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Brun discret",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Bordure d'ombre, sous-bois, jardin japonais, potée",
 "asso":"Hosta, Heuchera, fougères, Ajuga, Hakonechloa",
 "cons":"Persistant précieux pour l'hiver. Peigner à la main au printemps plutôt que rabattre. Craint le plein soleil brûlant."},

{"lat":"Cornus alba","fr":"Cornouiller blanc","type":"Arbuste","h":2.5,"l":2.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, argileux toléré","hum":"Frais à humide","rust":-30,
 "feu":"Caduc","cfeu":"Vert ou panaché, rouge en automne","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Blanc crème",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Moyen",
 "style":"Haie libre, massif d'hiver, bord de bassin, jardin naturaliste",
 "asso":"Salix, Miscanthus, Hydrangea paniculata, Viburnum, graminées",
 "cons":"Cultivé pour ses bois colorés en hiver. Recéper un tiers des tiges chaque année en fin d'hiver : seuls les jeunes bois sont vivement colorés. Supporte les sols détrempés."},

{"lat":"Corylus avellana","fr":"Noisetier commun","type":"Arbuste","h":5.0,"l":4.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, calcaire toléré, profond","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert, jaune en automne","m1":1,"m2":3,"flo":"Janvier à mars","cflo":"Jaune (chatons)",
 "plant":"Automne","popt":"Novembre à février","ent":"Faible",
 "style":"Haie champêtre, verger, jardin nourricier, brise-vue",
 "asso":"Cornus sanguinea, Viburnum opulus, Crataegus, Sambucus",
 "cons":"Planter au moins deux variétés pour la fructification. Drageonne : supprimer les rejets. Floraison très précoce, ressource pour les pollinisateurs."},

{"lat":"Cotoneaster","fr":"Cotonéaster","type":"Couvre-sol / Arbuste","h":0.5,"l":1.5,
 "expo":"Soleil à mi-ombre","sol":"Tout type, drainé, calcaire toléré","hum":"Sec à frais","rust":-20,
 "feu":"Persistant à semi-persistant","cfeu":"Vert foncé brillant","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Blanc rosé",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Talus, couvre-sol de masse, pied de mur, aménagement collectif",
 "asso":"Juniperus, Hedera, Vinca, graminées basses",
 "cons":"Très rustique et sans entretien. Baies rouges décoratives en automne et hiver, appréciées des oiseaux. Sensible au feu bactérien : éviter la taille en période humide."},

{"lat":"Cupressocyparis leylandii","fr":"Cyprès de Leyland","type":"Conifère","h":15.0,"l":4.0,
 "expo":"Plein soleil","sol":"Tout type, drainé","hum":"Frais","rust":-18,
 "feu":"Persistant","cfeu":"Vert foncé ou doré","m1":0,"m2":0,"flo":"Non ornementale","cflo":"—",
 "plant":"Automne à printemps","popt":"Octobre à novembre ou mars","ent":"Soutenu",
 "style":"Haie brise-vue, écran rapide",
 "asso":"À utiliser seul en haie monospécifique, ou mieux : intégré dans une haie mixte",
 "cons":"Croissance très rapide (80 cm à 1 m par an) : deux tailles annuelles indispensables. Ne repart pas sur le vieux bois, ne jamais tailler trop court. Concurrence fortement les plantations voisines. Alternative à proposer au client : Photinia, Elaeagnus ou haie mixte, moins contraignantes."},

{"lat":"Deschampsia cespitosa","fr":"Canche cespiteuse","type":"Graminée","h":1.0,"l":0.6,
 "expo":"Soleil à mi-ombre","sol":"Tout type, humifère","hum":"Frais à humide","rust":-25,
 "feu":"Semi-persistant","cfeu":"Vert foncé","m1":6,"m2":8,"flo":"Juin à août","cflo":"Beige argenté à doré",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif naturaliste, prairie, bord de bassin, contre-jour",
 "asso":"Molinia, Persicaria, Astrantia, Sanguisorba, Rudbeckia",
 "cons":"Espèce indigène, l'une des rares graminées tolérant la mi-ombre et l'humidité. Inflorescences en nuage spectaculaires à contre-jour. Peigner au printemps."},

{"lat":"Euphorbia characias","fr":"Euphorbe des garrigues","type":"Vivace","h":1.2,"l":1.0,
 "expo":"Plein soleil","sol":"Drainé, sec, calcaire, pauvre","hum":"Sec","rust":-12,
 "feu":"Persistant","cfeu":"Vert bleuté","m1":3,"m2":6,"flo":"Mars à juin","cflo":"Vert chartreuse",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin sec, méditerranéen, rocaille, massif graphique",
 "asso":"Lavandula, Cistus, Santolina, Stipa, Perovskia",
 "cons":"Structure persistante remarquable toute l'année. Couper les tiges défleuries à la base. Latex irritant : gants obligatoires, à signaler au client s'il y a des enfants. Redoute l'humidité hivernale."},

{"lat":"Ficus carica","fr":"Figuier commun","type":"Fruitier","h":4.0,"l":4.0,
 "expo":"Plein soleil","sol":"Drainé, calcaire toléré, pauvre","hum":"Sec","rust":-15,
 "feu":"Caduc","cfeu":"Vert franc","m1":0,"m2":0,"flo":"Non ornementale","cflo":"—",
 "plant":"Printemps","popt":"Mars à avril","ent":"Faible",
 "style":"Jardin méditerranéen, verger, terrasse abritée, patrimoine",
 "asso":"Lavandula, Rosmarinus, Vitis, Olea, graminées sèches",
 "cons":"Planter au printemps et non en automne, le jeune sujet craint l'hiver humide. Situation chaude et abritée, contre un mur au sud idéalement. Racines envahissantes : éloigner des canalisations. Peu d'arrosage une fois installé."},

{"lat":"Gaura lindheimeri","fr":"Gaura","type":"Vivace","h":1.0,"l":0.7,
 "expo":"Plein soleil","sol":"Drainé, pauvre toléré","hum":"Sec","rust":-15,
 "feu":"Semi-persistant","cfeu":"Vert grisé","m1":6,"m2":10,"flo":"Juin à octobre","cflo":"Blanc, rose",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif léger, jardin sec, effet nuage, bordure aérienne",
 "asso":"Perovskia, Stipa, Salvia, Verbena bonariensis, Nepeta",
 "cons":"Floraison exceptionnellement longue. Redoute l'humidité hivernale bien plus que le froid : drainage impératif. Rabattre au printemps. Durée de vie limitée (4-5 ans), prévoir le remplacement."},

{"lat":"Geranium","fr":"Géranium vivace","type":"Couvre-sol / Vivace","h":0.4,"l":0.6,
 "expo":"Soleil à mi-ombre","sol":"Tout type, drainé","hum":"Frais","rust":-20,
 "feu":"Semi-persistant","cfeu":"Vert, souvent coloré en automne","m1":5,"m2":9,"flo":"Mai à septembre","cflo":"Rose, bleu, violet, blanc",
 "plant":"Automne à printemps","popt":"Mars à mai ou septembre","ent":"Faible",
 "style":"Couvre-sol fleuri, bordure, pied de rosier, sous-bois clair",
 "asso":"Rosiers, Alchemilla, Nepeta, Hosta, Heuchera",
 "cons":"Valeur sûre du couvre-sol fleuri, très peu exigeant. Rabattre après la première floraison pour une remontée et un feuillage neuf. Se divise tous les 3-4 ans."},

{"lat":"Hedera","fr":"Lierre","type":"Grimpante / Couvre-sol","h":10.0,"l":3.0,
 "expo":"Mi-ombre à ombre","sol":"Tout type, calcaire toléré","hum":"Frais","rust":-25,
 "feu":"Persistant","cfeu":"Vert foncé ou panaché","m1":9,"m2":10,"flo":"Septembre à octobre","cflo":"Vert jaune",
 "plant":"Automne à printemps","popt":"Septembre à novembre ou mars","ent":"Moyen",
 "style":"Habillage de mur, couvre-sol d'ombre, pied d'arbre, talus",
 "asso":"Utilisé seul en nappe, ou avec fougères, Vinca, Carex",
 "cons":"Le meilleur couvre-sol pour l'ombre sèche, là où rien d'autre ne pousse. Ne détériore pas un mur sain mais s'infiltre dans les joints dégradés : à vérifier avant plantation. Floraison automnale précieuse pour les insectes. Taille annuelle pour contenir."},

{"lat":"Hibiscus syriacus","fr":"Althéa","type":"Arbuste","h":3.0,"l":2.0,
 "expo":"Plein soleil","sol":"Drainé, calcaire toléré, profond","hum":"Frais","rust":-20,
 "feu":"Caduc","cfeu":"Vert franc","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Bleu, violet, rose, blanc, bicolore",
 "plant":"Automne à printemps","popt":"Octobre ou mars à avril","ent":"Faible",
 "style":"Jardin de curé, haie fleurie, massif estival, sujet isolé",
 "asso":"Perovskia, Caryopteris, Lagerstroemia, graminées, Rosa",
 "cons":"Feuillaison très tardive (mai) : rassurer le client qui le croit mort au printemps. Floraison estivale précieuse quand peu d'arbustes fleurissent. Taille de printemps pour densifier."},

{"lat":"Hosta","fr":"Hosta","type":"Vivace","h":0.6,"l":0.8,
 "expo":"Mi-ombre à ombre","sol":"Frais, humifère, profond","hum":"Frais à humide","rust":-25,
 "feu":"Caduc","cfeu":"Vert, bleuté, doré ou panaché","m1":6,"m2":8,"flo":"Juin à août","cflo":"Mauve, blanc",
 "plant":"Printemps","popt":"Mars à mai","ent":"Moyen",
 "style":"Massif d'ombre, jardin japonais, bord de bassin, potée",
 "asso":"Fougères, Carex, Astilbe, Heuchera, Anemone du Japon, Hydrangea",
 "cons":"Cultivé pour le feuillage plus que la fleur. Limaces et escargots sont le problème principal : prévoir une protection dès le débourrement. Le soleil direct brûle le feuillage. Paillage indispensable."},

{"lat":"Hydrangea macrophylla","fr":"Hortensia","type":"Arbuste","h":1.5,"l":1.5,
 "expo":"Mi-ombre","sol":"Acide à neutre, humifère, drainé","hum":"Frais","rust":-15,
 "feu":"Caduc","cfeu":"Vert franc","m1":6,"m2":9,"flo":"Juin à septembre","cflo":"Rose, bleu, blanc, mauve",
 "plant":"Automne à printemps","popt":"Octobre ou mars","ent":"Moyen",
 "style":"Jardin d'ombre, massif de terre de bruyère, façade nord, jardin de bord de mer",
 "asso":"Azalea, Acer palmatum, Hosta, fougères, Carex, Anemone du Japon",
 "cons":"La couleur dépend du pH : bleu en sol acide, rose en sol calcaire. Le préciser au client, c'est souvent une source de déception. Taille légère seulement, au-dessus de la première paire de bourgeons sains : les fleurs se forment sur le bois de l'année précédente. Arrosage régulier en été."},

{"lat":"Hydrangea paniculata","fr":"Hortensia paniculé","type":"Arbuste","h":2.0,"l":1.8,
 "expo":"Soleil à mi-ombre","sol":"Tout type, humifère, calcaire toléré","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Blanc virant rose",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Massif contemporain, haie libre fleurie, sujet isolé, jardin blanc",
 "asso":"Graminées, Perovskia, Cornus alba, Rosa, Miscanthus",
 "cons":"Bien plus tolérant que le macrophylla : accepte le calcaire et le soleil, et fleurit sur le bois de l'année. Taille franche en fin d'hiver, à deux yeux, pour de grosses panicules. Le meilleur choix d'hortensia hors terre de bruyère. Inflorescences séchées décoratives en hiver."},

{"lat":"Lagerstroemia indica","fr":"Lilas des Indes","type":"Arbuste / Petit arbre","h":5.0,"l":3.0,
 "expo":"Plein soleil","sol":"Drainé, profond, calcaire toléré","hum":"Frais","rust":-15,
 "feu":"Caduc","cfeu":"Vert, rouge orangé en automne","m1":7,"m2":9,"flo":"Juillet à septembre","cflo":"Rose, rouge, violet, blanc",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin méditerranéen, alignement urbain, sujet isolé, terrasse",
 "asso":"Perovskia, Lavandula, graminées, Nepeta, Salvia",
 "cons":"Trois atouts sur l'année : floraison estivale longue, feuillage d'automne coloré, écorce décorative en hiver. Exige de la chaleur pour bien fleurir. Feuillaison tardive. Taille légère en fin d'hiver."},

{"lat":"Lavandula angustifolia","fr":"Lavande vraie","type":"Arbuste / Vivace","h":0.5,"l":0.7,
 "expo":"Plein soleil","sol":"Drainé, sec, calcaire, pauvre","hum":"Sec","rust":-18,
 "feu":"Persistant","cfeu":"Argenté","m1":6,"m2":8,"flo":"Juin à août","cflo":"Mauve, bleu violacé",
 "plant":"Printemps (à éviter en automne)","popt":"Mars à mai","ent":"Moyen",
 "style":"Jardin méditerranéen, bordure, rocaille, jardin de curé, massif sec",
 "asso":"Rosmarinus, Santolina, Cistus, Stipa, Perovskia, rosiers",
 "cons":"Le drainage compte plus que le froid : c'est l'humidité hivernale qui tue, pas le gel. Planter au printemps, en sol pauvre, sans amendement. Taille annuelle obligatoire juste après la floraison, sur le bois vert uniquement, sinon dégarnissement irréversible en 3 ans. Durée de vie 8-10 ans."},

{"lat":"Lavandula intermedia","fr":"Lavandin","type":"Arbuste / Vivace","h":0.8,"l":1.0,
 "expo":"Plein soleil","sol":"Drainé, sec, calcaire, pauvre","hum":"Sec","rust":-15,
 "feu":"Persistant","cfeu":"Argenté","m1":7,"m2":8,"flo":"Juillet à août","cflo":"Mauve, bleu",
 "plant":"Printemps (à éviter en automne)","popt":"Mars à mai","ent":"Moyen",
 "style":"Bordure massive, alignement, jardin sec, grande rocaille",
 "asso":"Rosmarinus, Santolina, Perovskia, Stipa, Cistus",
 "cons":"Plus volumineux et plus florifère que la lavande vraie, mais un peu moins rustique et au parfum plus camphré. Idéal pour les longues bordures. Mêmes exigences : drainage et taille annuelle après floraison sur bois vert."},

{"lat":"Malus domestica","fr":"Pommier","type":"Fruitier","h":4.0,"l":4.0,
 "expo":"Plein soleil","sol":"Profond, frais, drainé","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Blanc rosé",
 "plant":"Automne","popt":"Novembre à février","ent":"Soutenu",
 "style":"Verger, jardin nourricier, palissage sur mur, alignement fruitier",
 "asso":"Prairie fleurie, vivaces mellifères au pied, haie champêtre",
 "cons":"Prévoir deux variétés compatibles pour la pollinisation, ou un pollinisateur à proximité. Le porte-greffe détermine la taille finale, à vérifier chez AD.V selon la forme (quenouille, demi-tige). Taille de formation puis de fructification annuelle. Surveiller tavelure et carpocapse."},

{"lat":"Miscanthus sinensis","fr":"Roseau de Chine","type":"Graminée","h":2.0,"l":1.2,
 "expo":"Plein soleil","sol":"Tout type, profond","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert ou panaché, ocre en automne","m1":8,"m2":10,"flo":"Août à octobre","cflo":"Beige argenté à rosé",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Massif contemporain, écran végétal estival, jardin naturaliste, bord de bassin",
 "asso":"Perovskia, Rudbeckia, Echinacea, Sedum, Hydrangea paniculata",
 "cons":"Planter impérativement au printemps, l'installation avant l'hiver est risquée. Rabattre en fin d'hiver seulement : la silhouette sèche est décorative toute la saison froide et protège la souche. Non traçant, contrairement aux bambous. Compter 3 ans pour le volume adulte."},

{"lat":"Nandina domestica","fr":"Bambou sacré","type":"Arbuste","h":1.8,"l":1.2,
 "expo":"Soleil à mi-ombre","sol":"Drainé, humifère, frais","hum":"Frais","rust":-15,
 "feu":"Persistant","cfeu":"Vert, rouge en hiver","m1":6,"m2":7,"flo":"Juin à juillet","cflo":"Blanc crème",
 "plant":"Automne à printemps","popt":"Mars à avril ou octobre","ent":"Faible",
 "style":"Jardin japonais, massif contemporain, terrasse, entrée",
 "asso":"Carex, Ophiopogon, Acer palmatum, Hakonechloa, fougères",
 "cons":"Ce n'est pas un bambou et il n'est pas traçant, malgré son nom : à préciser au client inquiet. Feuillage rougissant en hiver, baies rouges persistantes. Supprimer les tiges les plus âgées à la base pour renouveler. Craint les vents froids desséchants."},

{"lat":"Pennisetum alopecuroides","fr":"Herbe aux écouvillons","type":"Graminée","h":0.8,"l":0.8,
 "expo":"Plein soleil","sol":"Drainé, fertile","hum":"Frais à sec","rust":-18,
 "feu":"Caduc","cfeu":"Vert, doré en automne","m1":8,"m2":10,"flo":"Août à octobre","cflo":"Beige rosé à pourpré",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Massif contemporain, bordure souple, jardin naturaliste, potée",
 "asso":"Sedum, Perovskia, Echinacea, Salvia nemorosa, Gaura",
 "cons":"Plantation de printemps impérative. Épis en goupillon très décoratifs, y compris desséchés. Démarrage tardif au printemps : ne pas croire à un échec. Rabattre en mars. Sensible à l'humidité hivernale en sol lourd."},

{"lat":"Perovskia atriplicifolia","fr":"Sauge d'Afghanistan","type":"Arbuste / Vivace","h":1.2,"l":1.0,
 "expo":"Plein soleil","sol":"Drainé, sec, calcaire, pauvre","hum":"Sec","rust":-20,
 "feu":"Caduc","cfeu":"Argenté","m1":7,"m2":10,"flo":"Juillet à octobre","cflo":"Bleu lavande",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin sec, massif contemporain, bordure aérienne, jardin de gravier",
 "asso":"Graminées, Gaura, Sedum, Echinacea, Lavandula, Achillea",
 "cons":"Excellente tenue en sécheresse et floraison très longue en fin de saison. Rabattre à 15 cm en fin d'hiver, la floraison a lieu sur le bois de l'année. Ne jamais fertiliser ni arroser une fois installé. Redoute les sols lourds et humides."},

{"lat":"Physocarpus opulifolius","fr":"Physocarpe","type":"Arbuste","h":2.5,"l":2.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, frais, argileux toléré","hum":"Frais","rust":-30,
 "feu":"Caduc","cfeu":"Pourpre, doré ou vert selon cultivar","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Blanc rosé",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie libre, massif de contraste, jardin naturaliste, écran coloré",
 "asso":"Graminées, Hydrangea paniculata, Cornus alba, Spiraea, vivaces claires",
 "cons":"Cultivé avant tout pour son feuillage coloré : les cultivars pourpres demandent du soleil pour garder leur teinte. Très rustique et sans exigence. Recéper un tiers des branches tous les 2-3 ans. Écorce exfoliante décorative en hiver."},

{"lat":"Potentilla fruticosa","fr":"Potentille arbustive","type":"Arbuste","h":1.0,"l":1.2,
 "expo":"Plein soleil","sol":"Tout type, drainé, pauvre toléré","hum":"Sec à frais","rust":-30,
 "feu":"Caduc","cfeu":"Vert grisé","m1":5,"m2":10,"flo":"Mai à octobre","cflo":"Jaune, blanc, orange, rose",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Bordure, massif bas, aménagement collectif, rocaille, talus",
 "asso":"Lavandula, graminées, Nepeta, Santolina, Sedum",
 "cons":"L'une des floraisons les plus longues du catalogue, près de six mois. Extrêmement rustique et sans entretien. Rabattre d'un tiers tous les 2-3 ans en fin d'hiver pour éviter le dégarnissement. Les cultivars roses pâlissent au plein soleil."},

{"lat":"Prunus avium","fr":"Merisier / Cerisier","type":"Arbre / Fruitier","h":8.0,"l":6.0,
 "expo":"Plein soleil","sol":"Profond, drainé, calcaire toléré","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert, rouge orangé en automne","m1":4,"m2":4,"flo":"Avril","cflo":"Blanc",
 "plant":"Automne","popt":"Novembre à février","ent":"Moyen",
 "style":"Verger, haie champêtre, arbre d'ombrage, jardin nourricier",
 "asso":"Prairie fleurie, haie champêtre, bulbes de printemps au pied",
 "cons":"Vérifier l'autofertilité de la variété, beaucoup de cerisiers exigent un pollinisateur. Tailler uniquement en été, hors sève, pour éviter les écoulements de gomme. Système racinaire traçant : éloigner des constructions. Prévoir le volume adulte, souvent sous-estimé."},

{"lat":"Prunus domestica","fr":"Prunier","type":"Fruitier","h":5.0,"l":4.0,
 "expo":"Plein soleil","sol":"Profond, frais, calcaire toléré","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert franc","m1":3,"m2":4,"flo":"Mars à avril","cflo":"Blanc",
 "plant":"Automne","popt":"Novembre à janvier","ent":"Moyen",
 "style":"Verger, jardin nourricier, haie fruitière",
 "asso":"Prairie fleurie, vivaces mellifères, haie champêtre",
 "cons":"Floraison précoce sensible aux gelées tardives : éviter les fonds de vallée et situations froides. Certaines variétés sont autofertiles, d'autres non, à vérifier avec AD.V. Taille légère en été. Drageonne selon le porte-greffe."},

{"lat":"Prunus laurocerasus","fr":"Laurier-cerise","type":"Arbuste","h":3.0,"l":2.5,
 "expo":"Soleil à ombre","sol":"Tout type, drainé, calcaire toléré","hum":"Frais","rust":-20,
 "feu":"Persistant","cfeu":"Vert foncé brillant","m1":4,"m2":5,"flo":"Avril à mai","cflo":"Blanc crème",
 "plant":"Automne à printemps","popt":"Septembre à novembre ou mars","ent":"Moyen",
 "style":"Haie brise-vue, écran persistant, massif d'ombre, fond de jardin",
 "asso":"Haie mixte avec Photinia, Elaeagnus, Viburnum tinus, Ligustrum",
 "cons":"Valeur sûre de la haie persistante, tolère l'ombre là où peu d'arbustes réussissent. Une à deux tailles par an, au sécateur plutôt qu'au taille-haie pour ne pas déchirer les grandes feuilles. Feuilles et fruits toxiques par ingestion : le signaler s'il y a de jeunes enfants. Considéré comme envahissant dans certaines régions, à intégrer de préférence dans une haie mixte."},

{"lat":"Prunus persica","fr":"Pêcher","type":"Fruitier","h":4.0,"l":3.5,
 "expo":"Plein soleil","sol":"Drainé, léger, profond","hum":"Frais","rust":-20,
 "feu":"Caduc","cfeu":"Vert franc","m1":3,"m2":4,"flo":"Mars à avril","cflo":"Rose vif",
 "plant":"Automne","popt":"Novembre à février","ent":"Soutenu",
 "style":"Verger, palissage sur mur chaud, jardin nourricier",
 "asso":"Ail et ciboulette au pied (usage traditionnel), prairie fleurie",
 "cons":"Le plus exigeant des fruitiers courants. Floraison très précoce et gélive : réserver aux situations abritées, idéalement palissé contre un mur au sud. Cloque du pêcher quasi systématique en climat humide : traitement préventif à l'automne et au débourrement. Taille annuelle obligatoire, il fructifie sur le bois de l'année précédente. Durée de vie courte, 15 à 20 ans, à annoncer au client."},

{"lat":"Pyracantha","fr":"Buisson ardent","type":"Arbuste","h":3.0,"l":2.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, drainé, calcaire toléré","hum":"Sec à frais","rust":-20,
 "feu":"Persistant","cfeu":"Vert foncé","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Blanc crème",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Moyen",
 "style":"Haie défensive, palissage sur mur, écran persistant, jardin de biodiversité",
 "asso":"Haie mixte avec Berberis, Elaeagnus, Cotoneaster, Ligustrum",
 "cons":"Épines très acérées : excellent en haie défensive, à éviter le long d'un passage ou d'une aire de jeux. Baies orange ou rouges spectaculaires de septembre à l'hiver, très appréciées des oiseaux. Sensible au feu bactérien : choisir les cultivars résistants et tailler par temps sec. Port palissable."},

{"lat":"Pyrus domestica","fr":"Poirier","type":"Fruitier","h":5.0,"l":3.5,
 "expo":"Plein soleil","sol":"Profond, frais, drainé","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert brillant, rouge en automne","m1":4,"m2":4,"flo":"Avril","cflo":"Blanc",
 "plant":"Automne","popt":"Novembre à février","ent":"Soutenu",
 "style":"Verger, palissage, jardin nourricier, alignement fruitier",
 "asso":"Prairie fleurie, vivaces mellifères au pied",
 "cons":"Pollinisation croisée nécessaire dans la quasi-totalité des cas : prévoir deux variétés compatibles. Plus longévif que le pommier mais plus lent à entrer en production. Se prête très bien au palissage en espalier. Surveiller la tavelure et le psylle."},

{"lat":"Rosa","fr":"Rosier paysager","type":"Arbuste","h":1.0,"l":1.0,
 "expo":"Plein soleil","sol":"Profond, frais, drainé, argileux toléré","hum":"Frais","rust":-20,
 "feu":"Caduc","cfeu":"Vert franc","m1":5,"m2":10,"flo":"Mai à octobre","cflo":"Rouge, rose, blanc, jaune, orange",
 "plant":"Automne à printemps","popt":"Novembre à mars","ent":"Moyen",
 "style":"Massif fleuri, bordure, aménagement collectif, talus, jardin romantique",
 "asso":"Nepeta, Lavandula, Geranium vivace, Perovskia, graminées",
 "cons":"Les rosiers paysagers demandent nettement moins d'entretien que les rosiers de collection : une taille de nettoyage en fin d'hiver suffit. Choisir des variétés résistantes aux maladies (labels ADR ou équivalents) pour éviter les traitements. Éviter de replanter un rosier à l'emplacement d'un ancien sans changer la terre."},

{"lat":"Rosmarinus officinalis","fr":"Romarin","type":"Arbuste","h":1.5,"l":1.2,
 "expo":"Plein soleil","sol":"Drainé, sec, calcaire, pauvre","hum":"Sec","rust":-12,
 "feu":"Persistant","cfeu":"Vert foncé, revers argenté","m1":3,"m2":5,"flo":"Mars à mai","cflo":"Bleu pâle, mauve",
 "plant":"Printemps (à éviter en automne)","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin méditerranéen, jardin d'aromatiques, bordure, talus, rocaille",
 "asso":"Lavandula, Santolina, Cistus, Thymus, Salvia officinalis",
 "cons":"Floraison très précoce, précieuse pour les premiers pollinisateurs. Drainage impératif, c'est l'humidité hivernale qui le tue. Taille légère après floraison, jamais sur le vieux bois. Les formes rampantes conviennent bien aux murets et talus."},

{"lat":"Salvia nemorosa","fr":"Sauge des bois","type":"Vivace","h":0.5,"l":0.4,
 "expo":"Plein soleil","sol":"Drainé, calcaire toléré, pauvre","hum":"Sec","rust":-25,
 "feu":"Caduc","cfeu":"Vert grisé","m1":5,"m2":9,"flo":"Mai à septembre","cflo":"Violet, bleu, rose",
 "plant":"Automne à printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Massif naturaliste, bordure, jardin sec, prairie fleurie",
 "asso":"Achillea, Stipa, Echinacea, Nepeta, Perovskia, Gaura",
 "cons":"Épis verticaux très structurants en massif. Rabattre juste après la première floraison pour obtenir une seconde vague en fin d'été. Très rustique et sobre en eau. Une des meilleures vivaces pour un massif d'inspiration naturaliste."},

{"lat":"Salvia officinalis","fr":"Sauge officinale","type":"Arbuste / Vivace","h":0.6,"l":0.8,
 "expo":"Plein soleil","sol":"Drainé, sec, calcaire, pauvre","hum":"Sec","rust":-20,
 "feu":"Persistant","cfeu":"Vert grisé, pourpre ou panaché","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Mauve, bleu",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Jardin d'aromatiques, bordure, jardin sec, massif de feuillages",
 "asso":"Lavandula, Thymus, Rosmarinus, Santolina, Stipa",
 "cons":"Cultivée autant pour son feuillage aromatique persistant que pour sa fleur. Rabattre d'un tiers au printemps pour maintenir un port compact, sur bois vert uniquement. Se dégarnit après 4-5 ans, prévoir le renouvellement. Les cultivars panachés sont moins rustiques."},

{"lat":"Salvia microphylla","fr":"Sauge arbustive","type":"Vivace / Arbuste","h":1.0,"l":0.8,
 "expo":"Plein soleil","sol":"Drainé, léger","hum":"Sec à frais","rust":-10,
 "feu":"Semi-persistant","cfeu":"Vert franc","m1":6,"m2":11,"flo":"Juin à novembre","cflo":"Rouge, rose, corail, blanc, bicolore",
 "plant":"Printemps","popt":"Avril à mai","ent":"Faible",
 "style":"Massif estival, jardin sec, bordure colorée, terrasse",
 "asso":"Gaura, Perovskia, graminées, Verbena bonariensis, Nepeta",
 "cons":"Floraison la plus longue du catalogue, souvent jusqu'aux premières gelées. Rusticité limitée : réserver aux situations abritées et bien drainées, ou prévoir un paillage hivernal. Rabattre au printemps seulement, jamais en automne. Plantation de printemps impérative."},

{"lat":"Spiraea japonica","fr":"Spirée du Japon","type":"Arbuste","h":1.0,"l":1.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, frais","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert, doré ou bronze selon cultivar","m1":6,"m2":8,"flo":"Juin à août","cflo":"Rose, rouge, blanc",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Bordure, massif bas, aménagement collectif, haie basse",
 "asso":"Graminées, Nepeta, Geranium vivace, Potentilla, Hydrangea",
 "cons":"Arbuste sans difficulté, très utilisé en collectif pour cette raison. Rabattre de moitié en fin d'hiver : il fleurit sur le bois de l'année et se densifie ainsi. Les cultivars à feuillage doré éclairent bien un massif mais brûlent au soleil brûlant."},

{"lat":"Thymus vulgaris","fr":"Thym commun","type":"Couvre-sol / Aromatique","h":0.3,"l":0.4,
 "expo":"Plein soleil","sol":"Drainé, sec, calcaire, pauvre, caillouteux","hum":"Sec","rust":-15,
 "feu":"Persistant","cfeu":"Vert grisé","m1":5,"m2":7,"flo":"Mai à juillet","cflo":"Mauve, rose, blanc",
 "plant":"Printemps","popt":"Mars à mai","ent":"Faible",
 "style":"Rocaille, dallage, jardin sec, bordure basse, toiture végétalisée",
 "asso":"Lavandula, Santolina, Sedum, Armeria, Cistus",
 "cons":"Supporte le piétinement léger : intéressant entre les dalles. Exige un sol vraiment drainant, il pourrit en terre lourde. Tailler légèrement après floraison. Très mellifère. Durée de vie 4-5 ans, à renouveler."},

{"lat":"Viburnum opulus","fr":"Viorne obier","type":"Arbuste","h":4.0,"l":3.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, argileux toléré","hum":"Frais à humide","rust":-30,
 "feu":"Caduc","cfeu":"Vert, rouge vif en automne","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Blanc",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie champêtre, jardin naturaliste, bord de bassin, jardin de biodiversité",
 "asso":"Cornus sanguinea, Corylus, Sambucus, Crataegus, graminées",
 "cons":"Espèce indigène, excellente pour la biodiversité : fleurs mellifères, baies rouges consommées par les oiseaux, feuillage d'automne éclatant. Tolère les sols lourds et humides, rare parmi les arbustes. Taille minimale. Le cultivar Roseum est stérile, sans baies : à préciser si le client cherche l'intérêt automnal."},

{"lat":"Viburnum tinus","fr":"Laurier-tin","type":"Arbuste","h":2.5,"l":2.0,
 "expo":"Soleil à mi-ombre","sol":"Drainé, calcaire toléré","hum":"Frais à sec","rust":-10,
 "feu":"Persistant","cfeu":"Vert foncé","m1":11,"m2":4,"flo":"Novembre à avril","cflo":"Blanc, boutons rosés",
 "plant":"Automne à printemps","popt":"Septembre à novembre ou mars","ent":"Faible",
 "style":"Haie persistante, massif d'hiver, jardin méditerranéen, terrasse",
 "asso":"Photinia, Elaeagnus, Prunus laurocerasus, Nandina, graminées",
 "cons":"Précieux pour sa floraison hivernale, presque unique parmi les arbustes de haie. Baies bleu métallique décoratives. Rusticité limitée : à éviter en situation froide et exposée. Taille après floraison, au printemps. Bonne tolérance au bord de mer."},

{"lat":"Vinca","fr":"Pervenche","type":"Couvre-sol","h":0.2,"l":1.0,
 "expo":"Mi-ombre à ombre","sol":"Tout type, calcaire toléré","hum":"Frais à sec","rust":-20,
 "feu":"Persistant","cfeu":"Vert foncé ou panaché","m1":3,"m2":6,"flo":"Mars à juin","cflo":"Bleu, mauve, blanc",
 "plant":"Automne à printemps","popt":"Septembre à novembre ou mars","ent":"Faible",
 "style":"Couvre-sol d'ombre, talus, sous-bois, pied d'arbre, pied de haie",
 "asso":"Hedera, fougères, Hosta, Carex, Epimedium",
 "cons":"L'un des meilleurs couvre-sols pour l'ombre sèche, y compris sous les arbres. Compter 4 à 6 plants au m² pour une couverture en deux saisons. Vinca major est plus vigoureuse mais plus envahissante que Vinca minor : choisir selon la surface à couvrir et la volonté d'entretien du client."},

{"lat":"Weigelia","fr":"Weigélia","type":"Arbuste","h":2.0,"l":2.0,
 "expo":"Soleil à mi-ombre","sol":"Tout type, frais, humifère","hum":"Frais","rust":-25,
 "feu":"Caduc","cfeu":"Vert, pourpre ou panaché selon cultivar","m1":5,"m2":6,"flo":"Mai à juin","cflo":"Rose, rouge, blanc",
 "plant":"Automne à printemps","popt":"Octobre à mars","ent":"Faible",
 "style":"Haie libre fleurie, massif de printemps, jardin de curé",
 "asso":"Spiraea, Philadelphus, Deutzia, Physocarpus, graminées",
 "cons":"Floraison abondante de printemps, souvent suivie d'une remontée légère en fin d'été. Tailler juste après la floraison, il fleurit sur le bois de l'année précédente : une taille de fin d'hiver supprimerait les fleurs. Supprimer un tiers des vieilles branches à la base tous les 2-3 ans."},
]
