# -*- coding: utf-8 -*-
"""Dictionnaire genre latin -> nom commun francais (usage paysager)."""

NOMS_GENRES = {
    "ABELIA": "Abélia",
    "ACANTHUS": "Acanthe",
    "ACER": "Érable",
    "ACHILLEA": "Achillée",
    "ACTINIDIA": "Kiwi",
    "AGAPANTHE": "Agapanthe",
    "AGAPANTHUS": "Agapanthe",
    "AGASTACHE": "Agastache",
    "AJUGA": "Bugle rampante",
    "AKEBIA": "Akébie",
    "ALBIZZIA": "Arbre à soie",
    "ALCEA": "Rose trémière",
    "ALCHEMILLA": "Alchémille",
    "ALLIUM": "Ail d'ornement",
    "ALNUS": "Aulne",
    "ALSTROEMERIA": "Lis des Incas",
    "AMELANCHIER": "Amélanchier",
    "ANAPHALIS": "Immortelle d'Amérique",
    "ANEMONE": "Anémone",
    "ANGELICA": "Angélique",
    "ANTHEMIS": "Camomille",
    "AQUILEGIA": "Ancolie",
    "ARABIS": "Corbeille d'argent",
    "ARBUTUS": "Arbousier",
    "ARENARIA": "Sabline",
    "ARMERIA": "Gazon d'Espagne",
    "ARONIA": "Aronie",
    "ARTEMISIA": "Armoise",
    "ASPLENIUM": "Doradille",
    "ASTER": "Aster",
    "ASTRANTIA": "Grande astrance",
    "ATHYRIUM": "Fougère femelle",
    "AUBRIETA": "Aubriète",
    "AZALEA": "Azalée",
    "BALLOTA": "Ballote",
    "BERBERIS": "Épine-vinette",
    "BERGENIA": "Bergénia",
    "BETULA": "Bouleau",
    "BRACHYPODIUM": "Brachypode",
    "BRIZA": "Amourette",
    "BUDDLEIA": "Arbre aux papillons",
    "BUDDLEJA": "Arbre aux papillons",
    "BULBINE": "Bulbine",
    "CALAMAGROSTIS": "Calamagrostide",
    "CALISTEMON": "Rince-bouteille",
    "CALLISTEMON": "Rince-bouteille",
    "CALLICARPA": "Arbre aux bonbons",
    "CAMPANULA": "Campanule",
    "CAMPSIS": "Bignone",
    "CARDAMINE": "Cardamine",
    "CAREX": "Laîche",
    "CARPINUS": "Charme",
    "CARYOPTERIS": "Barbe-bleue",
    "CASTANEA": "Châtaignier",
    "CATALPA": "Catalpa",
    "CEANOTHE": "Céanothe",
    "CEANOTHUS": "Céanothe",
    "CENTAUREA": "Centaurée",
    "CENTRANTHUS": "Valériane rouge",
    "CEPHALOTAXUS": "If à prunes",
    "CERASTIUM": "Céraiste",
    "CERATOSTIGMA": "Plumbago rustique",
    "CERCIS": "Arbre de Judée",
    "CHAENOMELES": "Cognassier du Japon",
    "CHAMAECYPARIS": "Faux-cyprès",
    "CHAMAEMELUM": "Camomille romaine",
    "CISTUS": "Ciste",
    "CLERODENDRON": "Arbre du clergé",
    "CLERODENDRUM": "Arbre du clergé",
    "CONVOLVULUS": "Liseron",
    "CORDYLINE": "Cordyline",
    "COREOPSIS": "Coréopsis",
    "CORNUS": "Cornouiller",
    "CORYLUS": "Noisetier",
    "COTINUS": "Arbre à perruque",
    "COTONEASTER": "Cotonéaster",
    "CRATAEGUS": "Aubépine",
    "CROCOSMIA": "Montbrétia",
    "CRYPTOMERIA": "Cèdre du Japon",
    "CUPRESSOCYPARIS": "Cyprès de Leyland",
    "CUPRESSUS": "Cyprès",
    "CYDONIA": "Cognassier",
    "CYRTOMIUM": "Fougère houx",
    "DELOSPERMA": "Pourpier vivace",
    "DESCHAMPSIA": "Canche",
    "DEUTZIA": "Deutzia",
    "DIOSPYROS": "Plaqueminier / Kaki",
    "DORONICUM": "Doronic",
    "DORYCNIUM": "Badasse",
    "DRYOPTERIS": "Fougère mâle",
    "ECHINACEA": "Échinacée",
    "ECHINOPS": "Boule azurée",
    "ECHIUM": "Vipérine",
    "ELAEAGNUS": "Chalef",
    "EPIMEDIUM": "Fleur des elfes",
    "EQUISETUM": "Prêle",
    "ERAGROSTIS": "Éragrostide",
    "ERIGERON": "Vergerette",
    "ERODIUM": "Bec-de-grue",
    "ERYNGIUM": "Panicaut / Chardon bleu",
    "ESCALLONIA": "Escallonia",
    "EUONYMUS": "Fusain",
    "EUPATORIUM": "Eupatoire",
    "EUPHORBIA": "Euphorbe",
    "EXOCHORDA": "Buisson de perles",
    "FAGUS": "Hêtre",
    "FARGESIA": "Bambou non traçant",
    "FESTUCA": "Fétuque",
    "FICUS": "Figuier",
    "FILIPENDULA": "Reine des prés",
    "FOENICULUM": "Fenouil",
    "FORSYTHIA": "Forsythia / Mimosa de Paris",
    "FUCHSIA": "Fuchsia",
    "GAILLARDIA": "Gaillarde",
    "GALIUM": "Gaillet",
    "GAURA": "Gaura",
    "GENISTA": "Genêt",
    "GERANIUM": "Géranium vivace",
    "GINKGO": "Arbre aux quarante écus",
    "GREVILLEA": "Grévilléa",
    "GRISELINA": "Griselinia",
    "GRISELINIA": "Griselinia",
    "HEDERA": "Lierre",
    "HELLEBORUS": "Hellébore / Rose de Noël",
    "HEMEROCALLIS": "Hémérocalle / Lis d'un jour",
    "HEUCHERA": "Heuchère",
    "HIBISCUS": "Hibiscus / Althéa",
    "HOLCUS": "Houlque",
    "HOSTA": "Hosta",
    "HOUTTUYNIA": "Houttuynia",
    "HYACYNTHOIDES": "Jacinthe des bois",
    "HYACINTHOIDES": "Jacinthe des bois",
    "HYDRANGEA": "Hortensia",
    "HYPERICUM": "Millepertuis",
    "HYSSOPUS": "Hysope",
    "IBERIS": "Corbeille d'argent",
    "ILEX": "Houx",
    "IMPERATA": "Herbe sanglante du Japon",
    "IRIS": "Iris",
    "ISOPOGON": "Isopogon",
    "JASMINUM": "Jasmin",
    "JUNCUS": "Jonc",
    "JUNIPERUS": "Genévrier",
    "KERRIA": "Corète du Japon",
    "KNAUTIA": "Knautie",
    "KNIPHOFIA": "Tritome / Tison de Satan",
    "KOELERIA": "Koélérie",
    "KOLKWITZIA": "Buisson de beauté",
    "LABURNUM": "Cytise",
    "LAGERSTROEMIA": "Lilas des Indes",
    "LAURUS": "Laurier-sauce",
    "LAVANDULA": "Lavande",
    "LAVATERA": "Lavatère",
    "LEPTOSPERMUM": "Arbre à thé",
    "LESPEDEZA": "Lespédéza",
    "LEUCANTHEMEUM": "Marguerite",
    "LEUCANTHEMUM": "Marguerite",
    "LEVISTICHUM": "Livèche",
    "LEVISTICUM": "Livèche",
    "LEYCESTERIA": "Arbre aux faisans",
    "LIATRIS": "Plume du Kansas",
    "LIGUSTRUM": "Troène",
    "LIMONIUM": "Statice / Lavande de mer",
    "LIPPIA": "Verveine citronnelle",
    "LIQUIDAMBAR": "Copalme d'Amérique",
    "LIRIODENDRON": "Tulipier de Virginie",
    "LIRIOPE": "Muguet du Japon",
    "LOBELIA": "Lobélie",
    "LONICERA": "Chèvrefeuille",
    "LOROPETALUM": "Loropétale de Chine",
    "LUZULA": "Luzule",
    "LYTHRUM": "Salicaire",
    "MAGNOLIA": "Magnolia",
    "MAHONIA": "Mahonia",
    "MALUS": "Pommier",
    "MALVA": "Mauve",
    "MALVASTRUM": "Fausse mauve",
    "MATTEUCCIA": "Fougère plume d'autruche",
    "MELICA": "Mélique",
    "MELISSA": "Mélisse",
    "MENTHA": "Menthe",
    "MISCANTHUS": "Roseau de Chine",
    "MOLINIA": "Molinie",
    "MORUS": "Mûrier",
    "MUEHLENBECKIA": "Muehlenbeckia",
    "MUHLENBERGIA": "Muhlenbergia",
    "MUSCARI": "Muscari",
    "NANDINA": "Bambou sacré",
    "NEPETA": "Népéta / Herbe à chat",
    "OENOTHERA": "Onagre",
    "OPHIOPOGON": "Barbe de serpent",
    "ORIGANUM": "Origan",
    "OSMANTHUS": "Osmanthe",
    "OSMUNDA": "Osmonde royale",
    "OXALIS": "Oxalis",
    "PACHYSANDRA": "Pachysandre",
    "PANICUM": "Panic érigé",
    "PANUICUM": "Panic érigé",
    "PASSIFLORE": "Passiflore",
    "PASSIFLORA": "Passiflore",
    "PAULOWNIA": "Paulownia",
    "PENNISETUM": "Herbe aux écouvillons",
    "PEROVSKIA": "Sauge d'Afghanistan",
    "PERSICARIA": "Renouée",
    "PHILADELPHUS": "Seringat",
    "PHILLYREA": "Filaire",
    "PHLOMIS": "Sauge de Jérusalem",
    "PHLOX": "Phlox",
    "PHORMIUM": "Lin de Nouvelle-Zélande",
    "PHOTINIA": "Photinia",
    "PHRAGMITES": "Roseau commun",
    "PHYSOCARPUS": "Physocarpe",
    "PICEA": "Épicéa",
    "PINUS": "Pin",
    "PITTOSPORUM": "Pittospore",
    "PLATANUS": "Platane",
    "POLYGONUM": "Renouée",
    "POLYPODIUM": "Polypode",
    "POLYSTICHUM": "Fougère polystic",
    "POPULUS": "Peuplier",
    "POTENTILLA": "Potentille",
    "PRUNUS": "Prunus (cerisier, prunier, laurier)",
    "PYRACANTHA": "Buisson ardent",
    "PYRUS": "Poirier",
    "RAPHIOKLEPSIS": "Raphiolépis",
    "RHAPHIOLEPIS": "Raphiolépis",
    "RHAMNUS": "Nerprun",
    "RHEUM": "Rhubarbe",
    "RIBES": "Groseillier",
    "ROBINIA": "Robinier / Faux-acacia",
    "ROSA": "Rosier",
    "ROSMARINUS": "Romarin",
    "RUBUS": "Ronce",
    "RUDBECKIA": "Rudbeckie",
    "RUMEX": "Oseille",
    "RUTA": "Rue officinale",
    "SAGINA": "Sagine",
    "SALIX": "Saule",
    "SALVIA": "Sauge",
    "SAMBUCUS": "Sureau",
    "SANGUISORBA": "Pimprenelle",
    "SANTOLINA": "Santoline",
    "SAPONARIA": "Saponaire",
    "SATUREJA": "Sarriette",
    "SCABIOSA": "Scabieuse",
    "SCIADOPITYS": "Pin parasol du Japon",
    "SEDUM": "Orpin",
    "SESLERIA": "Seslérie",
    "SOLIDAGO": "Verge d'or",
    "SOLIDASTER": "Solidaster",
    "SORBUS": "Sorbier",
    "SPIRAEA": "Spirée",
    "STACHYS": "Épiaire / Oreille d'ours",
    "STIPA": "Cheveux d'ange",
    "SYMPHORICARPOS": "Symphorine",
    "SYRINGA": "Lilas",
    "TAMARIX": "Tamaris",
    "TAXUS": "If",
    "TETRADIUM": "Arbre à miel",
    "TEUCRIUM": "Germandrée",
    "THUYA": "Thuya",
    "THUJA": "Thuya",
    "THYMUS": "Thym",
    "TIARELLA": "Tiarelle",
    "TILIA": "Tilleul",
    "TRACHELOPERMUM": "Jasmin étoilé",
    "TRACHELOSPERMUM": "Jasmin étoilé",
    "TULBAGHIA": "Ail d'Afrique du Sud",
    "ULMUS": "Orme",
    "VACCINUM": "Myrtillier",
    "VACCINIUM": "Myrtillier",
    "VALERIANA": "Valériane",
    "VERBENA": "Verveine",
    "VERONICA": "Véronique",
    "VIBURNUM": "Viorne",
    "VINCA": "Pervenche",
    "VIOLA": "Violette",
    "VITEX": "Gattilier",
    "VITIS": "Vigne",
    "WEIGELIA": "Weigélia",
    "WEIGELA": "Weigélia",
    "YUCCA": "Yucca",
}

# Especes particulieres ou le nom commun differe fortement du genre
NOMS_ESPECES = {
    "ACER CAMPESTRE": "Érable champêtre",
    "ACER PLATANOIDES": "Érable plane",
    "ACER PSEUDOPLATANUS": "Érable sycomore",
    "ACER PALMATUM": "Érable du Japon",
    "ACER NEGUNDO": "Érable negundo",
    "ALNUS GLUTINOSA": "Aulne glutineux",
    "BETULA PENDULA": "Bouleau verruqueux",
    "CARPINUS BETULUS": "Charme commun",
    "CORNUS MAS": "Cornouiller mâle",
    "CORNUS SANGUINEA": "Cornouiller sanguin",
    "CORNUS ALBA": "Cornouiller blanc",
    "CORYLUS AVELLANA": "Noisetier commun",
    "CRATAEGUS MONOGYNA": "Aubépine monogyne",
    "EUONYMUS EUROPAEUS": "Fusain d'Europe",
    "EUONYMUS FORTUNEI": "Fusain de Fortune",
    "FAGUS SYLVATICA": "Hêtre commun",
    "FRAXINUS EXCELSIOR": "Frêne commun",
    "HEDERA HELIX": "Lierre commun",
    "ILEX AQUIFOLIUM": "Houx commun",
    "LIGUSTRUM VULGARE": "Troène commun",
    "LIGUSTRUM OVALIFOLIUM": "Troène de Californie",
    "LONICERA NITIDA": "Chèvrefeuille à feuilles de buis",
    "PRUNUS AVIUM": "Merisier",
    "PRUNUS SPINOSA": "Prunellier",
    "PRUNUS LAUROCERASUS": "Laurier-cerise",
    "PRUNUS LUSITANICA": "Laurier du Portugal",
    "PRUNUS SERRULATA": "Cerisier du Japon",
    "PRUNUS DOMESTICA": "Prunier",
    "PRUNUS PERSICA": "Pêcher",
    "PRUNUS ARMENIACA": "Abricotier",
    "PRUNUS CERASUS": "Cerisier",
    "QUERCUS ROBUR": "Chêne pédonculé",
    "SALIX ALBA": "Saule blanc",
    "SALIX CAPREA": "Saule marsault",
    "SAMBUCUS NIGRA": "Sureau noir",
    "SORBUS AUCUPARIA": "Sorbier des oiseleurs",
    "TILIA CORDATA": "Tilleul à petites feuilles",
    "ULMUS CAMPESTRIS": "Orme champêtre",
    "VIBURNUM OPULUS": "Viorne obier",
    "VIBURNUM TINUS": "Laurier-tin",
    "VIBURNUM LANTANA": "Viorne lantane",
    "MALUS DOMESTICA": "Pommier fruitier",
    "PYRUS COMMUNIS": "Poirier fruitier",
    "FICUS CARICA": "Figuier commun",
    "VACCINUM CORYMBOSUM": "Myrtillier américain",
    "VACCINIUM CORYMBOSUM": "Myrtillier américain",
    "RIBES RUBRUM": "Groseillier à grappes",
    "RIBES NIGRUM": "Cassissier",
    "RIBES UVA-CRISPA": "Groseillier à maquereau",
    "CASTANEA SATIVA": "Châtaignier commun",
    "GINKGO BILOBA": "Ginkgo biloba",
    "LAURUS NOBILIS": "Laurier-sauce",
    "ROSMARINUS OFFICINALIS": "Romarin officinal",
    "LAVANDULA ANGUSTIFOLIA": "Lavande vraie",
    "LAVANDULA STOECHAS": "Lavande papillon",
    "SALVIA OFFICINALIS": "Sauge officinale",
    "THYMUS VULGARIS": "Thym commun",
    "MENTHA SPICATA": "Menthe verte",
    "VINCA MINOR": "Petite pervenche",
    "VINCA MAJOR": "Grande pervenche",
    "PRUNUS CERASIFERA": "Prunier myrobolan",
    "PRUNUS PADUS": "Merisier à grappes",
    "PRUNUS DULCIS": "Amandier",
    "PRUNUS SUBHIRTELLA": "Cerisier d'hiver",
    "PRUNUS TRILOBA": "Amandier de Chine",
    "SPIRAEA JAPONICA": "Spirée du Japon",
    "COTONEASTER HORIZONTALIS": "Cotonéaster horizontal",
    "COTONEASTER DAMMERI": "Cotonéaster rampant",
    "HYDRANGEA MACROPHYLLA": "Hortensia commun",
    "HYDRANGEA PANICULATA": "Hortensia paniculé",
    "HYDRANGEA QUERCIFOLIA": "Hortensia à feuilles de chêne",
    "PHOTINIA FRASERI": "Photinia rouge",
    "ELAEAGNUS EBBINGEI": "Chalef de Ebbinge",
    "BERBERIS THUNBERGII": "Épine-vinette de Thunberg",
    "CORNUS FLORIDA": "Cornouiller à fleurs",
    "CORNUS KOUSA": "Cornouiller du Japon",
    "MAGNOLIA GRANDIFLORA": "Magnolia à grandes fleurs",
    "MAGNOLIA SOULANGEANA": "Magnolia de Soulange",
    "TILIA TOMENTOSA": "Tilleul argenté",
    "CATALPA BIGNONIOIDES": "Catalpa commun",
    "CATALPA BIGNOIDES": "Catalpa commun",
    "GLEDITSIA TRIACANTHOS": "Févier d'Amérique",
    "LIQUIDAMBAR STYRACIFLUA": "Copalme d'Amérique",
    "PAULOWNIA TOMENTOSA": "Arbre impérial",
    "ALBIZZIA JULIBRISSIN": "Arbre à soie",
    "CERCIS SILIQUASTRUM": "Arbre de Judée",
    "ARBUTUS UNEDO": "Arbousier commun",
    "PHILLYREA ANGUSTIFOLIA": "Filaire à feuilles étroites",
    "PITTOSPORUM TOBIRA": "Pittospore du Japon",
    "NANDINA DOMESTICA": "Bambou sacré",
    "TRACHELOSPERMUM JASMINOIDES": "Jasmin étoilé",
    "LONICERA JAPONICA": "Chèvrefeuille du Japon",
    "PYRACANTHA COCCINEA": "Buisson ardent",
    "TAXUS BACCATA": "If commun",
    "PINUS SYLVESTRIS": "Pin sylvestre",
    "PINUS NIGRA": "Pin noir",
    "PINUS PINEA": "Pin parasol",
    "PICEA ABIES": "Épicéa commun",
    "JUNIPERUS COMMUNIS": "Genévrier commun",

}
