# -*- coding: utf-8 -*-
"""Systeme racinaire.

Pour chaque espece : (type, profondeur en m, distance de securite en m)

Types :
    piv  pivotant            racine verticale profonde
    tra  tracant             racines horizontales lointaines
    sup  superficiel etale   dense en surface, large
    fas  fascicule           chevelu compact
    dra  drageonnant         rejets a distance du pied
    cha  charnu fragile      racines cassantes, transplantation impossible

La distance de securite s'entend vis-a-vis des canalisations, fosses, murs
et dallages. Valeur 0 : aucune precaution particuliere.

Les valeurs sont des ordres de grandeur en conditions courantes. Un meme
sujet pivote en terrain profond et s'etale sur substrat superficiel.
"""

TYPES = {
    "piv": ("Pivotant", "Racine verticale profonde, ancrage puissant. Résiste bien à la sécheresse mais supporte mal la transplantation une fois installé."),
    "tra": ("Traçant", "Racines horizontales s'étendant loin du pied, souvent au-delà de l'aplomb du feuillage. À éloigner des réseaux et des ouvrages."),
    "sup": ("Superficiel étalé", "Réseau dense dans les premiers décimètres, sur une large surface. Complique les plantations au pied et peut soulever les dallages."),
    "fas": ("Fasciculé", "Chevelu compact et localisé. Sans risque pour les ouvrages, reprise et transplantation faciles."),
    "dra": ("Drageonnant", "Émet des rejets à distance du pied et forme progressivement une colonie. À contenir ou à isoler."),
    "cha": ("Charnu fragile", "Racines épaisses et cassantes. Ne pas travailler le sol au pied, ne jamais déplacer une fois installé."),
}

# Valeurs par défaut appliquées quand l'espèce n'est pas listée ci-dessous
DEFAUTS = {
    "Vivace":      ("fas", 0.4, 0),
    "Couvre-sol":  ("fas", 0.3, 0),
    "Graminée":    ("fas", 0.5, 0),
    "Fougère":     ("fas", 0.3, 0),
    "Aromatique":  ("fas", 0.4, 0),
    "Arbuste":     ("fas", 0.8, 1.0),
    "Grimpante":   ("fas", 0.8, 1.5),
    "Conifère":    ("sup", 1.0, 2.0),
    "Fruitier":    ("fas", 1.2, 3.0),
    "Arbre":       ("sup", 1.5, 5.0),
}

RACINES = {

# ---------------------------------------------------------------- arbres
"Acer campestris":        ("sup", 1.2, 4),
"Acer negundo":           ("sup", 1.0, 5),
"Acer palmatum":          ("sup", 0.6, 1.5),
"Acer platanoides":       ("sup", 1.2, 6),
"Acer rubrum":            ("sup", 1.2, 5),
"Acer sac":               ("tra", 1.2, 8),
"Albizzia julibrissin":   ("sup", 1.0, 4),
"Alnus glutinosa":        ("tra", 1.5, 6),
"Amelanchier lamarckii":  ("fas", 1.0, 2),
"Betula verrucosa":       ("sup", 0.8, 5),
"Carpinus betulus":       ("piv", 2.0, 4),
"Castanea sativa":        ("piv", 2.5, 8),
"Catalpa bignoides":      ("sup", 1.2, 5),
"Cercis siliquastrum":    ("cha", 1.5, 3),
"Corylus avellana":       ("dra", 1.0, 3),
"Fagus sylvatica":        ("sup", 1.5, 8),
"Ginkgo biloba":          ("piv", 2.5, 4),
"Laburnum anagyroides":   ("piv", 1.5, 3),
"Lagerstroemia indica":   ("fas", 1.2, 2),
"Liquidambar styraciflua":("piv", 2.0, 5),
"Liriodendron tulipifera":("piv", 2.5, 8),
"Magnolia soulangiana":   ("cha", 1.0, 3),
"Magnolia stellata":      ("cha", 0.8, 2),
"Malus coccinela":        ("fas", 1.2, 3),
"Morus kagayamae":        ("sup", 1.2, 4),
"Paulownia":              ("tra", 1.5, 6),
"Picea abies":            ("sup", 1.0, 5),
"Pinus sylvestris":       ("piv", 3.0, 5),
"Platanus acerifolia":    ("tra", 2.0, 12),
"Populus tremula":        ("dra", 1.5, 12),
"Prunus cerasifera":      ("sup", 1.2, 4),
"Prunus serrulata":       ("sup", 0.8, 3),
"Robinia pseudoacacia":   ("dra", 2.0, 8),
"Salix babylonica":       ("tra", 1.5, 15),
"Salix caprea":           ("tra", 1.2, 6),
"Sorbus aucuparia":       ("fas", 1.2, 3),
"Tetradium danielli":     ("piv", 1.8, 5),
"Tilia cordata":          ("sup", 1.8, 8),
"Tilia platyphyllos":     ("sup", 2.0, 10),
"Ulmus campestris":       ("dra", 1.8, 8),

# ------------------------------------------------------------ fruitiers
"Actinidia deliciosa":    ("fas", 1.0, 3),
"Cydonia oblanga":        ("fas", 1.2, 3),
"Diospyros":              ("piv", 1.8, 4),
"Ficus carica":           ("tra", 1.2, 6),
"Malus domestica":        ("fas", 1.2, 3),
"Prunus armeniaca":       ("fas", 1.5, 4),
"Prunus avium":           ("tra", 1.5, 6),
"Prunus domestica":       ("dra", 1.2, 4),
"Prunus persica":         ("fas", 1.2, 3),
"Pyrus domestica":        ("piv", 2.0, 4),
"Ribes rubrum":           ("fas", 0.6, 0),
"Ribes uva-crispa":       ("fas", 0.6, 0),
"Rubus fructicosus":      ("dra", 0.8, 1.5),
"Rubus idaeus":           ("dra", 0.6, 1.5),
"Vaccinum corymbosum":    ("fas", 0.4, 0),

# ------------------------------------------------------------ conifères
"Cephalotaxus fastigiata":("fas", 0.8, 1),
"Chamaecyparis obtusa":   ("fas", 0.8, 1.5),
"Cryptomeria japonica":   ("sup", 1.0, 3),
"Cupressocyparis leylandii":("tra", 1.2, 5),
"Cupressus sempervirens": ("piv", 2.0, 2),
"Juniperus chin":         ("fas", 0.8, 1),
"Juniperus communis":     ("piv", 1.5, 1),
"Pinus mugo":             ("piv", 1.2, 1),
"Sciadopitys verticillata":("fas", 0.8, 2),
"Taxus baccata":          ("fas", 1.2, 2),
"Thuya plicata":          ("sup", 1.0, 3),

# ---------------------------------------------- arbustes à surveiller
"Aronia prunifolia":      ("dra", 0.8, 1),
"Berberis thunbergii":    ("fas", 0.8, 0),
"Buddleia davidii":       ("fas", 1.0, 2),
"Clerodendron bungei":    ("dra", 0.6, 2),
"Cornus alba":            ("dra", 0.8, 1),
"Cornus mas":             ("piv", 1.5, 2),
"Cornus sanguinea":       ("dra", 1.0, 2),
"Crataegus monogyna":     ("piv", 2.0, 3),
"Elaeagnus ebbingei":     ("fas", 1.0, 1.5),
"Euonymus europaeus":     ("dra", 1.0, 1.5),
"Hibiscus syriacus":      ("piv", 1.2, 1.5),
"Hydrangea macrophylla":  ("sup", 0.5, 0),
"Hydrangea paniculata":   ("sup", 0.6, 0),
"Hydrangea quercifolia":  ("sup", 0.5, 0),
"Hydrangea arborescens":  ("dra", 0.5, 0),
"Hydrangea aspera":       ("sup", 0.6, 0),
"Kerria japonica":        ("dra", 0.5, 1.5),
"Leycesteria formosa":    ("fas", 0.6, 0),
"Ligustrum vulgare":      ("fas", 1.0, 1.5),
"Ligustrum japonicum":    ("fas", 1.0, 1.5),
"Ligustrum ovalifolium":  ("fas", 1.0, 2),
"Lonicera nitida":        ("fas", 0.6, 0),
"Prunus laurocerasus":    ("sup", 1.0, 2),
"Prunus lusitanica":      ("fas", 1.0, 1.5),
"Prunus spinosa":         ("dra", 1.2, 3),
"Rhamnus frangula":       ("fas", 1.0, 1),
"Rosa rugosa":            ("dra", 0.8, 2),
"Salix purpurea":         ("tra", 1.0, 5),
"Sambucus nigra":         ("dra", 1.0, 2),
"Symphoricarpos doorenbosii":("dra", 0.6, 1.5),
"Syringa vulgaris":       ("dra", 1.2, 2),
"Tamarix africana":       ("piv", 2.0, 3),
"Viburnum opulus":        ("dra", 1.0, 1.5),
"Arbutus unedo":          ("fas", 1.2, 2),
"Phillyrea angustifolia": ("piv", 1.5, 1),
"Photinia fraseri":       ("fas", 0.8, 1),
"Pittosporum tenuifolium":("fas", 0.8, 1),
"Griselina litoralis":    ("fas", 0.8, 1),
"Escallonia":             ("fas", 0.8, 1),
"Laurus nobilis":         ("dra", 1.2, 2),
"Cotinus coggygria":      ("piv", 1.5, 2),
"Ilex aquifolium":        ("piv", 1.5, 2),
"Ilex crenata":           ("fas", 0.6, 0),
"Osmanthus burkwoodii":   ("fas", 0.8, 1),
"Physocarpus opulifolius":("fas", 0.8, 0),
"Callicarpa bodinieri":   ("fas", 0.8, 0),
"Euonymus alatus":        ("fas", 0.8, 0),
"Lespedeza thunbergii":   ("piv", 1.0, 0),
"Genista porlock":        ("piv", 1.5, 0),
"Vitex agnus":            ("piv", 1.5, 1.5),
"Nandina domestica":      ("dra", 0.6, 0),
"Fargesia murielae":      ("fas", 0.6, 0),
"Muehlenbeckia complexa": ("dra", 0.6, 1),

# ----------------------------------------------------------- grimpantes
"Campsis":                ("dra", 1.0, 4),
"Polygonum aubertii":     ("tra", 1.0, 4),
"Hedera":                 ("sup", 0.8, 2),
"Hydrangea petiolaris":   ("sup", 0.8, 1.5),
"Akebia quinata":         ("fas", 0.8, 1.5),
"Lonicera japonica":      ("dra", 0.8, 2),
"Jasminum officinalis":   ("fas", 0.8, 1),
"Passiflore":             ("dra", 0.8, 2),
"Trachelospermum jasminoides":("fas", 0.8, 1),
"Vitis vinifera":         ("piv", 2.5, 2),

# ---------------------------------------- vivaces et couvre-sols notables
"Acanthus mollis":        ("cha", 1.0, 1),
"Eryngium planum":        ("piv", 1.0, 0),
"Echinops ritro":         ("piv", 1.0, 0),
"Limonium latifolium":    ("piv", 0.8, 0),
"Centranthus ruber":      ("piv", 0.8, 0),
"Foeniculum vulgare":     ("piv", 1.0, 0),
"Levistichum officinalis":("piv", 1.0, 0),
"Angelica archangelica":  ("piv", 0.8, 0),
"Rheum palmatum":         ("cha", 0.8, 0),
"Anemone hupehensis":     ("dra", 0.5, 0),
"Alstroemeria":           ("cha", 0.6, 0),
"Crocosmia crocosmiiflora":("fas", 0.3, 0),
"Agapanthus africanus":   ("cha", 0.5, 0),
"Hemerocallis":           ("fas", 0.6, 0),
"Iris germanica":         ("sup", 0.2, 0),
"Iris pseudacorus":       ("dra", 0.4, 0),
"Phragmites australis":   ("dra", 1.0, 3),
"Equisetum hyemale":      ("dra", 0.8, 3),
"Houttuynia cordata":     ("dra", 0.4, 2),
"Mentha spicata":         ("dra", 0.3, 1),
"Vinca":                  ("dra", 0.3, 0),
"Hypericum calycinum":    ("dra", 0.4, 0),
"Persicaria affinis":     ("dra", 0.3, 0),
"Ajuga reptans":          ("dra", 0.2, 0),
"Galium odoratum":        ("dra", 0.2, 0),
"Pachysandra terminalis": ("dra", 0.3, 0),
"Matteuccia struthiopteris":("dra", 0.3, 0),
"Solidago canadensis":    ("dra", 0.6, 0),
"Ceratostigma plumbaginoides":("dra", 0.4, 0),
"Holcus mollis":          ("dra", 0.3, 0),
"Liriope muscari":        ("fas", 0.4, 0),
"Ophiopogon planiscapus": ("dra", 0.3, 0),
"Geranium macrorrhizum":  ("dra", 0.3, 0),
"Miscanthus sinensis":    ("fas", 0.8, 0),
"Molinia arundinacea":    ("fas", 0.7, 0),
"Lythrum salicaria":      ("fas", 0.6, 0),
"Filipendula ulmaria":    ("dra", 0.5, 0),
"Eupatorium cannabinum":  ("fas", 0.8, 0),
"Yucca filamentosa":      ("piv", 1.0, 0),
"Yucca rostrata":         ("piv", 1.2, 0),
"Phormium tenax":         ("fas", 0.8, 1),
"Cordyline australis":    ("fas", 1.0, 1),
"Euphorbia characias":    ("piv", 0.8, 0),
"Ruta graveolens":        ("piv", 0.6, 0),
"Lavandula angustifolia": ("piv", 0.6, 0),
"Lavandula intermedia":   ("piv", 0.7, 0),
"Rosmarinus officinalis": ("piv", 1.0, 0),
"Cistus corbariensis":    ("piv", 0.8, 0),
"Cistus purpureus":       ("piv", 0.8, 0),
"Cistus pulverulentus":   ("piv", 0.8, 0),
"Perovskia atriplicifolia":("piv", 0.8, 0),
"Sedum acre":             ("fas", 0.1, 0),
"Delosperma cooperi":     ("fas", 0.1, 0),
"Thymus serpyllum":       ("fas", 0.15, 0),
"Sagina subulata":        ("fas", 0.1, 0),
"Armeria maritima":       ("piv", 0.4, 0),
"Muscari armeniacum":     ("fas", 0.15, 0),
"Hyacynthoides non-scripta":("fas", 0.2, 0),
}
